controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_suite_test.go

This patch temporarily disables an IT related to the CLS controller that is going away anyway.

Temporarily disable a CLS IT

---

api/v1alpha1/condition_consts.go
api/v1alpha1/virtualmachinepublishrequest_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_suite_test.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_intg_test.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_suite_test.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
pkg/vmprovider/fake/fake_vm_provider.go
pkg/vmprovider/interface.go
pkg/vmprovider/providers/vsphere/contentlibrary/content_library_provider.go
pkg/vmprovider/providers/vsphere/vmprovider.go
test/builder/test_suite.go
webhooks/virtualmachinepublishrequest/validation/virtualmachinepublishrequest_validator_intg_test.go

This change includes:
- Add VirtualMachinePublishRequest condition reasons to API.
- Add more details to SourceValid/TargetValid check.
- Source VM should be created.
- Target item name should be unique in the CL.
- Target CL should be writable.
- Add condition Upload implementation.
- VM publish succeeded, mark Uploaded to true. Otherwise, mark to false.
- Add condition ImageAvailable implementation.
- If a namespace scoped VMI is created, mark ImageAvailable to true.
- Add condition Complete implementation. Remove vmpub resource if ttlSecondsAfterFinished is set.
- Fix update VMI scope in integration tests and re-enable ContentLibraryItem intg tests.
Test done:
- Create a VirtualMachinePublishRequest with invalid source VM.
```
Status:
Conditions:
Last Transition Time: …
```

Add conditions check in VirtualMachinePublishRequest controller

---

README.md

This change fixes a minor link typo in `README.md`. Previously, the link for Ellen Mei would point to https://github.com/vmware-tanzu/vm-operator/blob/main/meie@vmware.com, which does not exist.

Fix e-mail link in README

---

api/v1alpha1/virtualmachineimage_types.go
config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml

This change removed internalID from required fields in VMI/CVMI Status since it's already deprecated.

Removed internalID from required field

---

Makefile
config/crd/external-crds/imageregistry.vmware.com_clustercontentlibraries.yaml
config/crd/external-crds/imageregistry.vmware.com_clustercontentlibraryitems.yaml
config/crd/external-crds/imageregistry.vmware.com_contentlibraries.yaml
controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_intg_test.go
controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_unit_test.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_intg_test.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_unit_test.go
controllers/contentlibrary/utils/test_utils.go

This change includes:
-  Update `external-crds` yaml files.
-  Add `securityCompliance` check for `clustercontentlibraryitem` and `conternlibraryitem` controllers. 
- When the `securityCompliance` field of a `ContentLibraryItem` or `ClusterContentLibraryItem` is not set or is set to be false, the controller should not create corresponding `VirtualMachineImage` or `ClusterVirtualMachineImage`. If already exists, should delete `VirtualMachineImage` or `ClusterVirtualMachineImage` since Content Library doesn't support deploying such VM images.

Add security compliance check for clustercontentlibraryitem and contentlibraryitem controllers

---

api/v1alpha1/virtualmachineimage_types.go
config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
docs/user-guide/apis/v1alpha1.md
images/ttylinux-pc_i486-16.1.ovf
pkg/vmprovider/providers/vsphere/contentlibrary/content_library_provider.go
pkg/vmprovider/providers/vsphere/contentlibrary/content_library_test.go
pkg/vmprovider/providers/vsphere/contentlibrary/content_library_utils.go
pkg/vmprovider/providers/vsphere/virtualmachine/configspec.go
pkg/vmprovider/providers/vsphere/virtualmachine/configspec_test.go
pkg/vmprovider/providers/vsphere/vmprovider_vm.go

The firmware status field for a virtualmachineimage gets populated when creating the vmi. The firmware config string if populated in the ovf image will be consumed when the vm class config spec does not specify firmware type.
This helps prevent issues with deploying images that don't support a specific type of firmware (ie) efi,bios and default to the image as the baseline unless otherwise specified by the vi admin via the vmclass.
Testing: 
- make test
- Manual testing with centos marketplace using OvfEnv transport

Introduce VirtualMachineImage Firmware status field and utilize with deployment Config Spec

---

controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_unit_test.go
controllers/contentlibrary/utils/test_utils.go

After below discussion, image registry will use the label `servicetype.iaas.vmware.com/tkg` for TKG ClusterContentLibrary and ClusterContentLibraryItem in order to distinguish them from the other cluster scoped content library and content library item resources.
This change propagates the label to ClusterVirtualMachineImage resources corresponding to the TKG content library items as well.
Test done:
```
NAME                    PROVIDER-NAME              CONTENT-LIBRARY-NAME   IMAGE-NAME                                                                  VERSION                           OS-TYPE               FORMAT   AGE   LABELS
vmi-0b5e4855a0f850ba8   clitem-0b5e4855a0f850ba8   cl-cbe1f4d63cf1d1877   ob-17861429-photon-3-k8s-v1.20.2---vmware.1-tkg.1.1d4f79a …
```

Propagate TKG labels to cvmi

---

controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_intg_test.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
pkg/vmprovider/providers/vsphere/virtualmachine/publish.go
pkg/vmprovider/providers/vsphere/virtualmachine/publish_test.go
webhooks/virtualmachinepublishrequest/validation/virtualmachinepublishrequest_validator.go
webhooks/virtualmachinepublishrequest/validation/virtualmachinepublishrequest_validator_intg_test.go

The VirtualMachinePublishRequest .spec.target.item.name is optional and we will set a default name if it is empty, which is <source vm name> + image. We will not mutate target item name in the spec, but instead update targetRef in the status. In other words, we will always set targetRef item information in the status no matter if .spec.target.item.name is set or not. Use .status.targetRef.item.name can guarantee that we use the right item name when publishing VMs.
This change includes:
- when target item name is not set, use <source-vm>-image as default target item name.
- Use .status.targetRef.item as the publish VM info
- Also fix VirtualMachinePublishRequest webhook and controller integration tests.
Test done:
- Manually deployed to a WCP testbed.
```
apiVersion: …
```

Fix issues when target item name is not set.

---

controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
pkg/metrics/vmpub_metrics.go

This PR adds a new `pkg/metrics/vmpub_metrics.go` file which introduces `vm_publish_request` metrics registered in the `virtualmachinepublishrequest` controller. This will give us better visibility on VM publish request results and the ability to measure the percentage of successful publish requests.
Testing Done:
- Metrics registration
```console
$ curl -s localhost:8083/metrics | grep vm_publish
vmservice_vm_publish_request{name="packer-vsphere-supervisor-crrhw",namespace="sdiliyaer-test"} 0
vmservice_vm_publish_request{name="test-ubuntu",namespace="sdiliyaer-test"} 0
vmservice_vm_publish_request{name="vmpub-test-metrics",namespace="yijiang-ns"} -1
```
- Metrics deletion
```console
$ curl -s localhost:8083/metrics  | grep vm_publish …
```

Add VM publish related metrics in virtualmachinepublishrequest controller

---

api/v1alpha1/virtualmachineclass_types.go
api/v1alpha1/zz_generated.deepcopy.go
docs/user-guide/apis/v1alpha1.md
pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go

This patch updates the `VirtualMachineClass.Spec.ConfigSpec` to be `json.RawMessage`, which is similar to `runtime.RawExtension`, but has no opinion about being a `runtime.Object`.
Per https://github.com/kubernetes-sigs/controller-tools/issues/637, it was necessary to decorate the field with the following kubebuilder annotations to force the wire protocol to be an object:
```go
// +kubebuilder:validation:Schemaless
// +kubebuilder:validation:Type=object
// +kubebuilder:pruning:PreserveUnknownFields
```

Update VMClass.Spec.ConfigSpec to be RawMessage

---

controllers/virtualmachine/virtualmachine_controller.go
controllers/virtualmachine/virtualmachine_controller_unit_test.go
pkg/context/context.go
pkg/lib/env.go
pkg/vmprovider/providers/vsphere/vmprovider_vm.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go

This patch updates the way VM Operator handles `MaxDeployThreads`. The value used to be hardcoded as `80%` of the `MaxConcurrentReconciles`, which is `20`. However, `MaxConcurrentReconciles` is configurable via the VM Operator deployment, so `80%` of `20`, which is `16`, should increase or decrease if `MaxConcurrentReconciles` does as well. This patch now derives `MaxDeployThreads` by looking at the environment variable `MAX_CREATE_VMS_ON_PROVIDER` which is expected to be a whole number that represents the percentage of the `MaxConcurrentReconciles` that equals `MaxDeployThreads`. `MaxDeployThreads` is then calculated by `MaxConcurrentReconciles / (100 / MaxDeployThreadsEnvVarValue)`. If the env var is not set then it defaults to `80`.

Update MaxDeployThreads to be configurable

---

pkg/vmprovider/providers/vsphere/session/session_vm_update.go
pkg/vmprovider/providers/vsphere/vmprovider_vm.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go

The outer VM provider code was incorrectly using the VMSetResourcePolicy's VirtualMachineClassResources field instead of the corresponding field from the VM Class. The former was meant for the TKG child ResourcePool but code setting that was never implemented in CAPV/CAPW, while the later is one for the actual VM.
Add tests to assert the expected VM ConfigInfo.

Use proper field for VM CPU limit & reservation

---

pkg/vmprovider/providers/vsphere/session/session_vm_create.go
pkg/vmprovider/providers/vsphere/session/session_vm_update.go
pkg/vmprovider/providers/vsphere/session/session_vm_update_test.go
pkg/vmprovider/providers/vsphere/vmprovider_vm.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go

This patch updates instances of the feature state switch from `WCP_VM_Class_as_Config` to the DaynDate variation. The original feature state switch is not removed entirely as it will be reused for a follow-up release.

Update uses of WCP_VM_Class_as_Config to DND

---

.github/configs/labeler.yml
.github/workflows/ci.yml
.github/workflows/labeler.yml

This patch adds a new GitHub action that automatically attaches labels to PRs based on their LoC.
It can also be served as a reminder for developers to conduct necessary testing for PRs with large LoC.
Testing Done:
- Updated my fork `main` branch with this change pushed
- Created a PR against my fork with different LoC changing
- Confirmed the labels are added/removed in the PR accordingly
Screenshot of the [above PR](https://github.com/dilyar85/vm-operator/pull/3) in my fork:

Add PR labeler based on LoC

---

pkg/vmprovider/providers/vsphere/config/config.go
pkg/vmprovider/providers/vsphere/network/network_provider.go
pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
pkg/vmprovider/providers/vsphere/session/session_vm_customization_test.go
pkg/vmprovider/providers/vsphere/session/session_vm_update.go
pkg/vmprovider/providers/vsphere/session/session_vm_update_test.go

This patch enables the automatic propogation of Supervisor DNS search suffixes for VMs created on behalf of Cluster API on Supervisor. If a VM has the label "capw.vmware.com/cluster.role" or "capv.vmware.com/cluster.role", then VM Operator will read the DNS search suffix information from the VM Op ConfigMap on Supervisor and use that information when constructing the netplan payload used to configure the VM's networking with Cloud-Init.
A few notes:
* This only works for TKGs nodes deployed with VM Op that set their bootstrap provider type to CloudInit in the VM Op VM resource.
* This is a band-aid until VM Op API is updated to express the full netplan configuration, at which point CAPV can use that to set DNS search suffixes when deploying VMs with VM Op.

tkg: Propogate Supervisor DNS Search Suffixes for TKGs nodes

---

pkg/vmprovider/providers/vsphere/constants/constants.go
pkg/vmprovider/providers/vsphere/session/session_vm_update.go
pkg/vmprovider/providers/vsphere/session/session_vm_update_test.go
pkg/vmprovider/providers/vsphere/virtualmachine/configspec.go
pkg/vmprovider/providers/vsphere/virtualmachine/configspec_test.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go

In update path of a VM reconcile, we reconfigure the VM to match the desired config specified in the VM Class.  This means that if a VM class is edited _after_ a VM has already been created from it, we will end up Reconfiguring the VM during next power cycle.  This was never a supported workflow and was just a by product of the original implementation.
With VM Class as Config, we are creating the VM with hardware spec and RLS settings specified form the VM class.  So, we don't need to update these during update.  This change preserves the behavior for clusters that do not have the feature enabled.
Testing Done:

Do not consider hardware spec and RLS settings in Update path

---

pkg/vmprovider/providers/vsphere/session/session_vm_update.go

If the vm. Annotations is nil, and assign entry to it will cause panic. This PR fix this issue by adding a check before assigning.

Fix nil map in UpdateVirtualMachine

---

pkg/util/devices.go
pkg/util/devices_test.go
pkg/vmprovider/providers/vsphere/session/session_vm_update.go
pkg/vmprovider/providers/vsphere/session/session_vm_update_test.go
pkg/vmprovider/providers/vsphere/virtualmachine/configspec.go
pkg/vmprovider/providers/vsphere/virtualmachine/devices.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go

After VM Class as Config is enabled, a ConfigSpec is always expected to (mostly) accurately represent the desired set of devices.  This is done in part, by duplicating the vGPU and DirectPath devices from VM Class spec into the ConfigSpec.
Currently, we look at ConfigSpec /and/ the VM Class `spec.devices` field to determine what devices do we need to add to the VM.  This leads to the vGPU and DirectPath devices being added twice to the VM (since they are present in VM Class `spec.devices` field and are duplicated in ConfigSpec).
This change fixes this behavior by only looking at the ConfigSpec when the FSS is enabled.
Testing Done:

Only add PCI passthrough devices from ConfigSpec if FSS is enabled

---

controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
pkg/manager/manager.go

Unlike ConfigMaps and Secrets which we cannot cache because their quantity and size will exceed our container's memory limit, the pub req shouldn't be cached because of how the controller is implemented so make that explicit in the controller.

Use APIReader client to Get() VirtualMachinePublishRequest

---

api/v1alpha1/webconsolerequest_types.go
config/crd/bases/vmoperator.vmware.com_webconsolerequests.yaml
controllers/webconsolerequest/webconsolerequest_controller.go
controllers/webconsolerequest/webconsolerequest_intg_test.go
controllers/webconsolerequest/webconsolerequest_unit_test.go
docs/apis/v1alpha1.md

This patch adds a new field to the WebConsoleRequest CR to store the proxy address that can be used to access the VM's web-console. It updates the `webconsolerequest_controller` to retrieve the proxy address info from the defined proxy service object (`kube-system/kube-apiserver-lb-svc`).
Testing Done:
- Updated unit & integration tests to cover the newly added field in the CR
- Internal gce2e test succeeded to ensure not to introduce any regressions
- Manually applied the change to an internal testbed and verified the updated reconciliation result:
```
$ kubectl get svc -n kube-system kube-apiserver-lb-svc -o jsonpath='{.status.loadBalancer.ingress[*].ip}'
192.168.0.2%
$ kubectl get webconsolerequest -n sdiliyaer-test  -o jsonpath='{.items[*].status.proxyAddr}'
192.168.0.2%
```

Add proxy address in web console request

---

controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_intg_test.go
controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_unit_test.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_intg_test.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_unit_test.go
controllers/contentlibrary/utils/test_utils.go
pkg/util/cache.go
pkg/util/cache_test.go
pkg/util/lock_pool.go
pkg/util/lock_pool_test.go
pkg/vmprovider/fake/fake_vm_provider.go
pkg/vmprovider/interface.go
pkg/vmprovider/providers/vsphere/contentlibrary/content_library_provider.go
pkg/vmprovider/providers/vsphere/contentlibrary/content_library_utils.go
pkg/vmprovider/providers/vsphere/vmprovider.go
pkg/vmprovider/providers/vsphere/vmprovider_test.go
pkg/vmprovider/providers/vsphere/vsphere_suite_test.go

This patch introduces an in-memory cache to store and manage downloaded OVF for virtual machine images. It also cleans up stale cached items after a specified time (currently set to 30 minutes). This avoids unnecessary requests to vCenter when the same content library is associated with multiple namespaces within a cluster and speeds up vm image reconciliation time.
Testing Done:
- Internal kind-based e2e tests (both fast and full) passed
- Manually deployed this patch in a WCP testbed (with Image-Registry FSS enabled) and verified the expected workflow by associating a content library to multiple namespaces simultaneously. Logs from VM-Operator (in verbose mode):
```bash
I0207 09:15:21.266601       1 vmprovider.go:248] vsphere "msg"="Cache item miss, downloading OVF from vCenter" …
```

Implement caching for download of virtual machine images

---

pkg/vmprovider/providers/vsphere/network/network_provider.go
pkg/vmprovider/providers/vsphere/network/network_provider_test.go
pkg/vmprovider/providers/vsphere/network/network_suite_test.go
test/builder/vcsim_test_context.go

We'll eventually need the vcsim test context to be aware of networking in order to create VMs with the correct NICs in the ConfigSpec. Do the conversion now in preparation of fixing an immediate bug in the provider.

Convert network provider tests to vcsim test context

---

test/builder/test_suite.go

This saves a step - having to set KUBEBUILDER_ASSETS envar - when running an integration test suite on directly on the CLI or an IDE. Top level Makefile still sets KUBEBUILDER_ASSETS so that behavior is unchanged.

Set default envtest asset directory when not provided

---

controllers/virtualmachinesetresourcepolicy/virtualmachinesetresourcepolicy_controller_intg_test.go

There is a data race with the called var. Switch it to an atomic until we revise how we're testing the whole provider interface, and the interface itself.

 Fix race in VirtualMachineSetResourcePolicy integration test

---

controllers/controllers.go

This change stops watching TKG content source in the provider configmap and creating/updating/deleting related resources, such as ContentLibraryProvider and ContentSourceBindings when WCP_VM_Image_Registry FSS is enabled.
Test done:
- make test
- make test-integration
- manually deployed to a WCP cluster
- passed internal gce2e tests
- no TKG related ContentSource/ContentSourceBindings are created.

Stop creating TKG content source related resources.

---

pkg/vmprovider/providers/vsphere/network/network_provider.go
pkg/vmprovider/providers/vsphere/network/network_provider_test.go

A supported but very, very rare NSX-T configuration is for the same LogicalSwitchUUID to be shared between multiple DPVGs in a Datacenter. To support this, shortly before WCP 1.0 release, a change was made in WCP and then ported over here that used a "all the hosts in the CCR" check to determine which DVPG is the correct one to use. Ever since, this check in WCP and here have been peculiar and the details as to why mostly lost.
This is all host check strict in the sense that it will fail if a host is in MM or otherwise disconnected. Fortunately, within a CCR, the LogicalSwitchUUID to DVPG mapping is unique, so use that to simplify the lookup logic.
The possibility of multiple DVPGs for each CCR will be a pain when we start to do network placement.
Remove the NSX-T OpaqueNetwork support …

Fix NSX-T LogicalSwitchUUID to DVPG lookup

---

pkg/vmprovider/providers/vsphere/constants/constants.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

With UnifiedTKG FFS being enabled for some time now, this image check has been a noop but we still had tests for the non-FFS path: I recently hit an integration test race where the just created VM Image hadn't yet made it into the ctrl-runtime client cache. The validation webhooks should really just worry about internal object consistency, so here we only care that the imageName field isn't empty.
There is another problematic VM Image check in here w.r.t. the PVC volumes and OVA HW version that will addressed in a later MR.

Remove image supported VM validation check

---

webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

0e8d6c7 went through the pipelines prior to now stricter golangci-lint checks from ea31066.

Remove unused var from VM validation webhook

---

pkg/vmprovider/providers/vsphere/session/session_vm_update.go
pkg/vmprovider/providers/vsphere/virtualmachine/configspec.go
pkg/vmprovider/providers/vsphere/virtualmachine/configspec_test.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go

Due to a bug introduced by 44cd693, we are not dropping the PCI passthrough devices when the DaynDate FSS is disabled.  This change fixes that.
Closes #62

Account for GPU devices when the DaynDate FSS is disabled

---

controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_intg_test.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
pkg/context/virtualmachinepublishrequest_context.go
test/builder/util.go

This change adds finalizer to VirtualMachinePublishRequest, so that the DeleteMetrics is guaranteed to be called.
Test done:
- make test
- make test-integration
- manually deployed to a WCP cluster and verified:
```root@42158b2f7e39152b667d27bcedfd360f [ ~ ]# k describe vmpub vmpub-3 -n yijiang-ns
Name:         vmpub-3
Namespace:    yijiang-ns
Labels:       <none>
Annotations:  <none>
API Version:  vmoperator.vmware.com/v1alpha1
Kind:         VirtualMachinePublishRequest
Metadata:
Creation Timestamp:  2023-02-27T22:07:19Z
Finalizers:
virtualmachinepublishrequest.vmoperator.vmware.com
Generation:  1
...
Resource Version:  21655992
UID:               c9f637b0-4f4d-46ca-8d0f-cef4146cc568
Spec:
...
Ttl Seconds After Finished:  60
Status:
Attempts:  1
...
Events:             <none>
```
- the …

Add finalizer to VirtualMachinePublishRequest

---

config/local/vmoperator/local_env_var_patch.yaml
config/wcp/vmoperator/manager_env_var_patch.yaml
hack/deploy-wcp.sh
pkg/lib/env.go

This MR adds WCP_Namespaced_Class_And_Windows_Support FSS into VMOP. It will guard both VM Serive migration of VM Class to namespace scope work and Windows support work.
Testing:
- Vmop: https://buildweb.eng.vmware.com/sb/63377089/
- Csp: https://buildweb.eng.vmware.com/sb/63377286/
- dev-integ-vds: https://wcp.svc.eng.vmware.com/job/dev-integ-vds/3070/
```
root@42037808056efc7c1853467a8ae6218b [ ~ ]#  k describe deployment vmware-system-vmop-controller-manager -n vmware-system-vmop | grep "FSS_WCP_NAMESPACED_CLASS_AND_WINDOWS_SUPPORT"
FSS_WCP_NAMESPACED_CLASS_AND_WINDOWS_SUPPORT:  false
```

Add WCP_Namespaced_Class_And_Windows_Support FSS into VMOP

---

.github/workflows/pr-rtfd.yml

This patch adds support for building preview-ReadTheDoc sites on pull requests.
Validated with https://github.com/akutz/vm-operator/pull/7.

docs: Build RTFD preview for PRs

---

pkg/lib/env.go
pkg/vmprovider/providers/vsphere/network/network_provider.go
pkg/vmprovider/providers/vsphere/network/network_provider_test.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
webhooks/virtualmachine/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

This patch disallows the use of the named network provider in production deployments of VM Operator. While used for testing, the named network provider will be rejected unless the VM Operator ConfigMap is explicitly configured to support the named network provider.
This is an important fix as the current state of things violates the security model of Supervisor and Namespace-isolated resources.

sec: Disable Named Net Provider in Prod

---

controllers/volume/volume_controller.go
controllers/volume/volume_controller_suite_test.go
controllers/volume/volume_controller_unit_test.go
pkg/vmprovider/fake/fake_vm_provider.go
pkg/vmprovider/interface.go
pkg/vmprovider/providers/vsphere/vmprovider_vm.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

This change removes VM image hardware version check in VM validation webhook. After we enable WCP_VM_Image_Registry FSS, VMI name format has been changed. When PVC is added to an existing VM, which is created from the old format VMI, the validation webhook rejects the request since it fails to find the VMI and check the image hardware version.
To solve this issue, this change introduces a new condition PVCHardwareVersion in VM status. When the volume controller reconciles, it will first check if the HW version is supported when the PVC is sepcified in the VM spec.
Test done:
```
Deployed a VM with PVC:
root@421eb72411625ac28f829640dd47abe7 [ ~ ]# k describe vm ubuntu-volume -n yijiang-ns
...
Spec:
Class Name:  best-effort-small
Image Name:  vmi-8fae851a896a59a92
Network Interfaces: …
```

Remove VM image hardware version check in VM validation webhook.

---

config/wcp/vmoperator/namespace_patch.yaml

Starting version 1.25, Kubernetes will drop support for pod security policies.  This change modifies our codebase so we are using pod security admission admission.
- End to end tests on a testbed
- Deployed a testbed and verified that the namespace gets the correct labels

 PSP to PSA migration to support Kubernetes 1.25

---

controllers/providerconfigmap/provider_configmap_controller.go
controllers/providerconfigmap/provider_configmap_controller_unit_test.go
controllers/virtualmachineservice/virtualmachineservice_controller.go
controllers/virtualmachineservice/virtualmachineservice_controller_unit_test.go
controllers/volume/volume_controller.go
controllers/volume/volume_controller_unit_test.go
pkg/context/controller_manager_context.go
pkg/context/fake/fake_controller_manager_context.go
pkg/manager/manager.go
test/builder/unit_test_context.go

The controller-runtime Client added a Scheme() getter a while back so consistently use that for the Scheme so we don't have multiple ways to get the same thing.

Remove Scheme from ControllerManagerContext and Reconciler

---

api/v1alpha1/virtualmachine_types.go
docs/user-guide/deployvm.md
pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
pkg/vmprovider/providers/vsphere/session/session_vm_customization_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

This patch introduces support for a Sysprep transport for VMs, enabling the use of Windows images. An example, minimal Sysprep answers file is:
```xml
<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend">
<settings pass="oobeSystem">
<component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<OOBE>
<SkipMachineOOBE>true</SkipMachineOOBE>
<SkipUserOOBE>true</SkipUserOOBE>
</OOBE>
</component>
</settings>
</unattend>
```
This could be created as a Secret resource with:
```yaml
apiVersion: v1
kind: Secret
metadata:
name: my-vm-bootstrap-data …
```

Support for Sysprep / Windows images

---

controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_intg_test.go

The patch helper updates the Conditions first and separately from the rest of the Status, so that leaves a window where the Complete condition is set but the Status.Ready is still false.

Fix VirtualMachinePublishRequest controller test race

---

.github/configs/labeler.yml
.github/workflows/testing-needed.yml

This patch updates the testing-needed workflow to address a race condition (see #73) by applying and checking related labels in a single workflow, without using an additional GitHub token as previously proposed in PR #75.
Testing Done:
- Pushed this change into a fork's main: https://github.com/dilyar85/vm-operator/
- Created a PR from another fork (https://github.com/test-vmop/vm-operator) to the above repo: https://github.com/dilyar85/vm-operator/pull/23
- Manually remove the "testing-needed-e2e-fast" label from the PR
- Added a "testing-done-e2e-fast" label to the PR
- Updated the PR with a smaller LoC
Screenshot:

Update testing-needed workflow to prevent label race

---

controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_intg_test.go

We were using Update in VMPublishRequest integration tests to force trigger a reconcile. This may cause race since vmPub controller is also trying to update the resource. This change uses Patch instead of Update to fix such race.

Fix VirtualMachinePublishRequest integration test race.

---

api/v1alpha1/condition_consts.go
config/rbac/role.yaml
controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_intg_test.go
controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_unit_test.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_intg_test.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_unit_test.go
controllers/contentlibrary/utils/constants.go
controllers/contentlibrary/utils/test_utils.go
controllers/contentlibrary/utils/utils.go
pkg/context/clustercontentlibraryitem_context.go
pkg/context/contentlibraryitem_context.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go

This patch updates the cl-item & ccl-item controllers by adding/removing a finalizer during their reconciliation process. This ensures that when these resources are deleted from a K8s cluster, the corresponding image metrics are also deleted by calling our ReconcileDelete function. Two `contentlibraryitem_context` and `clustercontentlibraryitem_context` files are added to streamline the reconciling function params in both controllers.
Additionally, the security compliance check of item resources is also updated to avoid deleting the image resources. Instead, a new condition is introduced and added to images, which is verified during the VM deployment process (in the `vmprovider_vm_utils.go` file).
Testing: 
```console
$ kubectl get cclitem clitem-d71052e4b82561b37 -o …
```

Add finalizer for vmi and cvmi resources

---

controllers/virtualmachine/virtualmachine_controller.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go

When WCP_Namespaced_Class_And_Windows_Support is enabled, VM Class will be namespace scoped. This change removes VirtualMachineClassBinding logic from VM Operator repo.
Test done:

Remove VirtualMachineClassBinding logic

---

api/v1alpha1/conversion_test.go
api/v1alpha1/virtualmachineimage_conversion.go
api/v1alpha1/zz_generated.conversion.go
api/v1alpha2/virtualmachineimage_types.go

Add ProviderContentVersion to the image Status that's used to track last synced Content Library item version. This is used to avoid repeated CL item fetch tasks.
Add Condition type and reasons

Sync v1a1 VirtualMachineImage changes to v1a2

---

controllers/virtualmachineservice/virtualmachineservice_controller.go
controllers/virtualmachineservice/virtualmachineservice_controller_intg_test.go
controllers/virtualmachineservice/virtualmachineservice_controller_unit_test.go

Previously a selectorless VirtualMachineService would end up selecting every VM in the namespace, which is not the expected behavior.
Improve the VM EnqueueRequestsFromMapFunc handler by not repeating listing all the VMs that match each service. Instead, list the services once and see if the changed VM would have matched.

Fix VirtualMachineService selectorless behavior

---

pkg/vmprovider/providers/vsphere/vmprovider_vm.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go

This change to use VM Class spec for resource reservation and limits before computing min frequency was done earlier for the update path but missed out for create.
Adding some cpu/mem reservation tests to validate the same.

Fix up computeCPUMinFrequency for the createVM path and add some CPU/Mem Reservation tests

---

api/v1alpha1/virtualmachine_types.go
api/v1alpha1/virtualmachinetempl_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
docs/concepts/workloads/guest.md
docs/concepts/workloads/vm.md
docs/ref/proj/docs.md
docs/start/quick.md
mkdocs.yml
pkg/vmprovider/providers/vsphere/constants/constants.go
pkg/vmprovider/providers/vsphere/network/network_provider.go
pkg/vmprovider/providers/vsphere/session/session_suite_test.go
pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
pkg/vmprovider/providers/vsphere/session/session_vm_customization_test.go

This PR adds a new `V1alpha1_FirstNicMacAddr` template query required for Sysprep network customization.
It also updates the Guest Customization doc with more examples provided for Sysprep and vAppCofnig (closes #107). A new `jinja_options` is added to indicate variables, allowing the presentation of the template strings in markdown.
Testing:
- Windows 11
- Windows Server 2022
- Ubuntu & CentOS (with CloudInit) 
Sysprep unattend data used for Windows VM:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend">
<settings pass="specialize">
<component name="Microsoft-Windows-TCPIP" processorArchitecture="amd64"
publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS"
xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State" …
```

Update template to support Sysprep guest customization

---

api/v1alpha2/virtualmachine_bootstrap_types.go
api/v1alpha2/virtualmachine_network_types.go
api/v1alpha2/virtualmachine_readiness_types.go
api/v1alpha2/virtualmachine_types.go

Update shorten CloudInit docs link to chase new docs URL
Update VM IP printcolumn path to new IP4 field since we do not have just one "primary" IP field anymore
Remove Severity from Conditions comment since metav1.Conditions do not have that field
Add various description boilerplate

Initial pass at v1a2 VirtualMachine CRD doc updates

---

api/v1alpha2/sysprep/sysprep.go
api/v1alpha2/virtualmachine_network_types.go

This PR addresses the missing comments for v1alpha2 Sysprep fields based on the [CustomizationSysprep](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/da47f910-60ac-438b-8b9b-6122f4d14524/16b7274a-bf8b-4b4c-a05e-746f2aa93c8c/doc/vim.vm.customization.Sysprep.html) API. Additionally, this PR includes a clarification regarding the `sysprep.RawSysprep` field, explicitly stating that it is not applicable to certain `VirtualMachineNetworkInterfaceSpec` (all settings will be applied from the sysprep.xml answer file in that case). 
N/A
**Are there any special notes for your …

📖 Update v1alpha2 Sysprep API related comments

---

pkg/vmprovider/fake/fake_vm_provider.go
pkg/vmprovider/providers/vsphere/constants/constants.go

This patch updates the minimum hardware version requirement for persistent volumes
n/a
n/a
```release-note
Updates the minimum hardware version for persistent volumes
```

🌱 Updates the minimum hardware version for persistent volumes

---

config/local/vmoperator/local_env_var_patch.yaml
config/wcp/vmoperator/manager_env_var_patch.yaml
controllers/virtualmachine/virtualmachine_controller.go
pkg/lib/env.go
pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

This PR refactors the WCP_Namespaced_Class_And_Windows_Support into two separate FSS, so that they can be enabled individually.
N/A
Deployed an internal testbed with the corresponding builds and verified that the updated FSS env vars were passed down properly:
```console
$ kubectl get deploy -n vmware-system-vmop -o yaml | grep FSS_WCP -C 2
...
- name: FSS_WCP_NAMESPACED_VM_CLASS
value: "false"
- name: FSS_WCP_WINDOWS_SYSPREP
value: "false"
```

🌱 Separate WCP_Namespaced_Class_And_Windows_Support into two FSS

---

pkg/vmprovider/providers/vsphere/constants/constants.go

Attaching PCI passhtru devices to VMs requires a minimum hardware version of 17.
Fixes #158 
None.
```release-note
Introduces new constant for PCI passthru vmx version
```

🌱 Introduces new constant for PCI passthru vmx version

---

pkg/util/devices.go
pkg/util/devices_test.go
pkg/vmprovider/providers/vsphere/session/session_vm_create.go
pkg/vmprovider/providers/vsphere/vmprovider_vm.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go

Set a minimum hardware version for VMs created with PVC/PCI devices when no hardware version is specified in the VM Class
- PVCs == vmx-15
- PVCs and/or PCI (vGPU/DDPIO) devices == vmx-17
- If the VM Image has a higher version than the minimum mentioned above, the image version takes precedence
This makes sure that going forward brownfield VMs/workloads with PVCs/PCI devices still have a supported hardware version specified when the VM Class doesn't mention one.
Fixes #
NA
None
```
Set minimum hardware version for VMs created with Persistent Volume Claims or PCI devices (eg Nvidia GPUs) when
the VM Class doesn't mention a hardware version
``` …

 🐛 Set Hardware versions for VMs created with PVC/PCI devices

---

api/v1alpha1/virtualmachineclass_types.go
api/v1alpha1/zz_generated.conversion.go
api/v1alpha2/virtualmachineclass_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml
controllers/virtualmachine/virtualmachine_controller.go
docs/concepts/workloads/vm-class.md
pkg/lib/env.go
pkg/util/kube/kube_suite_test.go
pkg/util/kube/predicates.go
pkg/util/kube/predicates_test.go
webhooks/virtualmachineclass/mutation/virtualmachineclass_mutator.go
webhooks/virtualmachineclass/mutation/virtualmachineclass_mutator_unit_test.go

This patch adds support for specifying the field `spec.controllerName` in a `VirtualMachineClass` resource. If this field is set to `vmoperator.vmware.com/vsphere`, then the VM Operator controller for `VirtualMachine` reconciles all VM resources. If the field is empty, then the environment variable `DEFAULT_VM_CLASS_CONTROLLER_NAME` is used to determine the default controller name. If this environment variable is empty, it defaults to `vmoperator.vmware.com/vsphere`. Otherwise the controller responsible for reconciling VM resources is determined by the field `spec.controllerName` in the VM Class referenced by a VM.
**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …

✨ Support ControllerName for VM Class

---

pkg/util/configspec.go
pkg/util/configspec_test.go
pkg/util/devices.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go

When VMClassAsConfig is enabled, this change removes only disks that are not raw device mapping backed. All disk controllers can be added post this FSS.
Testing:
make test
N/A
Fixes #
N/A
N/A
```
Remove only virtual disks without RDM backings from the VM Class when VMClassAsConfig FSS is enabled 
```

🌱 Only sanitize virtual disks that are non-RDM from class config spec

---

controllers/virtualmachine/virtualmachine_controller.go
controllers/virtualmachine/virtualmachine_controller_unit_test.go

This PR filters VMClass events when it comes to VM reconciliation with Namespaced VMClass FSS enabled. Now only Create and Delete events on namespaced VMClass will trigger reconcile in VM controller
Fixes NA
```release-note
Only watch Create and Delete events for namespaced VMClass when reconcile VM
```

:seedling: Only watch Create and Delete events for VMClass when reconcile VM

---

api/v1alpha1/condition_consts.go
api/v1alpha2/virtualmachine_types.go
go.mod
go.sum
pkg/vmprovider/providers/vsphere/constants/constants.go
pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
pkg/vmprovider/providers/vsphere/session/session_vm_customization_test.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go

Adds a new condition to the `VirtualMachine` CR to expose the state of the metadata+userdata.
Fixes #148 
```release-note
Adds new condition to VirtualMachine to the expose state of metadata+userdata
```

✨ Adds new condition to VirtualMachine to the expose state of metadata+userdata

---

api/v1alpha1/condition_consts.go
api/v1alpha2/virtualmachine_types.go
go.mod
go.sum
pkg/vmprovider/providers/vsphere/constants/constants.go
pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
pkg/vmprovider/providers/vsphere/session/session_vm_customization_test.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go

This reverts commit ce7874b99dc60a7394fb15e23923a1970bb8aa18.
Due to gce2e failed on `panic: interface conversion: error is *session.ErrWithReason, not session.ErrWithReason`. I am reverting this commit which introduced `session.ErrWithReason` for now.

Revert "Adds new condition to expose state of guestinfo"

---

docs/concepts/workloads/guest.md
docs/tutorials/deploy-vm/vappconfig.md

Add doc for vAppConfig bootstrap. 
Fixes #123
----
:books: Documentation preview :books:: https://vm-operator--175.org.readthedocs.build/en/175/

:book: Add vappconfig.md doc

---

controllers/virtualmachineservice/virtualmachineservice_controller.go
controllers/virtualmachineservice/virtualmachineservice_controller_unit_test.go

For VirtualMachineServices we create a selectorless Service and manage
the Endpoints to point to the underlying VirtualMachines so NodePorts are
not required because we don't proxy via the Supervisor CP VMs. Set field
added in k8s 1.24 to disable allocating NodePorts. Make this automatic
for LB-type services. This field is ignored/reset for non-LB type Services.
This addresses a scaling issue where we can exhaust the WCP SV cluster
out of NodePorts, usually via many TKG Services..

Do not allocate NodePorts for VirtualMachineService Services

---

api/v1alpha1/conversion_test.go
api/v1alpha1/virtualmachine_conversion.go
api/v1alpha1/virtualmachine_types.go
api/v1alpha2/virtualmachine_types.go

- Add more creation step Conditions
- Use Condition to infer "Created" phase for v1a1 down conversion since CAPI uses that value to determine if the VM is ready
- Implement condition Get/Set methods for later v1a2 conditions support

Update v1a2 VirtualMachine types

---

docs/tutorials/deploy-vm/README.md
docs/tutorials/deploy-vm/cloudinit.md

This change moves around information between docs that speaks of various ways to Deploy a VM using VM operator and moves the Cloud-init bootstrapping section to its own file.
Fixes #122, #121
----
:books: Documentation preview :books:: https://vm-operator--183.org.readthedocs.build/en/183/

📖 Consolidate content in the Cloud-Init and Deploy VM docs

---

docs/concepts/workloads/guest.md

This PR adds a callout to the Sysprep section in the [Guest Customization](https://vm-operator.readthedocs.io/en/latest/concepts/workloads/guest/) doc. This is to highlight the guest OS customization failure from deploying Windows images with an incomplete Sysprep state. The issue is described in detail in [KB 86350](https://kb.vmware.com/s/article/86350), which is also linked in the callout section.
Fixes #185 
NONE
----
:books: Documentation preview :books:: https://vm-operator--186.org.readthedocs.build/en/186/

📖 Add callout to address incomplete Sysprep state issue

---

Makefile

Without this the presence of an existing binary file, regardless of age w.r.t the rest of the project, won't result in a recompile. This can cause confusion around a using stale binary or whether the current state of the project actually compiles.

Add relative binary path to -only .PHONY targets

---

pkg/util/devices.go
pkg/util/devices_test.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go

This makes the method SelectVGPU more explicit since vGPUs can have DVX backings as well.
This makes the method more explicit since vGPUs can have VMIOP and DVX backing.
Fixes #162

🌱 Rename SelectVGPU taking BackingType into account

---

api/utilconversion/conversion.go
api/utilconversion/conversion_fuzz.go
api/v1alpha1/conversion_test.go
api/v1alpha1/virtualmachineclass_conversion.go

This patch extends the conversion function for the VirtualMachineClass API type to ensure lossless conversion of the new fields in the Status of the v1alpha2 version of the CR.
When down-converting to v1alpha1 version, the extra fields get added to the CR's annotation and this data can be read during up-conversion to v1alpha2 version.
The v1alpha2 version of the `VirtualMachineClass` CR has new fields introduced in the `VirtualMachineClassStatus` type, namely `Ready`, `Conditions` and `Capabilities` which are not present in the v1alpha1 version. When down-converting a v1alpha2 API version, say, via the v1alpha1 versioned client, a straight up conversion will cause these new fields to be …

:sparkles: Ensure lossless conversion of VirtualMachineClass new fields

---

config/wcp/vmoperator/cpu_resources_patch.yaml

The is the quickest change to alleviate the OOM we're seeing in large scale test envs.
Longer term work of setting GOMEMLIMIT, using more metadata only watches, disabling the ctrl-runtime Client for more types, and reworking some types to not store large dumps of data in the annotations so MD-only watches are more effective is needed.
```release-note
NONE
```

🐛 Bump manager container memory limit

---

controllers/infracluster/infracluster_controller.go
controllers/infraprovider/infraprovider_controller.go
pkg/context/controller_manager_context.go

There is nothing inherently v1a2 about these controllers, but the way we have the fat VMProvider interface makes them so. We've wanted to and should get away from our current not Go'ish interface but that is out of scope for my current work. So just for these controllers, define the interface they need and pick the appropriate provider based on the FSS
```release-note
NONE
```

✨ Make infra related controllers v1a2 aware

---

Makefile
config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineservices.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml
config/webhook/manifests.yaml
webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachineclass/v1alpha2/validation/virtualmachineclass_validator.go
webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator.go
webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator.go
webhooks/virtualmachinesetresourcepolicy/v1alpha2/validation/virtualmachinesetresourcepolicy_validator.go

This change generates the v1alpha2 CRD and webhook manifests.
Fixes # N/A
CSP (a consumer of the wcp deployment manifests) has code to strip out v1a2 manifests based on the V1A2 FSS value. 
```
Generate v1alpha2 custom resource definition and webhook manifests
```

✨Generate v1a2 CRD and webhooks manifests

---

.github/PULL_REQUEST_TEMPLATE.md
docs/concepts/workloads/guest.md
docs/tutorials/deploy-vm/README.md
docs/tutorials/troubleshooting/README.md
docs/tutorials/troubleshooting/deploy-vm.md
docs/tutorials/troubleshooting/ip-assignment.md
docs/tutorials/troubleshooting/publish-vm.md
mkdocs.yml

Add readme page for https://vm-operator.readthedocs.io/en/stable/tutorials/troubleshooting/ and how to troubleshoot failure on vm deployment. This change also created place holders for troubleshooting VM failed to get a valid IP Address page and troubleshooting VM publish failure.
Fixes #124 
```release-note
NONE
```
----
:books: Documentation preview :books:: https://vm-operator--201.org.readthedocs.build/en/201/

📖 Add troubleshooting readme and troubleshooting deploy vm

---

pkg/vmprovider/providers/vsphere/session/session_vm_customization.go

VM operator can accept Golang template strings in bootstrap user-data and perform any substitutions before passing it down to the guest. However, as of today, the only bootstrap method that supports templating is vAppConfig and Sysprep. This change enforce template rendering to only  vAppConfig and Sysprep transport.
Fixes #146 
Testing done: gce2e vmservice test passed with this change.
```release-note
Limit template rendering to only vAppConfig and Sysprep transport
```

:seedling: Limit template rendering to only vAppConfig and Sysprep transport

---

controllers/volume/v1alpha1/volume_controller.go
controllers/volume/v1alpha1/volume_controller_unit_test.go
controllers/volume/v1alpha2/volume_controller.go
controllers/volume/v1alpha2/volume_controller_unit_test.go

If a CnsNodeVmAttachment already exists when we were expecting to create it, inspect the existing one to see if we're the owners of it but it is otherwise stale. The usual cause of this will be that VC VM was deleted from underneath, and the replacement VM will end up with a new BiosUUID.
This addresses the immediate issue we have, but still leaves some lingering issues around the whole attachment workflow, like w.r.t. volume and PVC name changes, and how we determine if the volume is actually attached, that we'll have to keep throwing code at until we're able to revisit this workflow, and likely bring the attachment and detachment in-house.
```release-note
NONE
```

 🐛  Better handle when CnsNodeVmAttachment unexpectedly already exists

---

hack/deploy-local.sh

This PR removes the v1a2 CRDs and webhooks based on the v1alpha2 FSS value when deploy-local.sh is used. 
Fixes #
N/A
Ran gce2e-build to verify things are working fine
```
Add v1alpha2 FSS related logic to hack/deploy-local.sh 
```

🌱 Remove v1a2 CRDs and webhooks on local kind environments based on v1alpha2 FSS 

---

controllers/virtualmachine/v1alpha1/virtualmachine_controller.go
controllers/virtualmachine/v1alpha2/virtualmachine_controller.go

This ensures that the controllerName filter is applied to the incoming VirtualMachine objects only instead of all the watched objects by the controller.
This PR replaces #170 
```release-note
🐛 Adds event filter to incoming VirtualMachine objects only
```

🐛 Adds event filter to incoming VirtualMachine objects only

---

controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller_suite_test.go
controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller_intg_test.go
controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller_suite_test.go
controllers/virtualmachine/v1alpha2/virtualmachine_controller_suite_test.go
controllers/virtualmachineclass/v1alpha2/virtualmachineclass_controller_suite_test.go
controllers/virtualmachinepublishrequest/v1alpha2/virtualmachinepublishrequest_controller_suite_test.go
controllers/virtualmachineservice/v1alpha2/virtualmachineservice_controller_suite_test.go
controllers/virtualmachinesetresourcepolicy/v1alpha2/virtualmachinesetresourcepolicy_controller_suite_test.go
controllers/volume/v1alpha2/volume_controller_suite_test.go
pkg/manager/manager.go
test/builder/test_suite.go
test/builder/util.go
webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_suite_test.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_suite_test.go
webhooks/virtualmachineclass/v1alpha2/mutation/virtualmachineclass_mutator_suite_test.go
webhooks/virtualmachineclass/v1alpha2/validation/virtualmachineclass_validator_suite_test.go
webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator_suite_test.go
webhooks/virtualmachineservice/v1alpha2/mutation/virtualmachineservice_mutator_suite_test.go
webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator_suite_test.go
webhooks/virtualmachinesetresourcepolicy/v1alpha2/validation/virtualmachinesetresourcepolicy_validator_suite_test.go

- This change enables controller and webhook integration tests for v1alpha2.
- The testsuite works with the v1A2 FSS to create the right CRD storage versions prior to the integration tests. This way, the right v1a1 and v1a2 CRDs are installed with the right storage versions when v1a1/v1a2 controller/webhook integration tests are run.
Fixes # 
N/A
N/A
N/A

✨Enable v1a2 controller and webhook integration tests

---

api/v1alpha2/virtualmachinewebconsolerequest_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinewebconsolerequests.yaml

- This change adds the spec.PublicKey and status.Response fields to the v1a2 VirtualMachineWebConsoleRequest CRD similar the v1a1 CRD. These are still required 
Fixes #
N/A
N/A

✨Add PublicKey and Response fields to v1a2 VirtualMachineWebConsoleRequest CRD

---

config/rbac/role.yaml
controllers/virtualmachinewebconsolerequest/controllers.go
controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_controller.go
controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_intg_test.go
controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_suite_test.go
controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_unit_test.go
pkg/context/webconsolerequest_context.go

This change adds the v1a2 virtualmachinewebconsolerequest controllers and tests. The controller is guarded by the Feature state switch. The webhook changes will be a follow-up of this PR.
Fixes # N/A
N/A
```
Add v1a2 virtualmachinewebconsolerequest controllers and tests
```

✨ Add v1a2 webconsole request controllers

---

api/v1alpha1/virtualmachine_types.go
api/v1alpha2/virtualmachine_types.go
pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go
webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_unit_test.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go

This change fixes the bug when using CloudInit transport to bootstrap a VM, not passing user data actually results VM customized with GOSC (LinuxPrep). This patch introduced an annotation to set Cloudinit metadata instance-id and also introduced a webhook to prevent SSO users from setting the annotation manually.
Fixes N/A
Testing done: 
1. gce2e vmservice passed.
2. Greenfield: Manually deployed a VM using Cloud-init sans userdata. `guestinfo.metadata` got set successfully.
3. SSO User setting annotation is forbidden …

:bug: fix bug when using CloudInit without userdata to bootstrap VM

---

controllers/virtualmachine/v1alpha1/virtualmachine_controller.go
controllers/virtualmachine/v1alpha1/virtualmachine_controller_unit_test.go
controllers/virtualmachine/v1alpha2/virtualmachine_controller.go
controllers/virtualmachine/v1alpha2/virtualmachine_controller_unit_test.go
pkg/lib/env.go
pkg/util/enc.go
pkg/util/enc_test.go
pkg/vmprovider/fake/fake_vm_provider.go
pkg/vmprovider/fake/fake_vm_provider_a2.go
pkg/vmprovider/interface.go
pkg/vmprovider/interface_a2.go
pkg/vmprovider/providers/vsphere/constants/constants.go
pkg/vmprovider/providers/vsphere/session/session_util.go
pkg/vmprovider/providers/vsphere/session/session_util_test.go
pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
pkg/vmprovider/providers/vsphere/session/session_vm_customization_test.go
pkg/vmprovider/providers/vsphere/virtualmachine/backup.go
pkg/vmprovider/providers/vsphere/virtualmachine/backup_test.go
pkg/vmprovider/providers/vsphere/virtualmachine/virtualmachine_suite_test.go
pkg/vmprovider/providers/vsphere/vmprovider_vm.go

This PR updates the VirtualMachine Controller to store the VM's Kubernetes and bootstrap data YAML (compressed using gzip and base64-encoded) into the VM's ExtraConfig, if the corresponding FSS is enabled. This enables the VM to be restored by recreating the YAML from this backup data.
The v1a2 VM Controller code has been updated with the new `BackupVirtualMachine()` function. However, the implementation of that function has not been added because the v1a2 VM provider code does not exist yet.
```release-note
Persist VM's Kubernetes and bootstrap data in ExtraConfig
```
**Testing Done**
- Added test code in both VM controller and provider.
- …

✨ Persist VM's kubernetes and bootstrap data in ExtraConfig

---

go.mod
go.sum

This patch updates the GoVmomi dependency to 8.0U1c, which also includes code comments for all GoVmomi types. Please see https://github.com/vmware/govmomi/pull/3232 for more information.
Fixes `NA`
`NA`
```release-note
Updates vSphere API dependencies to 8.0U1c.
```

:sparkles: Update GoVmomi to 8.0U1c

---

config/rbac/role.yaml
controllers/contentlibrary/v1alpha1/utils/utils.go
pkg/lib/env.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go
webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator_intg_test.go
webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator_unit_test.go

This PR updates the VirtualMachine mutation webhook to replace the `vm.spec.imageName` if it's a friendly image name that matches a **single** namespace or cluster scope image. If multiple images are found, the mutator denies the VM creation request. The mutator also indexes the VirtualMachineImage and ClusterVirtualMachineImage objects by their `.status.imageName` fields to enable efficient querying.
Fixes #214
This patch formats the `controllers/contentlibrary/v1alpha1/utils/utils.go` file to not exceed 80 characters. It also replaces the FSS mock calls with `os.Setenv/Unsetenv` in the test code. …

✨ Support VM deployment from image status (friendly) name

---

.github/workflows/testing-needed.yml

This patch updates the check-label job to not fail the PR if it contains a `testing-done-e2e-full` label. This is to address the case where a PR may require `testing-needed-e2e-fast`, but developers have conducted a full e2e validation and attached the `testing-done-e2e-full` label.
N/A.
Some comments are rewritten in this file to comply with the 80-character format requirement.
```release-note
Update testing-needed job to not fail when testing-done-e2e-full label presents
```
**Testing Done**
- Manually merged this change to an upstream repo and created a PR that validated all the following cases:
- …

🐛 Do not fail PR when the testing-done-e2e-full label presents

---

docs/tutorials/troubleshooting/ip-assignment.md

Add troubleshooting doc for ip assignment issue.
Fixes #193 
```release-note
Add troubleshooting doc for ip assignment issue
```
----
:books: Documentation preview :books:: https://vm-operator--220.org.readthedocs.build/en/220/

:book: Add troubleshooting page for ip assignment issue

---

.github/workflows/ci.yml
Dockerfile
go.mod
main.go
pkg/util/enc_test.go
test/builder/util.go

`controller-runtime` v15 has a min Golang version requirement that breaks the container builds.  This change bumps up the Go version used to build the container.  Starting 1.21 Golang, go.mod requires the Go version and treats that as min required go version to compile your binary.  So, also bump up the Go version for local builds.
**Which issue(s) is/are addressed by this PR?** 
N/A
N/A
```release-note
NONE
```

:seedling: Bump up min go version to 1.20

---

config/crd/kustomization.yaml
config/webhook/manifests.yaml
webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator_suite_test.go
webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_suite_test.go
webhooks/virtualmachineclass/v1alpha1/mutation/virtualmachineclass_mutator.go
webhooks/virtualmachineclass/v1alpha1/mutation/virtualmachineclass_mutator_suite_test.go
webhooks/virtualmachineclass/v1alpha1/validation/virtualmachineclass_validator.go
webhooks/virtualmachineclass/v1alpha1/validation/virtualmachineclass_validator_suite_test.go
webhooks/virtualmachinepublishrequest/v1alpha1/validation/virtualmachinepublishrequest_validator.go
webhooks/virtualmachinepublishrequest/v1alpha1/validation/virtualmachinepublishrequest_validator_suite_test.go
webhooks/virtualmachineservice/v1alpha1/mutation/virtualmachineservice_mutator.go
webhooks/virtualmachineservice/v1alpha1/mutation/virtualmachineservice_mutator_suite_test.go
webhooks/virtualmachineservice/v1alpha1/validation/virtualmachineservice_validator.go
webhooks/virtualmachineservice/v1alpha1/validation/virtualmachineservice_validator_suite_test.go
webhooks/virtualmachinesetresourcepolicy/v1alpha1/mutation/virtualmachinesetresourcepolicy_mutator.go
webhooks/virtualmachinesetresourcepolicy/v1alpha1/mutation/virtualmachinesetresourcepolicy_mutator_suite_test.go
webhooks/virtualmachinesetresourcepolicy/v1alpha1/validation/virtualmachinesetresourcepolicy_validator.go
webhooks/virtualmachinesetresourcepolicy/v1alpha1/validation/virtualmachinesetresourcepolicy_validator_suite_test.go
webhooks/virtualmachinewebconsolerequest/v1alpha1/validation/webconsolerequest_validator.go
webhooks/virtualmachinewebconsolerequest/v1alpha1/validation/webconsolerequest_validator_suite_test.go

This change
- includes the controller-runtime conversion webhook patches for v1a2 CRs and
- updates the v1a1 webhook names to include v1alpha1
Fixes # N/A
N/A
```
Include the controller-runtime conversion webhook patches for v1alpha2
```

✨ Include the controller-runtime conversion webhook patches for v1a2 and update v1a1 webhook names

---

go.mod
go.sum

This patch updates the GoVmomi dependency to 8.0U2.
Fixes `NA`
`NA`
```release-note
Updates vSphere API dependencies to 8.0U2.
```

:sparkles: Update GoVmomi to 8.0U2

---

api/v1alpha1/virtualmachineimage_types.go
config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml

This patch removes the printer columns related to Content Library from the v1a1 VirtualMachineImage and ClusterVirtualMachineImage resources. This is aligned with v1a2, and frankly, these fields provide no real value when printing VMIs and just clutter the output. A user should not care where the image originates, and if they do, they can look at the image's status for more info.
Fixes `NA`
`NA`
```release-note
Removes the Content Provider and Library Item Name printer columns …
```

✨ Remove content library fields from VirtualMachineImage printer columns

---

docs/concepts/images/vm-image.md
docs/requirements.txt
docs/www/themes/material/main.html
mkdocs.yml

This patch updates the version of mkdocs, its theme, and dependencies used to build the documentation. This patch also adds documentation about VM image names/resolution and creates a dismissable banner to ensure users see that image name logic has changed in vSphere 8.0U1+.
Fixes `NA`
`NA`
```release-note
Document VM image names and image resolution.
```
----
:books: Documentation preview :books:: https://vm-operator--233.org.readthedocs.build/en/233/

:sparkles: Markdown updates / VM image documentation

---

controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_controller.go
controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_intg_test.go
controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_suite_test.go
controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_unit_test.go

When v1a2 FSS gets enabled, only the v1a2 VM Provider will be available for use. 
Since v1a1 webconsole CRs are still supported in v1a2 world, the v1a1 VM Provider that it uses will NPE.
This requires the v1a1 controller to be v1a2 Provider aware.
Fixes #
N/A
N/A
```
None
```

✨ Make v1a1 webconsole controller v1a2 VMProvider aware

---

pkg/vmprovider/providers/vsphere/constants/constants.go
pkg/vmprovider/providers/vsphere/virtualmachine/backup.go
pkg/vmprovider/providers/vsphere/virtualmachine/backup_test.go

This PR persists a VM's disk path and type (determined by the existence of `VDiskID`) in ExtraConfig. This is required to register any disks as FCDs and expose them as PVCs during a restore operation.
N/A
Currently, the `vm.Reconfigure()` task will not be called because the corresponding FSS is not enabled. A follow-up patch will be submitted to optimize that VC call during VM reconciliation.
```release-note
Persist VM disk path and type info in ExtraConfig.
```
**Testing Done**:
- Added unit tests to cover the disk info check in vcSim VM's ExtraConfig
- Manually deployed this change to a WCP testbed …

✨ Persist VM disk path and type info in ExtraConfig

---

api/v1alpha1/virtualmachine_types.go
api/v1alpha2/virtualmachine_types.go
pkg/vmprovider/providers/vsphere/session/session_vm_update.go
pkg/vmprovider/providers/vsphere/vmprovider_vm.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_unit_test.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go

This patch updates the VM mutation webhook to disallow non-admin users from adding/updating/removing the `first-boot-done` annotation. It is only meant to be modified by the VM-Operator. Also, it fixes the current implementation which could cause all VM updates from non-admin users to fail if the `cloud-init-instance-id` annotations exist.
Fixes #221 
This change is a prerequisite for another upcoming change that will rely on the existence of the `first-boot-done` annotation set by the VM-Operator.
```release-note
Prevent non-admin users from setting first-boot-done annotation
```

🌱 Prevent non-admin users from setting first-boot-done annotation

---

api/v1alpha2/common/types.go
api/v1alpha2/sysprep/sysprep.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml

🐛 Fix a few typos in the v1a2 bootstrap types

---

pkg/vmprovider/providers/vsphere/contentlibrary/content_library_provider.go
pkg/vmprovider/providers/vsphere/contentlibrary/content_library_test.go
pkg/vmprovider/providers/vsphere2/contentlibrary/content_library_provider.go
pkg/vmprovider/providers/vsphere2/contentlibrary/content_library_test.go

With image service enabled, we now reconcile individual Content Library Items. So we don't want to skip error handling anymore. This change will allow retrying when encountered errors during `RetrieveOvfEnvelopeFromLibraryItem`.
Fixes N/A
```release-note
Return errors to trigger reconcilation when retrieve Ovf envelope from library item
```

:bug: Return err during unmarshaling ovf file to trigger reconcile

---

webhooks/common/response.go
webhooks/common/response_test.go
webhooks/persistentvolumeclaim/validation/persistentvolumeclaim_validator.go
webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_unit_test.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachineclass/v1alpha1/validation/virtualmachineclass_validator.go
webhooks/virtualmachineclass/v1alpha2/validation/virtualmachineclass_validator.go
webhooks/virtualmachinepublishrequest/v1alpha1/validation/virtualmachinepublishrequest_validator.go
webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator.go
webhooks/virtualmachineservice/v1alpha1/validation/virtualmachineservice_validator.go
webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator.go
webhooks/virtualmachinesetresourcepolicy/v1alpha1/validation/virtualmachinesetresourcepolicy_validator.go
webhooks/virtualmachinesetresourcepolicy/v1alpha2/validation/virtualmachinesetresourcepolicy_validator.go
webhooks/virtualmachinewebconsolerequest/v1alpha1/validation/webconsolerequest_validator.go

This change emits a warning when a user specifies OvfEnv transport in a VM's spec.  In order to support warnings, modify the BuildValidationResponse so it can now take warnings from any validations.
At some point, we should move our webhooks to controller-runtime generated webhooks which will remove the need to synthesize the response from errors and warnings ourselves.
None
```release-note
Emit a webhook warning when OvfEnv or ExtraConfig transport is specified
```

:seedling: Emit a webhook warning when OvfEnv or ExtraConfig transport is specified

---

pkg/vmprovider/providers/vsphere/virtualmachine/configspec.go
pkg/vmprovider/providers/vsphere/virtualmachine/configspec_test.go
pkg/vmprovider/providers/vsphere2/virtualmachine/configspec.go
pkg/vmprovider/providers/vsphere2/virtualmachine/configspec_test.go

This change reverses of the order of precedence to populate the configSpec from the image first then the class. This is necessary since the vSphere UI is currently unable to create VM Classes with an empty firmware type and always defaults to 'efi', creating scenarios for VM boot failures when the image does not support the firmware. 
This reversal can be changed back once vSphere GUI supports creating VM Classes with an optional/empty firmware type as default for a user.
Fixes #
N/A
N/A
**Please add a release note if …

🌱 Reverse configSpec.firmware order of precedence to Image then Classes

---

api/v1alpha1/virtualmachine_types.go
api/v1alpha1/virtualmachineclass_types.go
api/v1alpha1/virtualmachineimage_types.go
api/v1alpha1/virtualmachinepublishrequest_types.go
api/v1alpha1/virtualmachineservice_types.go
api/v1alpha1/virtualmachinesetresourcepolicy_types.go
api/v1alpha2/virtualmachine_types.go
api/v1alpha2/virtualmachineclass_types.go
api/v1alpha2/virtualmachineimage_types.go
api/v1alpha2/virtualmachinepublishrequest_types.go
api/v1alpha2/virtualmachineservice_types.go
api/v1alpha2/virtualmachinesetresourcepolicy_types.go
config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineservices.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml

This is effectively a noop when the v1a2 FFS is not enabled since our post install configure script already forces the storageVersion back to v1a1 in that case. But when the FFS is enabled this results in the correct storageVersion being set.
```release-note
NONE
```

✨  Set v1a2 as the storageVersion

---

api/v1alpha2/virtualmachine_network_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go

First pass at better checks of the various Network fields during create. The existing table driven tests have reached their limit and are just too cumbersome to keep adding cases to. And it is annoying that the setup and assertion messages are not grouped together. Start new table driven tests for these new Network tests, and we should revisit the rest all the existing tests later once we've moved fully to v1a2. And I want to change we do the tests so that it is easier to share assertions between create and update.
Correct the Gateway4 and Gateway6 docs: these should not have the network prefix, just the IP.
```release-note
NONE
```

 ✨ Improve v1a2 VM Network validation checks

---

docs/concepts/images/vm-image.md
webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator_intg_test.go
webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator_unit_test.go
webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_intg_test.go
webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_unit_test.go

This patch updates the VM mutation webhook to take both namespace and cluster scope images into consideration when resolving the VM image resource from the specified friendly name. It also adds the corresponding implementation in v1a2.
```release-note
Consider both namespace and cluster scope images when mutating VM image names.
Add support for deploying VMs with friendly image status names in v1a2.
```
**Testing Done:**
- Updated test code to reflect this change
- Manually deployed this change to a testbed and verified all different cases:
```console
$ kubectl get vm -n sdiliyaer-test -o wide
NAME                                   POWER-STATE   CLASS               IMAGE …
```

🌱 Add friendly image name support in v1a2 and improve duplicate check

---

api/v1alpha1/virtualmachineimage_types.go
api/v1alpha2/virtualmachineimage_types.go
config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml

This PR updates the printer column of VirtualMachine Image (in both v1a1 and v1a2) to rename "Image Name" to "Human Readable Name". The previous "Image Name" can be confusing with the `spec.imageName` in the VirtualMachine type.
Manually applied the updated CRD in a testbed and verified the output printer column:
```console
$ kubectl get cvmi
NAME                    HUMAN-READABLE-NAME                                          VERSION                  OS-TYPE               FORMAT   AGE
vmi-9b0796bae7b11ea63   photon-3-amd64-vmi-k8s-v1.23.8---vmware.2-tkg.1-zshippable   v1.23.8+vmware.1-tkg.1   vmwarePhoton64Guest   OVF      151m
$ kubectl get vmi -n sdiliyaer-test
NAME …
```

🌱 Rename IMAGE-NAME to HUMAN-READABLE-NAME in VM Image printer column

---

api/v1alpha1/virtualmachineimage_types.go
api/v1alpha1/virtualmachinepublishrequest_types.go
api/v1alpha2/virtualmachineimage_types.go
config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
docs/concepts/images/vm-image.md
docs/ref/api/v1alpha1.md
docs/ref/api/v1alpha2.md

This patch updates all references of the image's "friendly/human-readable" name to "display name" as finalized with the team.
The API docs are updated by running `make generate-api-docs`.
```release-note
Adopt image display name in API and docs.
```
Kubectl output:
```console
$ kubectl  get vmi -n sdiliyaer-test
NAME                    DISPLAY-NAME          VERSION   OS-TYPE               FORMAT   AGE
vmi-4321c937fd22e514a   photon-ova_uefi-4.0   4.0       vmwarePhoton64Guest   OVF      5h17m
$ kubectl get cvmi
NAME                    DISPLAY-NAME                                                 VERSION                  OS-TYPE               FORMAT …
```

🌱 Adopt image display name in API and docs

---

hack/deploy-local.sh

This fixes the deploy-local.sh script to work with v1a2 FSS disabled scenarios. 
Fixes # N/A
waiting for gce2e-build to pass
```N/A
```

 🌱 Fix deploy-local script for v1a2 disabled scenarios

---

controllers/virtualmachine/v1alpha2/virtualmachine_controller.go
controllers/virtualmachine/v1alpha2/virtualmachine_controller_unit_test.go
pkg/vmprovider/fake/fake_vm_provider_a2.go
pkg/vmprovider/interface_a2.go
pkg/vmprovider/providers/vsphere2/constants/constants.go
pkg/vmprovider/providers/vsphere2/virtualmachine/backup.go
pkg/vmprovider/providers/vsphere2/virtualmachine/backup_test.go
pkg/vmprovider/providers/vsphere2/virtualmachine/virtualmachine_suite_test.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm.go

This patch adds the implementation code for VM backup in v1a2. It includes all the follow-up changes in #239 with some minor updates specific to v1a2.
```release-note
Add VM backup implementation for v1a2.
```

🌱 Add VM backup implementation for v1a2

---

api/v1alpha1/virtualmachine_conversion.go

There is various weirdness around how and what we set the v1a1 Prereq condition to, so this isn't quite a complete match but hopefully good enough.
For now just leave the conditions as-is when going from v1a1 to v1a2. We might later want to remove the Prereq - or other v1a1 only conditions - during that conversion.
```release-note
NONE
```

✨ Synthesize v1a1 Prereq condition from v1a2 conditions

---

webhooks/virtualmachine/webhooks.go

The v1a1 VM mutating webhooks are still required in a v1a2 environment to preserve fields in v1a1 unknown to v1a2 CR.
The mutation webhooks also run serially, so they don't have the problem of racing that a validation webhook would have.
Fixes # N/A
N/A
```
N/A
```

🌱 Enabled v1a1 VM mutation webhooks on v1a2 FSS enabled env

---

api/v1alpha2/virtualmachineclass_types.go

The v1a2 class is implicitly scoped because we don't have the bindings. Note this still requires the WCP_Namespaced_VM_Class FFS, and the generated manifest is unchanged because v1a1 is still marked as Cluster scoped.
```release-note
NONE
```

✨  Mark v1a2 VirtualMachineClass as namespace scoped

---

api/v1alpha1/virtualmachine_conversion.go
api/v1alpha2/virtualmachine_network_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
pkg/vmprovider/providers/vsphere2/network/gosc_test.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_linuxprep_test.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_sysprep.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_sysprep_test.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go

Accumulated fixes as we've continued to test v1a2
- Add a basic to v1a1 version conversion for SysPrep
- Use dashes as MAC address separators for SysPrep GOSC
- Do templating for SysPrep
- Fix an off by one preventing from fixing up the MAC address in VDS
- Correct API doc copy-paste for the DHCP6 and Gateway6 fields
```release-note
NONE
```

 🐛 Various v1a2 bug fixes

---

config/wcp/vmoperator/manager_env_var_patch.yaml
pkg/builder/auth.go
pkg/builder/mutating_webhook.go
pkg/builder/validating_webhook.go
pkg/lib/env.go
webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_unit_test.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go

Currently, we have webhooks to prevent users from modifying system used annotations.  This is done by validating if the user making the request is the kube-admin user.  However, other parts of the infrastructure (such as WCP service) are not considered privileged, which is required for backup/restore.
This changes expands the definition of a privileged account by including WCP service solution user.  The code expects this particular environment variable to be present in the pod's environment variable.
Testing Done:
1. Create a ServiceAccount
2. Create a ClusterRoleBinding with a roleRef that gives the ServiceAccount permissions to edit/update/delete VM resources
3. Invoke create VM with a reserved annotation
```
$ k apply -f …
```

:seedling: Allow privileged users to modify annotations on a VirtualMachine object

---

pkg/context/backupvirtualmachine_context.go
pkg/vmprovider/providers/vsphere/virtualmachine/backup.go
pkg/vmprovider/providers/vsphere/virtualmachine/backup_test.go
pkg/vmprovider/providers/vsphere/vmprovider_vm.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_utils_test.go
pkg/vmprovider/providers/vsphere2/virtualmachine/backup.go
pkg/vmprovider/providers/vsphere2/virtualmachine/backup_test.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go

This PR stores a VM's disk UUID to PVC mapping info in ExtraConfig during the backup process. This will enable us to register the volumes of the VM with the same PVC name and access modes during the restore. The change has also been added to the v1a2 package.
A helper function is added in `vmprovider_vm_utils.go` to retrieve the disk UUID to PVC mapping. This eliminates the need to pass a K8s client in the `backup.go` file. Also, the `BackupVirtualMachine` function is updated to have all the necessary params from the new `BackupOptions` struct.
```release-note
Persist VM's disk UUID to PVC mapping info in ExtraConfig during VM reconciliation.
``` …

✨ Persist PVC related info in VM ExtraConfig for backup

---

pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go

This PR adds validation on Network Spec with its supported Bootstrap types (according to eg, https://github.com/vmware-tanzu/vm-operator/blob/main/api/v1alpha2/virtualmachine_network_types.go#L125) and unit tests.
This PR also reformats Bootstrap validation unit tests to be more verbose and easier to understand.
Fixes # N/A
```release-note
Adds validation on Network Spec with its supported Bootstrap types
```

:sparkles: Add validations for Networkspec with its supported Bootstrap and unit tests

---

api/v1alpha1/virtualmachine_types.go
api/v1alpha2/virtualmachine_types.go
pkg/vmprovider/providers/vsphere/constants/constants.go
pkg/vmprovider/providers/vsphere/session/session_vm_update.go
pkg/vmprovider/providers/vsphere/virtualmachine/backup.go
pkg/vmprovider/providers/vsphere/virtualmachine/backup_test.go
pkg/vmprovider/providers/vsphere/virtualmachine/configspec.go
pkg/vmprovider/providers/vsphere2/constants/constants.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
pkg/vmprovider/providers/vsphere2/virtualmachine/backup.go
pkg/vmprovider/providers/vsphere2/virtualmachine/backup_test.go
pkg/vmprovider/providers/vsphere2/virtualmachine/configspec.go

This PR moves the constants used for VM backup/restore into the API module to enforce a contract. These constants are utilized when registering a VM Service VM as part of the VM restore process.
The WCP service codebase will be updated to use these constants imported from the vm-operator/api module once this change is applied.
```release-note
Move VM backup/restore related constants to the API module to enforce a contract.
```

🌱 Move VM backup/restore related constants to API module

---

api/v1alpha2/virtualmachineclass_types.go

This reverts commit 25b6933d95656b4178f23a5a7c4229c0cf99573b.
While apparently very biased towards v1a1, the controller-gen manifest output is not deterministic. Since this change was just for informational purposes - the Scope field is fixed up later - revert this change.
```release-note
NONE
```

🐛 Revert "Mark v1a2 VirtualMachineClass as namespace scoped"

---

api/v1alpha2/cloudinit/cloudconfig.go

This was just accidentally omitted and required for proper serialization.
```release-note
NONE
```

🐛 Add missing omitempty on CloudConfig User Passwd field

---

controllers/virtualmachine/v1alpha1/virtualmachine_controller.go
controllers/virtualmachine/v1alpha2/virtualmachine_controller.go

The same error during MV reconcile normal loop gets logged twice which clutters the log files with duplicates. Removing one of the loggers from VM reconcile loop.
n/a
n/a
```release-note
🌱 Removing duplicate error logger in VM controller
```

🌱 Removing duplicate  error logger in VM controller

---

pkg/vmprovider/providers/vsphere/session/session_vm_update.go
pkg/vmprovider/providers/vsphere/session/session_vm_update_test.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go

This change removes the update of deviceGroups in the UpdateVM path. We don't currently support this workflow on Update and DeviceGroups are already covered in the CreatePath. The code for this is currently incomplete to support deviceGroups on update and will be prioritized when we support Resizing VMs in VM operator.
Fixes # N/A
N/A
```
```

🐛 Remove updates to DeviceGroups

---

api/v1alpha1/virtualmachine_types.go
api/v1alpha2/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
pkg/util/configspec.go
pkg/util/configspec_test.go
pkg/util/hardware_version.go
pkg/util/hardware_version_test.go
pkg/vmprovider/providers/vsphere/contentlibrary/content_library_utils.go
pkg/vmprovider/providers/vsphere/contentlibrary/content_library_utils_test.go
pkg/vmprovider/providers/vsphere/session/session_vm_status.go
pkg/vmprovider/providers/vsphere/vmprovider_vm.go
pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status_test.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go
test/builder/util.go
test/builder/utila2.go
webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_intg_test.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_intg_test.go

Introduces a new field on the VirtualMachine CRD which allows the user to define the minimum hardware version for the provisioned VM. The behavior of the field is as follows:
- If the VMClassAsConfig FSS is enabled, this new field will override the hardware version derived from the VMClass's ConfigSpec if that value is lower than the minimum version field. Otherwise, the value from the ConfigSpec is honored.
- If the VMClassAsConfig FSS is disabled, it will reconfigure the VM post creation before the power on operation to ensure that the h/w version is atleast set to the minimum version. This means, it can override the hardware version of the OVA with a hardware version value lower than this field.
**Which issue(s) is/are addressed by this …

✨ Adds minimum hardware version to VirtualMachine CRD

---

.github/workflows/ci.yml
Dockerfile

According to govulncheck, Vulnerability `Insecure parsing of Windows paths with a \??\ prefix in path/filepath` is fixed in `go1.21.4`. Bumping up go version.
Fixes #N/A
```release-note
Bump up go version from 1.21.3 to 1.21.4
```

:seedling: Bump up go version from 1.21.3 to 1.21.4

---

pkg/builder/mutating_webhook.go
pkg/context/webhook_request_context.go
webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_intg_test.go
webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_unit_test.go
webhooks/virtualmachineclass/v1alpha2/mutation/virtualmachineclass_mutator.go
webhooks/virtualmachineservice/v1alpha2/mutation/virtualmachineservice_mutator.go

Use the admission request original raw json byte array as the diff patch source: this is needed to generate the correct json diff patches for nested optional fields. This matches a change made to controller-runtime webhook server that we'll eventually switch to.
Sync over remaining differences in the v1a2 webhook and tests from v1a1
```release-note
NONE
```

🐛 v1a2 VM mutation webhook updates

---

test/builder/test_suite.go

ee7ca92ce changed the install path. This is the fallback path when KUBEBUILDER_ASSETS is unset.
```release-note
NONE
```

Fix envtest assets directory

---

webhooks/virtualmachine/webhooks.go

The v1a1 VM mutation webhook can be safely removed now because the v1a2 VM mutation webhook does the needful.
Fixes # N/A
We initially had certain things that only the v1a1 VM mutation webhook did. Currently both the v1a1 and v1a2 VM mutation webhook do the same things. 
```
```

🌱 Remove v1a1 VM mutation webhook when v1a2 FSS is enabled

---

api/v1alpha1/virtualmachineimage_conversion.go
api/v1alpha2/virtualmachineimage_types.go
controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller_intg_test.go
controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller_unit_test.go
controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller.go
controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller_intg_test.go
controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller_unit_test.go
pkg/conditions2/getter.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
test/builder/vcsim_test_context.go

This patch introduces 2 different approaches to add a Ready condition to the ClusterVirtualMachineImage and VirtualMachineImage CRs. 
For ClusterVirtualMachineImage, we have added the Ready condition in addition the existing conditions, and calculated the Ready condition as a summary of the existing conditions on the CVMI.
For VirtualMachineImage, we have removed the existing conditions and used the appropriate reason when setting the Ready condition on the VMI.
**Which issue(s) is/are addressed by this PR?** *(optional)*:
Fixes n/a
Following tests have been done:
- Existing CVMI resource's Status with previous condition types are replaced with the `Ready` condition **only**.
- Existing VMI …

🌱 Adds a Ready condition to CVMI and VMI resources

---

api/v1alpha1/virtualmachineimage_conversion.go
hack/test-unit.sh

This patch adds the github.com/vmware-tanzu/vm-operator/api module to be run when running the test Makefile target. Since ./api directory is a separate go module, we run the tests via a separate go command.
This also fixes a minor VMI/CVMI conversion issue wherein an empty condition set should always return an empty condition set on up/down conversion.
n/a
```release-note
NONE
```

🌱 Adds api unit tests to Makefile

---

api/v1alpha1/virtualmachineimage_conversion.go
api/v1alpha1/zz_generated.conversion.go
api/v1alpha2/virtualmachineimage_types.go
api/v1alpha2/zz_generated.deepcopy.go
config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
pkg/vmprovider/providers/vsphere2/contentlibrary/content_library_utils.go
pkg/vmprovider/providers/vsphere2/contentlibrary/content_library_utils_test.go

One of the goals w/ this is to make Metadata watches more effective in v1a2 by not having big yamls in the ObjectMeta.
This change moves the
- tkg vmware-system-* annotations to a v1a2 status field
- adds conversions for this status field to convert to annotations for v1a1.
- v1a1 annotations when up-converted are copied over to the v1a2 status field and removed from v1a2 annotations if already present
Fixes # N/A
Testing TKC deployments and scaled up to check vmware-system annotations are fetched from the v1a1 …

✨Move tkg vmware-system-* annotations to vmi/cvmi status

---

webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go

This change fixes the v1a2 network CR name validation to use the DNSSubDomain. 
This also fixes the error message to be more clear.
Fixes # N/A
N/A
```
```

Fix network name validation to use DNSSubDomain

---

webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_unit_test.go

When the Network stanza is entirely omitted we'd otherwise NPE when adding the default network interface.
Fixes b54465
```release-note
NONE
```

🐛 Check VM.Spec.Network for nil in v1a2 mutation wehbook

---

api/v1alpha1/virtualmachineclass_conversion.go

After e1d2e468ed7, this is not needed anymore since the Status is now empty. In general, restoring the Status, when it is a subresource, is not needed since only our controllers will update it, and the Status will be re-observed after a reconcile.
```release-note
NONE
```

🌱 Remove v1a2 VirtualMachineClass annotation conversion

---

docs/concepts/workloads/guest.md
docs/tutorials/deploy-vm/README.md
docs/tutorials/deploy-vm/cloudinit.md
docs/tutorials/deploy-vm/vappconfig.md

This patch fixes some formatting / wording issues in the vApp bootstrap docs.
Fixes `NONE`
```release-note
Fixes some errors in the vApp bootstrap documentation.
```
----
📚 Documentation preview 📚: https://vm-operator--307.org.readthedocs.build/en/307/

🐛 Fix bugs in vApp bootstrap docs

---

pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status_test.go

We have a long ways to go before we actually support multiple interfaces, both in bootstrap and in reconcile. The exceedingly common case is just one interface so special case that to provide the interface name in the Status.
```release-note
NONE
```

✨ Set more useful interface name in v1a2 VM Status

---

.golangci.yml
api/v1alpha1/virtualmachine_types.go
api/v1alpha2/virtualmachine_readiness_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml

This probe method was added at the last minute of the first WCP release as a stopgap to address a limitation with the NSX-T LB at the time. Since the probe is done via VM Operator pod on one of the Supervisor CP VMs it requires network connectivity that does not exist in certain environments, and TKGs - the primary user of this probe method - will be switching to different method that's introduced in v1a2.
```release-note
The TCPSocket probe action is deprecated and will be removed in a later API version.
```

⚠️ Add note that the TCPSocket probe method is deprecated

---

pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go

We have E2E tests that assume this behavior so preserve that in v1a2 as well. The pointer API change in b54465 changed the behavior to exit bootstrap early. This is just a quick fix to get pipelines fixed. There is an existing story to both improve this default behavior - like by inspecting the image OS, and to keep addressing the prior lack of tests in this area.

🐛 Restore previous LinuxPrep default customization behavior

---

pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go

v1a1 did not have a Key field to specify the Secret key to find the userdata in so we'd try a few well-known keys. So for just CloudInit check for the existence of those well-known keys as well when checking for a required key in the CloudInit Secret.
This fixes TKGs post 5e4469e9.
```release-note
NONE
```

🐛 Check for well-known CloudInit userdata keys

---

controllers/virtualmachinesetresourcepolicy/v1alpha2/virtualmachinesetresourcepolicy_controller.go
controllers/virtualmachinesetresourcepolicy/v1alpha2/virtualmachinesetresourcepolicy_controller_unit_test.go

🐛 Fix NPE when VM does not have a Reserved field

---

.golangci.yml
api/v1alpha1/virtualmachineimage_types.go
config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml

We do not have a corresponding field in v1a2, and this specific provider field ideally should not be apart of our generic image type. If needed, this can be looked up via the Spec.ProviderRef.
```release-note
The v1alpha1 ClusterVirtualMachineImage and VirtualMachineImage Status.ContentLibraryRef field is deprecated. Instead for images provided by a Content Library, the Spec.ProviderRef will point to either a ContentLibraryItem ClusterContentLibraryItem that contains a reference to the Content Library.
```

⚠️ Mark the v1a1 VirtualMachineImage ContentLibraryRef field as deprecated

---

pkg/util/cloudinit/schema/Makefile

This patch fixes a weird issue when generate the Golang type(s) for a Cloud-Init CloudConfig. When generating them via Docker, the program quicktype used the schema's filename as part of the generated types. This caused the file to look different when generated locally versus when generated via a container.
Fixes `NA`
```release-note
Fixes mismatched `cloudconfig.go` when using `quicktype` via Docker versus locally
```

🐛 Fix generated CloudConfig type via Docker

---

api/v1alpha1/conversion_test.go
api/v1alpha1/virtualmachine_conversion.go
api/v1alpha1/virtualmachine_conversion_test.go
pkg/vmprovider/providers/vsphere2/network/network_test.go

Start with a nearly fully populated v1a2 VM and ensure that the VM resulting from conversion is the same. We can keep adding these explicit conversion tests to ensure that fields are converted as we expect instead of always depending on the fuzzer.
Fix a few conversion issues around the Network and Advanced fields.
Always restore the full VM status from the annotations. Our controller should be the only one updating the Status, and an update from the conversion will cause our controllers to reconcile and reevaluate the Status.
```release-note
NONE
```

✨ Add VirtualMachine conversion tests

---

api/v1alpha1/virtualmachineimage_conversion.go
api/v1alpha1/virtualmachineimage_conversion_test.go
controllers/contentlibrary/v1alpha1/contentlibraryitem/contentlibraryitem_controller.go
controllers/contentlibrary/v1alpha1/utils/test_utils.go

The VirtualMachineImage provided by the namespace scoped ContentLibraryItem so the Namespace field should have been set in the ProviderRef. Otherwise, the field documentation the referenced kind is cluster scoped.
Populate the namespace field when down converting the image to v1a1.
```release-note
For namespaced scoped VirtualMachineImages the Namespace field in the Spec.ProviderRef is now set.
```

🐛 Set Namespace in v1a1 VirtualMachineImage ProviderRef

---

pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm2_test.go

Post b54465, several spec fields were changed to pointers so add test to cover if those are nil, and fix a few bugs.
```release-note
NONE
```

🐛 Add provider test for nil v1a2 VM Spec nil fields

---

api/v1alpha1/conversion_test.go
api/v1alpha1/virtualmachineimage_conversion.go
api/v1alpha1/virtualmachineimage_conversion_test.go
api/v1alpha2/virtualmachineimage_types.go
controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller_intg_test.go
controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller.go
controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller_intg_test.go

In the VMI and CVMI v1a2 controllers, we add the conversion annotation by converting the current v1a2 object to a v1a1 object and adding the content library ref info into the v1a1 CVMI status. This v1a1 object is then marshalled and stored as an annotation in the v1a2 object. When a v1a1 object is requested by the client, the conversion function ConvertTo() accesses this stored annotation, unmarshalls it to get the content library data and sets it on the v1a1 object.
n/a
Here is the excerpt of an existing VMI from a v1a2 FSS enabled testbed
```bash
$ k get vmi -n trial vmi-004ebcb5558f33270 -oyaml
apiVersion: vmoperator.vmware.com/v1alpha2 …
```

🌱 Add conversion annotation to CVMI/VMI to populate missing field

---

controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller.go
controllers/contentlibrary/v1alpha2/utils/utils.go
controllers/contentlibrary/v1alpha2/utils/utils_test.go

This patch moves the common logic of checking for an annotation on the VMI and CVMI v1a2 objects into a common utility function. This is a follow up from the [comment](https://github.com/vmware-tanzu/vm-operator/pull/313#discussion_r1432943964) on #313 
n/a
n/a
```release-note
NONE
```

🌱 Moves common annotation logic to util package

---

api/v1alpha2/cloudinit/cloudconfig.go
api/v1alpha2/cloudinit/zz_generated.deepcopy.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
pkg/util/cloudinit/cloudconfig.go
pkg/util/cloudinit/cloudconfig_secret.go
pkg/util/cloudinit/cloudconfig_secret_test.go
pkg/util/cloudinit/cloudconfig_test.go
pkg/util/cloudinit/validate/validate.go
pkg/util/cloudinit/validate/validate_test.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit_test.go

This patch updates the inline cloud config's runcmd field to be of type json.RawMessage instead of a slice of them. This is because kubebuilder cannot generate the correct CRD for elements in the slice, and they are expected to be base64-encoded. Instead the entire runcmd is now a json.RawMessage.
Additionally, this patch fixes an issue in the validation logic for the inline cloud config. It was based on YAML in, YAML out, but it should have been JSON in, YAML out.
Fixes `NA`
I applied the CRD to a kind cluster and was …

🐛 Fix cloudconfig runcmd / YAML->JSON on parse

---

api/v1alpha2/cloudinit/cloudconfig.go
api/v1alpha2/testdata/vm-with-cloudinit.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
pkg/util/cloudinit/cloudconfig.go
pkg/util/cloudinit/cloudconfig_test.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit_test.go

Use DefaultUserEnabled as the field name for when the default user should still be created when other users are specified.
Update the VM with CloudInit example yaml
```release-note
NONE
```

🌱 Rename inlined CloudInit default user field

---

.gitignore
Makefile
docs/requirements.txt
docs/start/contrib/submit-change.md
mkdocs.yml

This patch updates the version of mkdocs used to build the docs as well as versions of the dependencies required by mkdocs. This patch also introduces two, new Makefile targets, `docs-build-python` and `docs-build-docker` for building the documentation without serving it.
Fixes `NA`
```release-note
NONE
```
----
📚 Documentation preview 📚: https://vm-operator--322.org.readthedocs.build/en/322/

🌱 Update mkdocs ver & deps ver & build-docs mk

---

pkg/vmprovider/providers/vsphere2/session/session_vm.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go
pkg/vmprovider/providers/vsphere2/virtualmachine/configspec.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/create_clone.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm.go

During VM creation, if the Spec.Advanced field was nil, we'd always set the field to its empty structure. Later when we would Patch the k8s VM at the end of reconcile, the field would get updated. This meant that every VM would have the Advanced field set even when not using any of the advance features.
Fix several NPE bugs the assignment was masking.
```release-note
NONE
```

🐛 Do not always initialize v1a2 VM Spec.Advanced field

---

.github/configs/labeler.yml
.github/workflows/pr-labeler.yml

Bump the version of the PR Labeler action, updating to the newer configuration schema. The size configuration was changed a few versions ago. I'm looking to remove support so I'm sending some PRs to the very few repos that still rely on it.
I updated the reference to the action to master. This actually uses the latest stable version so it should avoid any unintended breakage.
Thanks for using the action!

🌱 Update deprecated pr labeler version

---

api/v1alpha2/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml

Sync power state and age from v1a1
Use the Spec for the image and class names: for the time being, the corresponding status fields are updated until after the VM has been created on VC.
```release-note
NONE
```

🌱 Update v1a2 VM printer columns

---

test/builder/test_suite.go

This patch updates the scope of the VM Class CRD in the test builder based on the presence and value of the VM Class Namespace FSS.
Fixes `NA`
```release-note
NONE
```

🐛 Update VM Class scope in test builder for FSS

---

api/v1alpha2/virtualmachine_types.go
pkg/context/backupvirtualmachine_context.go
pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
pkg/vmprovider/providers/vsphere2/virtualmachine/backup.go
pkg/vmprovider/providers/vsphere2/virtualmachine/backup_test.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go

- Replace `BackupVirtualMachineContextA2` with `BackupVirtualMachineOptions`.
- Store VM resource YAML in the "vmservice.virtualmachine.resource.yaml" ExtraConfig key.
- Store VM bootstrap relevant resources YAML (separated by "---") in the "vmservice.virtualmachine.additional.resources.yaml" ExtraConfig key.
These changes are needed to better support backup/restore for v1a2 VMs.
- A separate PR will be pushed to either update or remove the v1a1 backup controller code (as it won't be executed if v1a2 and B/R features are enabled in the same release).
```release-note
Refactor v1a2 backup to store all bootstrap referencing objects YAML as additional …
```

🌱 Refactor v1a2 backup to store all VM additional resources YAML in ExtraConfig

---

pkg/util/cloudinit/cloudconfig.go
pkg/util/cloudinit/cloudconfig_test.go
pkg/util/cloudinit/validate/testdata/valid-cloud-config-1.yaml
pkg/util/cloudinit/validate/validate.go
pkg/util/cloudinit/validate/validate_test.go

This patch fixes the validation logic to include the content in the CloudInit WriteFiles section to be empty. Since the API declares it as a required field, we set it to empty during the marshaling process to generate the YAML cloudconfig document.
n/a
n/a
```release-note
🐛 Fixes empty or unset write file content in cloudinit
```

🐛 Fixes unset/empty write file content in cloudinit

---

api/v1alpha1/virtualmachineimage_conversion.go
api/v1alpha1/virtualmachineimage_conversion_test.go

When going from an originally v1a1 VMI to v1a2 VMI, the condition may not have a Reason set since it was optional in v1a1. However, in v1a2 that is now a required field so ensure that field is set. We use the Status field since we don't have anything better.
Add a bunch of missing condition conversion tests.
```release-note
NONE
```

🐛 Fix VirtualMachineImage condition version conversion

---

api/v1alpha1/virtualmachineimage_conversion.go
api/v1alpha1/virtualmachineimage_conversion_test.go

This patch adds tests to up-down and down-up conversion between system annotations and status system properties.
n/a
n/a
```release-note
NONE
```

🌱 Adds VMI/CVMI test for annotation-status property conversion

---

pkg/util/cloudinit/schema/Dockerfile.quicktype
pkg/util/cloudinit/schema/Makefile

This patch updates the npm command used to generate the typws for cloud init. Instead of using npm install which will install packages from the node_modules cache, `npm ci` will always use the packages defined in `package-lock.json` to ensure a reproducible build on every run.
Fixes [failed](https://github.com/vmware-tanzu/vm-operator/actions/runs/7451363966/job/20272336654?pr=339) `verify-codegen` GH actions
```
make cloudconfig.go
make[4]: Entering directory '/home/runner/work/vm-operator/vm-operator/pkg/util/cloudinit/schema'
npm install --user quicktype
.....
diff --git a/pkg/util/cloudinit/schema/package-lock.json b/pkg/util/cloudinit/schema/package-lock.json
index …
```

🐛  [codegen]: Uses npm ci command to generate schema types

---

api/v1alpha1/virtualmachine_conversion.go
api/v1alpha1/virtualmachine_conversion_test.go

Resort a few of the bootstrap hubSpokeHub tests to be grouped together.
```release-note
NONE
```

🐛 Restore v1a2 Sysprep with vAppConfig in hub-spoke-hub

---

api/v1alpha2/testdata/vm-with-cloudinit.yaml

ee0250839 remove these top-level fields in favor of always be apart of the interfaces.
```release-note
NONE
```

🌱 Fix v1a2 cloud-init example

---

controllers/volume/controllers.go

🐛 Do not add the v1a1 Volume controller when v1a2 is enabled

---

api/v1alpha2/virtualmachine_network_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml

Since the networkInterface name is used in the CRD, we need to make sure it is DNSSubDomain compliant. It cannot include A-Z or underscore.
Fixes #
N/A
Earlier: 
```
root@422c3dc1f0a803888601c2f7bd08a66a [ ~ ]# kubectl apply -f vm.yaml
Error from server (spec.network.interfaces[0].name: Invalid value: "vm-v1a2-ETH0": is the resulting network interface name: a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. …
```

Update NetworkInterface Name field pattern validation

---

api/v1alpha2/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml

This isn't supported yet so remove it from the docs until we get to implementing it.
```release-note
NONE
```
(because this isn't release yet)

📖 Remove bootstrap doc about automatic LinuxPrep/Sysprep

---

pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_sysprep.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_sysprep_test.go

The intention with the hostName field is to let the user specify a name that's different than the k8s VM object name.
```release-note
NONE
```

🌱 Use Network Hostname if set for Sysprep computer name

---

pkg/util/configspec.go
pkg/util/configspec_test.go
pkg/vmprovider/providers/vsphere/constants/constants.go
pkg/vmprovider/providers/vsphere/session/session_vm_update.go
pkg/vmprovider/providers/vsphere/session/session_vm_update_test.go
pkg/vmprovider/providers/vsphere2/constants/constants.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm.go

It used to be the case that VI Admins could not manage the power state of VM Service managed VMs on vSphere via API or the HTML5 client (H5C). This presented a challenge to maintenance mode. If a VM could not be automatically evacuated from a host entering maintenance mode, the host could not successfully enter maintenance mode. In vSphere 7, VMs with vGPUs were not automatically vMotioned, and in vSphere 8+, VMs with PCI Passthru devices still are not vMotioned. There are also other CPU related settings that might pin a VM to a host, preventing DRS from vMotioning a VM to evacuate it off of a host entering maintenance mode.
Normally a VI Admin would power off a VM that blocks maintenance mode, but since VM Service managed VMs used to …

✨ Disable DRS PowerOff for VMs with vGPU/Dynamic Direct Path IO devices

---

pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit.go

This PR updates the `bootstrap_cloudinit.go` file to use the `MergeExtraConfig` function so that the existing EC also gets updated. This ensures that the VM is reconfigured with accurate data when updated (e.g. cloud-init `guestinfo.metadata` with a different instance ID).
```release-note
Update existing ExtraConfig keys if the values are changed.
```

🐛 Update bootstrap_cloudinit to use MergeExtraConfig

---

api/v1alpha1/condition_consts.go
api/v1alpha2/virtualmachine_types.go
pkg/util/bootstrap_condition.go
pkg/util/bootstrap_condition_test.go
pkg/vmprovider/providers/vsphere/session/session_vm_status.go
pkg/vmprovider/providers/vsphere/session/session_vm_status_test.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status_test.go

This patch introduces the condition `GuestBootstrap` such that its status, reason, and message are all surfaced from reading the ExtraConfig key `guestinfo.vmservice.bootstrap.condition`. The key's value is comma-delimited, split at most three times:
| Index | Description |
|---|---|
| `0` | The condition's status |
| `1` | The condition's reason |
| `2` | The condition's message |
The following values for `guestinfo.vmservice.bootstrap.condition` would be parsed accordingly:
| Value | Status | Reason | Message |
|---|---|---|---|
| ` ` | `false` | | |
| `, ,` | `false` | | |
| `  , my-reason` | `false` | `my-reason` | |
| `,my-reason,my-message` | `false` | `my-reason` | `my-message` |
| `a non-truthy value` | `false` | | |
| `a non-truthy …

✨ Guest bootstrap status as condition

---

config/local/vmoperator/local_env_var_patch.yaml
controllers/contentlibrary/v1alpha1/contentlibraryitem/contentlibraryitem_controller_suite_test.go
controllers/virtualmachinepublishrequest/v1alpha1/virtualmachinepublishrequest_controller_suite_test.go
pkg/config/default.go
pkg/config/env_test.go

This patch updates the logic in `pkg/config` to treat the v1a2 FSS as true by default since this feature was enabled on main.
Fixes `NA`
The two test updates were required due to them being integration tests for v1a1 that do not expect v1a2 to be enabled.
```release-note
Enable v1alpha2 by default.
```

✨ Set v1a2 FSS to true by default

---

config/local/vmoperator/local_env_var_patch.yaml

This patch updates the local env var patch applied to local Kind instances so that enabled FSSs are set to true by default. This patch touches the following features: Unified TKG, Instance Storage, VM Class as Config, VM Class as Config DnD, Image Registry, Namespaced VM Class, and Sysprep.
Fixes `NA`
```release-note
NONE
```

✨ Set enabled FSSs to true by default

---

pkg/config/config.go
pkg/config/default.go
pkg/constants/constants.go
webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator_intg_test.go
webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator_suite_test.go
webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator_unit_test.go
webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_unit_test.go
webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_intg_test.go
webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_suite_test.go
webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_unit_test.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go

This patch introduces support for the `created-at` annotations for VM resources. A VM's mutation webhook ensures the first time a VM is created the following annotations are patched into the VM:
* `vmoperator.vmware.com/created-at-build-version`
* `vmoperator.vmware.com/created-at-schema-version`
The above information allows future changes to VM Operator know helpful details about the version of VM Operator and schema version that were used to create a VM resource. Even the absence of the information is informative as it indicates the VM was created before the annotations were introduced.
**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when …

✨ Created-at annotations

---

webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator_unit_test.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go

This PR updates the VM validation webhook to no longer check annotations for creation requests.
This ensures that the mutation webhook can update the VM's annotations in creation request without subsequent failure from the validation webhook.
N/A.
This is a fix forward to #364 which fails VM creation from non-admin users.
```release-note
Drop validating annotations added by mutation webhook upon VM creation.
```

🐛 Drop validating annotations added by mutation webhook upon VM creation

---

api/v1alpha1/virtualmachine_conversion.go

While the prior code worked, it was a little confusing because we'd overwrite the fields with itself. Fix the comment and code to make the intention clearer.
```release-note
NONE
```

🌱 Clean up how Sysprep w/ vAppConfig is restored

---

pkg/util/kube/vm.go
pkg/util/kube/vm_test.go
pkg/vmprovider/providers/vsphere/session/session_vm_update.go
pkg/vmprovider/providers/vsphere/session/session_vm_update_test.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go
test/builder/vcsim_test_context.go

This PR skips persisting backup ExtraConfig keys in TKG node VMs when the `AutoVADPBackupRestore` feature is enabled.  
TKG node VMs will be backed up and restored differently (outside of VM-Operator reconciliation), hence do not require the backup ExtraConfig keys. These keys are only necessary for VM Service managed VMs.
N/A
The `HasTKGLabels` function has been moved to a new util file as it is used in multiple locations.
```release-note
Skip persisting backup ExtraConfig keys in TKG VMs when the AutoVADPBackupRestore feature is enabled.
```
**Testing Done**
- Deployed TKG VMs to an internal testbed …

🌱 Skip VM Service B/R workflow for TKG node VMs

---

pkg/util/devices.go
pkg/util/devices_test.go
pkg/vmprovider/providers/vsphere2/virtualmachine/configspec.go
pkg/vmprovider/providers/vsphere2/virtualmachine/configspec_test.go
pkg/vmprovider/providers/vsphere2/virtualmachine/virtualmachine_suite_test.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go

The logic for determining the ConfigSpec version was spread out in two different functions and done separately after creating the ConfigSpec. The version can come from the class ConfigSpec or the class (passthru) devices, image, VM Spec MinHardwareVersion, or if the VM has PVCs at create time. Now have one function that is responsible for determining the version.
Prior logic was a little confusing - hopefully this will make the intention clearer
```release-note
NONE
```

🌱 Set HW Version in CreateConfigSpec()

---

pkg/vmprovider/providers/vsphere/storage/storageclass.go

This is a partial revert of 177578e. Regardless if the PodVMOnStretchedSupervisor FFS is enabled and if this setup is stretched we can always resolve the storage policy ID via the cluster scoped StorageClass. The storage namespace association has already be validated by this point.
While here don't export GetStoragePolicyID().
```release-note
NONE
```

🌱 Simplify get storage policy ID from storage class name

---

pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go

This PR adds GVK into the bootstrap secret resources during backup, so that they can be recreated successfully during the restore. 
It appears that the `Decoder` used for getting K8s core resources clears the GVK info (see https://github.com/kubernetes/kubernetes/issues/80609 for more details).
N/A.
N/A.
```release-note
Add GVK in additional resource backup to ensure a successful restore of VM bootstrap data.
```
**Testing Done**:
- CloudInit with inlined secret data
```
$ govc vm.info -e "test-ubuntu-impish-inlined-cloud-config" | grep "vmservice.virtualmachine.additional.resources.yaml" | awk …
```

🐛 Add GVK in additional resource backup

---

pkg/vmprovider/providers/vsphere2/vmprovider_vm.go

This seems like a miss in https://github.com/vmware-tanzu/vm-operator/commit/a8c499d14118a0b9c687d850135fe1594121b7ce when we added the inline Sysprep bootstrap support.
If a Secret key is specified in the inline Sysprep bootstrap, it does get retrieved, but it's not currently being passed to the create/updateArgs. This causes the `CustomizationGuiUnattended` failed because of missing data. 
N/A.
N/A.
```release-note
Set Sysprep bootstrap secret data in createArgs & updateArgs to ensure successful GOSC when VM bootstrap spec contains inline Sysprep.
```

🐛 Set Sysprep bootstrap secret data in createArgs & updateArgs

---

pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm2_test.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go

The VM SetResourcePool, Bootstrap, and Network are optional so only set their corresponding ready conditions when they're specified.  We were setting the Bootstrap ready condition when Bootstrap was nil. We we were not setting the other two when not specified or disabled.  Add some conditions.Delete() calls to make the not setting a condition explicit.
Add a bunch of expected condition assertions
Fixes #
I'm cool if we want to set these conditions to true when not specified instead. It's just that they should all behave the same.
```release-note
NONE
```

🌱 Commonize setting of optional VM ready conditions

---

pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go

If the VC VM already has an Annotation then leave it as-is instead of always reverting back to our default.
```release-note
If the VirtualMachineClass ConfigSpec has the Annotation field set, then a VM created from the class will have that Annotation.
```

🌱 Preserve class ConfigSpec Annotation if set

---

pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_sysprep.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_sysprep_test.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go

If neither the raw or cooked sysprep data is provided the Windows GOSC Customize() call will fail, and since an empty text for raw sysprep also fails just disallow that configuration.
If wanting to do an empty Sysprep ends up being a common request - so the networking is configured - we can investigate more to see if there is some noop default we can fallback to.
```release-note
NONE
```

 🐛 Disallow empty sysPrep bootstrap

---

Makefile
config/default/kustomization.yaml
config/default/manager_default_container_patch.yaml
hack/deploy-local-certmanager.sh

This change makes `manager` the default container so that commands like `kubectl exec` and `kubectl logs` pick that container by default.
Also handle a few trivial things like:
- Changing the now unsupported `verbosity` with `-v` flag in kind load
- Removing the incorrect kustomize path since we now add HOSTOSARCH in the binary path
- Generated the manifests and verified that the annotation is present: 
```
$ grep -r 'kubectl.kubernetes.io/default-container: manager' artifacts/local-deployment.yaml artifacts/local-deployment.yaml:
kubectl.kubernetes.io/default-container: manager
```
- Verified that kubectl logs pick up the default container
```
$ k logs -n vmware-system-vmop vmware-system-vmop-controller-manager-6f8d6f8c78-wh5z8 | head …
```

🌱 Make manager the default container

---

pkg/util/devices.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update.go

Use a type check instead of enumerating possible devices to determine if a device is a VirtualEthernetCard.  This also includes the OG vmxnet device that wasn't in the prior list.
```release-note
NONE
```

🌱 Simplify check if a device is a VirtualEthernetCard

---

api/v1alpha2/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
pkg/vmprovider/providers/vsphere2/storage/storageclass.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_test.go

If we require a storage class - which as of today will always be the case in WCP, include that as a part of the StorageReady condition check. There is little point in letting the VM creation flow get past this point since we will be able to create the VM.
There is some future that will make this optional for certain VMs so we're not going to enforce this in the webhook at the moment. There is also future UX improvement here: we don't allow the storage class to change - this will also be relaxed in the future - so the only way out of this is to delete the k8s VM resource and recreate it with the intended storage class. We could use the presence of this condition to allow it to be changed.
Remove API doc mentioning this field being defaulted when there is a sensible default, pushing this to …

🌱 Include required storage class in StorageReady condition

---

go.mod
go.sum
pkg/manager/manager.go
test/builder/fake.go

This change imports VPC API from https://github.com/vmware-tanzu/nsx-operator/tree/vpc_dev/pkg/apis/nsx.vmware.com/v1alpha1 and adds types to k8s client scheme.
Fixes N/A
```release-note
Import VPC API from nsx-operator
```

:sparkles: Import VPC API from nsx-operator

---

api/v1alpha2/sysprep/sysprep.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go

This change adds validations and updates logonCount description to say must be specified
when AutoLogon is true.
Fixes # N/A
https://learn.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-shell-setup-autologon-logoncount
```
Update AutoLogonCount description to say must be specified when AutoLogon is true
```

🌱 Add validation for autoLogonCount and update description

---

webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_unit_test.go

This change adds default network interface `SubnetSet` when VPC Network in VM mutation webhook. 
Fixes N/A
We don't need to determine the network type/name because VPC will pick a namespace default(SubnetSet with the label `nsxoperator.vmware.com/default-subnetset-for: VirtualMachine`)
Testing done: when deployed a VM under VPC network without specifying network, default network interface is added.
```
Network:
Interfaces:
Name:  eth0
Network:
API Version:  nsx.vmware.com/v1alpha1
Kind:         SubnetSet
Name:
```
**Please …

:sparkles: Add default NetworkInterface when VPC network

---

api/v1alpha2/virtualmachineimage_types.go
pkg/vmprovider/providers/vsphere2/contentlibrary/content_library_utils.go
pkg/vmprovider/providers/vsphere2/contentlibrary/content_library_utils_test.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go

For images that have the special ExtraConfig field, set the V1Alpha1Compatible condition like v1a1 did, and update the EC field when using the v1a1 OvfEnv transport converts to in v1a2.  The very old v1a1 ExtraConfig transport is not really supported anymore since we don't allow CloudInit with vAppConfig.
Note that the V1Alpha1Compatible thing is the only reason we need the image post VM create. We cannot set the EC field to "Enabled" at create time since the OVF ExtraConfig takes precedence over conflicting keys in our ConfigSpec. A future change may remove the need for the image and we'll just set the EC field if it is there and "Ready" to "Enabled" since
Do some clean up in UpdateConfigSpecExtraConfig() by using our various util functions.
Remove an InstanceStorage ExtraConfig test …

🐛 Add back the V1Alpha1Compatible image condition to v1a2

---

api/v1alpha2/virtualmachine_network_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml

When we're doing inlined Sysprep, if set, the HostName field is what we set as the Computer Name. For ease, just pass this value as-is since internally GOSC does the same. If it becomes pressing later, we can try to do some up front validation.
Since GOSC passes this value as-is through w/o validation have us just do the same. Which multibyte characters are allowed or not makes that slightly annoying and I just don't think worth it.
```release-note
NONE
```

📖 Note that HostName is used as Windows Computer Name

---

webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go

Like the existing v1a1 prober methods we only support at most one of the methods being specified but GuestInfo was missing from the validation.
Add a quick test that includes GuestInfo in the old style test until we can convert everything over from the big "args" format.
```release-note
NONE
```

🐛 Check for GuestInfo prober exclusivity in validation webhook

---

test/builder/vcsim_test_context.go

This change updates vcsim test frame for VPC networking. Specific e2e tests will be added after implementation is done.
Fixes N/A
NONE

:sparkles: Update vcsim test frame for VPC networking

---

api/v1alpha1/virtualmachine_conversion.go
api/v1alpha1/virtualmachine_conversion_test.go

This is more correct since Bootstrap.CloudInit was non-nil to start with, and correctly handles the case when just SSHAuthorizedKeys is set.
Not a common CloudInit use case but by setting the v1a1 VMMetaData transport on down convert, we'll correctly restore the Bootstrap when up converting to v1a2.
```release-note
NONE
```

🐛 Always set v1a1 CloudInit transport when v1a2 is using CloudInit

---

pkg/util/configspec.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap_cloudinit_test.go

If the VM already has the expected vAppConfig - either no vAppConfig or already has the OvfEnvironmentTransport - depending on the type of CloudInit we're doing, then don't update the ConfigSpec. If something fails after the reconfigure, we'd otherwise create needless no-op Reconfigure tasks.
```release-note
NONE
```

🐛 Only update CloudInit ConfigSpec if updates are required

---

config/rbac/role.yaml
controllers/virtualmachine/v1alpha2/virtualmachine_controller.go
pkg/vmprovider/providers/vsphere2/constants/constants.go
pkg/vmprovider/providers/vsphere2/network/network.go
pkg/vmprovider/providers/vsphere2/network/network_test.go
pkg/vmprovider/providers/vsphere2/network/nsxt.go
pkg/vmprovider/providers/vsphere2/network/nsxt_test.go
test/builder/fake.go

In VPC mode, we should create a `SubnetPort` when it is time to do IPAM configuration for a Virtual Machine. This is very similar to the `VirtualNetworkInterface` flow of NSX-T, and similar logic should be applied to find the associated DVPG necessary.
Fixes N/A
`Subnet` and `SubnetSet` CRs are both supported as network choices if in VPC mode. But only one is supported at a time. Validation story will be a follow-up to avoid the situation both are specified.
- Testing done: 
- After deploying a VM under VPC networking …

:sparkles: Create SubnetPort when realizing VPC networking

---

pkg/vmprovider/providers/vsphere2/placement/cluster_placement_test.go
pkg/vmprovider/providers/vsphere2/placement/zone_placement_test.go
pkg/vmprovider/providers/vsphere2/vmprovider_test.go
webhooks/persistentvolumeclaim/validation/persistentvolumeclaim_validator.go
webhooks/persistentvolumeclaim/validation/persistentvolumeclaim_validator_unit_test.go
webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator_intg_test.go
webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator_unit_test.go

This is just a few cherry-picked commits from #401 that fixes v1a2 code still using v1a1 imports.
Fixes #
I'll rebase #401 after this goes in - I want to keep that MR just v1a1 code removal. Highlights the need for more refactoring so that v1a3+ isn't so invasive.
```release-note
NONE
```

🌱 Remove v1a1 imports from v1a2 code

---

api/v1alpha1/virtualmachine_conversion_test.go
api/v1alpha2/virtualmachine_network_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
pkg/vmprovider/providers/vsphere2/network/netplan.go
pkg/vmprovider/providers/vsphere2/network/netplan_test.go
pkg/vmprovider/providers/vsphere2/network/network.go
pkg/vmprovider/providers/vsphere2/network/network_test.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go

When using cloud-init this allows the device name in the guest to be set to something different that what the name is in the k8s VM and used for the corresponding network interface CR name.
This can be useful if desired device name in the guest does not conform to what k8s allows since Name field is used for part of the interface CR name.
Fixes #
```release-note
When using CloudInit for the bootstrap, the network device name in the guest can be specified with the GuestDeviceName …
```

✨ Add GuestDeviceName to network interfaces spec

---

api/v1alpha2/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
pkg/vmprovider/providers/vsphere2/vmlifecycle/bootstrap.go

In the old v1a1 code, we'd always fallback to LinuxPrep regardless if the guest was Linux or not, and we have tests that assume that behavior. Improve that here by only doing that on guests that would indicate to be some known Linux distro.
Fixes #
IDK how intentional the prior behavior was but since we have tests that assume this behavior and it is a LCD way of passing in the network config keep doing so. 
```release-note
If Bootstrap is omitted and the guest OS identifier is …
```

🌱 Only default to LinuxPrep GOSC on Linux VMs

---

pkg/vmprovider/providers/vsphere2/vmprovider_vm2_test.go

This change adds a e2e like test in vcsim env for VPC networking to better test the create-update reconcile workflow. It creates a VM with CloudInit Bootstrap and simulates successful NSX Operator reconcile to check VM conditions and NIC Backing.
FixesN/A
```release-note
Add VM create/update e2e testing for VPC networking
```

:sparkles: Add VM create/update e2e testing for VPC networking

---

api/v1alpha1/virtualmachine_conversion.go
api/v1alpha1/virtualmachine_types.go
api/v1alpha2/virtualmachine_network_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status_test.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_intg_test.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go

In VDS we have difficulty in matching up the network interfaces in our VM spec with the VM's devices. Unlike NCP/NSX-T, VDS does not generate the MAC address - we defer to VC to generate it - and an overly restrictive limitation that on VDS, the EthCard ExternalID cannot be set on device create (but can later set it via an edit). So for now, try to constrain things a bit by making our network interfaces immutable so we can depend on the device order during create.
Limit network interfaces to 10 since that is the VC limit
This is just the first small step to make this better supported. In general, multiple interfaces just wouldn't have worked in either NSX-T or VDS so limit what we can make work for now until we have more time to solve this …

✨ Make the VM network interfaces immutable

---

.golangci.yml
main.go
pkg/webconsolevalidation/server.go

This patch:
* updates the project's linter config to:
* remove some vestigial references to v1alpha1 code
* remove the linter deadline as it is no longer supported by the linter
* updates two places where `ListenAndServe` was used instead of an explicit server with a timeout
Fixes `NA`
```release-note
NONE
```

🐛 Fix linter config after rm v1a1 bits

---

pkg/util/cns.go
test/builder/util.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go

With a WaitForFirstConsumer storage class, "-wffc" is appended to the storage class name but the StorageQuotaPolicy still has just the base name so we cannot depend on those names always being the same.
Instead list all the StorageQuotaPolicys in the namespace to determine if the storage class is associated with the namespace.
When the PodVMOnStretchedSupervisor FFS is enabled, both the ResourceQuotas and StorageQuotaPolicys on non-stretched SV so drop the AZ > 1 check.
Fixes # …

🐛 Fix PodVMOnStretchedSupervisor with WFFC storage class

---

controllers/infra/configmap/infra_configmap.go
controllers/infra/configmap/infra_configmap_controller.go
controllers/infra/secret/infra_secret_controller.go
pkg/manager/cache.go
pkg/manager/manager.go
pkg/manager/test/cache_test.go
pkg/manager/test/manager_suite_test.go
test/builder/test_suite.go

This patch addresses a bug created by https://github.com/vmware-tanzu/vm-operator/pull/414 and the move to the new, built-in cache logic in Controller-Runtime v0.17.x. In adopting this logic a mistake was made regarding how the logic corresponded to bypassing the cache for certain object types. This patch fixes the issue by once again disabling the global cache for ConfigMap and Secret resources, but this time using specific caches for the infra controllers.
A new test package, pkg/manager/test, has also been created to verify that the global cache is in fact bypassed for the disabled objects.
**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …

🐛 Fix inability to get ConfigMap/Secret objs

---

controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller_intg_test.go
controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller_intg_test.go
controllers/infra/configmap/infra_configmap_controller_intg_test.go
controllers/infra/node/infra_node_controller_intg_test.go
controllers/infra/node/infra_node_controller_suite_test.go
controllers/infra/secret/infra_secret_controller.go
controllers/infra/secret/infra_secret_controller_intg_test.go
controllers/virtualmachine/v1alpha2/virtualmachine_controller_intg_test.go
controllers/virtualmachineclass/v1alpha2/virtualmachineclass_controller_intg_test.go
controllers/virtualmachinepublishrequest/v1alpha2/virtualmachinepublishrequest_controller_intg_test.go
controllers/virtualmachineservice/v1alpha2/virtualmachineservice_controller_intg_test.go
controllers/virtualmachineservice/v1alpha2/virtualmachineservice_controller_suite_test.go
controllers/virtualmachinesetresourcepolicy/v1alpha2/virtualmachinesetresourcepolicy_controller_intg_test.go
controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_intg_test.go
controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_intg_test.go
controllers/volume/v1alpha2/volume_controller_intg_test.go
webhooks/persistentvolumeclaim/validation/persistentvolumeclaim_validator_intg_test.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_intg_test.go
webhooks/virtualmachineclass/v1alpha2/validation/virtualmachineclass_validator_intg_test.go
webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator_intg_test.go
webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator_intg_test.go
webhooks/virtualmachinesetresourcepolicy/v1alpha2/validation/virtualmachinesetresourcepolicy_validator_intg_test.go
webhooks/virtualmachinewebconsolerequest/v1alpha1/validation/webconsolerequest_validator_intg_test.go
webhooks/virtualmachinewebconsolerequest/v1alpha2/validation/webconsolerequest_validator_intg_test.go

Add a note around the infra negative tests that even if the objects are reconciled the tests will still pass. Note that the default timeout for these tests is 100ms which in my local testing has been long enough for them to be reconciled when removing the objects from the Managers Cache.ByObject map.
Remove vcsim from the controller and webhook labels since these just tests against the fake VM Provider. Change the old WebConsoleRequest webhook test label to be v1alpha1.
Fixes # …

🌱 Misc updates to infra controllers and test labels

---

config/local/vmoperator/local_env_var_patch.yaml
config/wcp/vmoperator/manager_env_var_patch.yaml
controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
controllers/contentlibrary/v1alpha2/utils/constants.go
pkg/config/config.go
pkg/config/default.go
pkg/config/env.go
pkg/config/env/env.go
pkg/config/env_test.go

This PR will bring in the following changes:
1.  Adding support for WCP_TKG_Multiple_CL in the following :
a. YAML Changes
- config/local/vmoperator/local_env_var_patch.yaml
- config/wcp/vmoperator/manager_env_var_patch.yaml
b. Adding a new variable for TKGMultipleCL
-  pkg/config/config.go
-  pkg/config/default.go
-  pkg/config/env.go
-  pkg/config/env/env.go
c. Updating the variable `TKGMultipleCL` as env variable in UTs in `pkg/config/env_test.go`
2. Updating the reconcile logic in `setUpCVMIFromCCLItem` to update the labels on if the labels exists in CCLItems.
Fixes …

:sparkles: Introduce WCP_TKG_Multiple_CL FSS in vm-operator 

---

.markdownlintrc
docs/concepts/services-networking/README.md
docs/concepts/services-networking/vm-service.md
mkdocs.yml

This patch introduces documentation for the concept of VM services and networking.
Fixes #111, #112
```release-note
Documentation for services and networking
```
----
📚 Documentation preview 📚: https://vm-operator--433.org.readthedocs.build/en/433/

📖 Services and networking

---

controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller.go
pkg/util/image/image_suite_test.go
pkg/util/image/status_to_label.go
pkg/util/image/status_to_label_test.go

This patch ensures the VirtualMachineImage and ClusterVMI resources have their status.capabilities and status.osInfo fields set on the resources as labels. This behavior was already documented via the v1alpha2 APIs, but was not implemented. This change allows clients to more efficiently discover images based on labels, indexed by the API server, for information about the images' OS or capabilities.
Fixes `NA`
```release-note
NONE
```

✨ Sync VMI status to labels

---

api/v1alpha1/virtualmachine_types.go
api/v1alpha2/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml

This patch updates the `imageName` field in the VM CRD to reflect the correct resolution order from VMI to CVMI. It also includes the user-friendly image resolution done by the mutation webhook for better clarity.  
```release-note
Update VirtualMachine API doc to correct the resolving order of the imageName field.
```

📖 Update VirtualMachine CRD doc

---

config/wcp/vmoperator/cpu_resources_patch.yaml

With version conversion during certain v1a1 use cases that are Update() heavy with large VM objects this brings this brings performance back to prior values.
Some later work will split the webhook and controller deployments in to two so these limits can be finer tuned.
Fixes #
```release-note
manager container CPU limit raised from 250m to 750m
```

✨ Bump manager container CPU limit to 750m

---

pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status_test.go

6c4fbc4 introduced a few ways that we'd no longer update the VM.Status.Network if some of the moVM.Guest itself or its fields were nil.
Note that even on a powered off VM the moVM.Guest.Net.IPStacks is not empty, so as a side effect PrimaryIP{4,6} and Interfaces fields would get cleared.
Also note that we need to preserve the VM.Status.Network.Config field since that is currently only re-evaluated when the VM is powered on.
Fixes #
```release-note
NONE
```

🐛 Better clear VM.Status.Network fields

---

controllers/volume/v1alpha2/volume_controller.go
controllers/volume/v1alpha2/volume_controller_unit_test.go
pkg/context/volume_context.go
pkg/manager/cache.go

We only need to be aware of PVCs in the Volume controller because of instance storage. This feature isn't enabled in all envs, and is not that commonly used in general, so defer the costs of the Watch() until we need to do so.
Improve getInstanceStoragePVCs() to not return PVCs that did not exist. Things still worked because these PVCs would fail the IsControlledBy() check but it is clearer to just not return these PVCs in the first place.
One goal is to offset some of the memory used by the CnsNodeVmAttachment field index added in 7a6e39d.
Fixes #
**Are there any special …

🌱 Defer PVC watch in Volume controller until needed

---

docs/concepts/workloads/vm-class.md
pkg/docs/concepts/concepts_suite_test.go
pkg/docs/concepts/vm-class_test.go

This patch adds some additional documentation for VM classes, as well as a new package to supplement docs with Golang code, pkg/docs. This package includes a file for providing examples of encoded ConfigSpec structures, pkg/docs/concepts/vm-class_test.go.
Fixes `NA`
```release-note
The package pkg/docs supplements documentation with Go examples, beginning with examples of encoded ConfigSpec values.
```
----
📚 Documentation preview 📚: …

📖 Add encoded ConfigSpec examples

---

api/v1alpha1/virtualmachineservice_types.go
api/v1alpha2/virtualmachineservice_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachineservices.yaml

The underlying k8s Service field was deprecated in v1.24 and our controller just passes through the from the VirtualMachineService to the Service. Use the same deprecate message as upstream.
Fixes #
I can tweak the deprecation message to be more specific to our env/wcp instead. We'll have to update this depreciation message once we implement a single annotation that covers all our possible/supported LBs.
See https://github.com/kubernetes/kubernetes/pull/107235 for the upstream deprecation
**Please add a release note if …

Mark VirtualMachineService LoadBalancerIP as deprecated

---

docs/concepts/workloads/README.md
docs/concepts/workloads/vm-controller.md
mkdocs.yml

This patch adds a docs page for the VM controller and includes workflow diagrams for the basic VM Reconcile and Delete workflows.
There is a TODO for the ReconcileNormal workflow.
Fixes `NA`
```release-note
Initial documentation for the VM controller
```
----
📚 Documentation preview 📚: https://vm-operator--445.org.readthedocs.build/en/445/

📖 VM controller docs / workflows

---

pkg/util/configspec.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go

This patch modifies the logic for updating ExtraConfig to support powered on VMs. This ensures powered on VMs that have vGPUs will have the flag in ExtraConfig removed that DRS queries to determine whether or not to power off the VM during vMotion. This was already handled in #353, but that logic is only executed before a VM is powered on, not for currently powered on VMs.
This patch also optimizes the behavior of the UpdateEC function to only iterate over the existing EC list once.
Fixes `NA`
**Please add a release note …

✨ UpdateExtraConfig for powered on VMs, iterate list once

---

config/local-vcsim/vcsim-patch.yaml
pkg/vmprovider/providers/vsphere2/constants/constants.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm.go

Post create, I'd like us to never have to depend in the image resource existing since it may get deleted. Fix the two situations where the image was being used.
First the JSON_EXTRA_CONFIG contains RUN.container that uses a template to fill in the image name so vcsim creates a container under the covers. This was used for old local gce2e testing, and isn't used by us but some other teams have a desire to use it so keep it around. Now that is just set on create in the EC and we don't need to re-eval it later on.
Second remove the V1Alpha1Compatible condition check and always check the EC. This does change the behavior that if an image did not have the condition but had guestinfo.vmservice.defer-cloud-init=ready, we'll now always set it to …

⚠️ Remove need for VM Image in Update path

---

pkg/vmprovider/providers/vsphere2/network/network.go
pkg/vmprovider/providers/vsphere2/network/network_test.go

Going forward for new VMs, once the network interfaces are mutable and we need to reconcile the network interface CRs we can use this to quickly list all the interfaces for the VM instead of having to list all in the namespace.
Fixes #
```release-note
NONE
```

🌱 Add label to network interface CR for its VM name

---

pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go

This PR updates the `setMemoryMappedIOFlagsInExtraConfig()` function to skip if the VM is nil. This could be the case when it's called from `UpdateConfigSpecExtraConfig()` while reconciling a powered-on VM with a vGPU or DDPIO device.
Fixes #447.
```release-note
Fix UpdateConfigSpecExtraConfig() when reconciling a powered-on VM with vGPU or DDPIO device.
```

🐛 Fix UpdateConfigSpecExtraConfig() when reconciling VM with vGPU/DDPIO

---

config/wcp/vmoperator/manager_env_var_patch.yaml

This change removes the duplicate FSS_WCP_NAMESPACED_VM_CLASS FSS env var that blocking component upgrades during patch.
Fixes # N/A
Issue similar to https://github.com/helm/helm/issues/10650#issuecomment-1047660003
```NONE
```

🐛 Remove dup FSS_WCP_NAMESPACED_VM_CLASS FSS env var from manager patch

---

pkg/util/configspec.go
pkg/util/configspec_test.go
pkg/vmprovider/providers/vsphere2/placement/cluster_placement.go
pkg/vmprovider/providers/vsphere2/placement/zone_placement.go
pkg/vmprovider/providers/vsphere2/placement/zone_placement_test.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
pkg/vmprovider/providers/vsphere2/virtualmachine/configspec.go
pkg/vmprovider/providers/vsphere2/virtualmachine/configspec_test.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/create.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/create_clone.go
pkg/vmprovider/providers/vsphere2/vmlifecycle/create_contentlibrary.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go

This patch updates the way the VM ConfigSpec is handled by several util functions and the vSphere provider to be copy-by-value instead of as a pointer. This is because Golang is much more efficient at handling memory on the stack versus the heap. However, the primary reason for this patch is to change the perception of the `configSpec` variable throughout the rest of its call stack. The spec is not optional, and moving away from a pointer reinforces that notion.
Fixes `NA` …

✨ ConfigSpec by value

---

webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator.go
webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator_unit_test.go

This change fixes the validation for VirtualMachineService names to
use IsDNS1035Label. This is the right one to use since we create k8s Service objects
with the same name and they need to comply with RFC 1035.
Service Port names are validated as DNS 1123 still.
Fixes #
N/A
```NONE
```

🐛Use IsDNS1035Label for VirtualMachineService validations

---

api/v1alpha2/virtualmachine_types.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go

This change adds `PauseVMExtraConfigKey`, `PausedVMLabelKey` and `VirtualMachineReconciliationCondition` for later break glass override consumption. It also adds validation to prevent non-admin user to edit PausedVMLabelKey. This label is set by VMOP to specify what persona paused vm reconciliation.
- PauseVMExtraConfigKey = "vmservice.virtualmachine.pause"
- PausedVMLabelKey = "vmoperator.vmware.com/paused-vm", value being:
- admin
- devops
- both
- VirtualMachineReconciliationCondition = "VirtualMachineReconciliation"
- when false, reason being "VirtualMachineReconciliationPaused"
This change also fixes validation unit test to use `DescribeTable` func.
**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, …

:seedling: Add ExtraConfig Key, Label, Condition and validation for break glass override

---

.github/workflows/ci.yml
Makefile

This patch simplifies the Makefile test targets so there is now a single test target named "test". There is also a single test workflow in GitHub, reducing the duplicate tests that would run as part of the old unit/integration test division.
This patch also updates the code coverage workflow to warn if coverage falls below the minimum instead of failing the job.
Fixes `NA`
```release-note
Simplify testing with a single Makefile target named "test"
```

✨ Single test target / workflow

---

pkg/config/config.go
pkg/config/env.go
pkg/config/env/env.go
pkg/providers/vsphere/vmlifecycle/bootstrap.go
pkg/providers/vsphere/vmlifecycle/bootstrap_test.go

Some fields may contain sensitive info like passwords, so redact or nil out those fields for the specs used for logging. This is enabled by default.
This behavior can be toggled by the LOG_FULL_BOOTSTRAP_SPECS envvar.
Fixes #
I'm not in love with this opt-in field approach fwiw.
```release-note
```

 🌱 Redact sensitive fields in bootstrap config and customization specs

---

go.mod
go.sum

This patch updates the GoVmomi dependency to commit c385285, which includes a critical fix for a bug in the way GoVmomi waited for property collector updates.
Fixes `NA`
```release-note
Update GoVmomi to c385285
```

🐛 GoVmomi c385285

---

.github/workflows/ci.yml

Per [the notice](https://github.com/vmware-tanzu/vm-operator/actions/runs/8754747978?pr=474) from a previous PR's GitHub actions, this patch updates several deprecated GitHub action versions:
* actions/setup-go -- v4 --> v5
* actions/download-artifact -- v3 --> v4
* actions/upload-artifact -- v3 --> v4
* actions/cache -- v3 --> v4
Fixes `NA`
```release-note
Updates GitHub actions cache, setup-go, upload-artifact, download-artifact
```

🌱 Update deprecated GitHub actions

---

.github/workflows/ci.yml

This patch removes the distinct GitHub action for parsing the code coverage produced by the test action. Instead, the coverage logic is now handled at the end of the test action. Previously the coverage logic needed to be a distinct step since there were two, separate test jobs. However, now those are combined into one, meaning we can remove the need to upload the coverage artifact to be processed later.
Fixes `NA`
Depends on #475 
```release-note
NONE
```

🌱 Combine test and coverage actions

---

.github/workflows/gnotify.yml

This patch updates the gnotify GitHub action's setup-python step from v4 to v5.
Fixes `NA`
```release-note
NONE
```

🌱 Update gnotify setup-python action

---

pkg/prober/probe/guestinfo.go
pkg/prober/probe/guestinfo_test.go
pkg/prober/probe/probe.go
pkg/providers/fake/fake_vm_provider.go
pkg/providers/vm_provider_interface.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_test.go

This patch updates the GuestInfo prober to only fetch the properties that are part of the specified probe definition. Previously the VM's entire config.extraConfig property path was retrieved, resulting in a very expensive operation, depending on the size of the data in that property. By focusing on specific properties, the number of bytes transferred is limited to the size of the property values required to evaluate the probe. This change is possible because vSphere supports fetching property paths with indexed values. For example, instead of fetching all of config.extraConfig, an array, just to access the element with the key "hello", it is possible to fetch the property path config.extraConfig["hello"].
Additionally, this patch forgoes …

✨ GuestInfo prober fetches required props only

---

config/local/vmoperator/local_env_var_patch.yaml
config/wcp/vmoperator/manager_env_var_patch.yaml
pkg/config/config.go
pkg/config/env.go
pkg/config/env/env.go
pkg/config/env_test.go

This change introduces the FSS for the initiative that allows workload management of VMs using Kubernetes primitives such as Deployments, ReplicaSets and StatefulSets.
```release-note
Feature state switch for k8s primitive workload management APIs
```

:seedling: Introduce FSS for workload management of VMs using Kubernetes patterns

---

api/go.mod
api/v1alpha1/virtualmachine_conversion.go
api/v1alpha1/virtualmachine_conversion_test.go
api/v1alpha2/virtualmachine_conversion.go
api/v1alpha3/virtualmachine_bootstrap_types.go
api/v1alpha3/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
pkg/providers/vsphere/vcenter/getvm.go
pkg/providers/vsphere/vcenter/getvm_test.go
pkg/providers/vsphere/virtualmachine/configspec.go
pkg/providers/vsphere/virtualmachine/configspec_test.go
pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit.go
webhooks/virtualmachine/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

When creating a new VirtualMachine:
- InstanceUUID is set to VM ObjectMeta.UID
- BiosUUID is included in VirtualMachineSpec
- cloud-init metadata instance ID is set to VM spec.biosUUID
Enable find by UUID preference in vcenter.GetVirtualMachine, as it is more stable than Inventory path.

🐛 Specify BIOS and instance UUIDs when creating VM

---

api/v1alpha2/virtualmachine_types.go
api/v1alpha3/virtualmachine_types.go
controllers/virtualmachine/virtualmachine_controller.go
controllers/virtualmachine/virtualmachine_controller_intg_test.go
controllers/virtualmachine/virtualmachine_controller_unit_test.go
controllers/volume/volume_controller.go
pkg/providers/vsphere/constants/constants.go
pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/virtualmachine/delete.go
pkg/providers/vsphere/vmlifecycle/update_status.go
pkg/providers/vsphere/vmlifecycle/update_status_test.go
pkg/util/vsphere/vm/vm.go
pkg/util/vsphere/vm/vm_test.go

This change will support admins to pause VM Service VM reconciliation by adding ExtraConfig Key [PauseVMExtraConfigKey](https://github.com/vmware-tanzu/vm-operator/blob/main/api/v1alpha3/virtualmachine_types.go#L155). After admin adds EC key, VM will have label [PausedVMLabelKey](https://github.com/vmware-tanzu/vm-operator/blob/main/api/v1alpha3/virtualmachine_types.go#L162) =`admin` and `VirtualMachineReconcileReady` condition set to false, showing reason being `VirtualMachineReconcilePaused`, indicates that VirtualMachine reconciliation is being paused by Admin.
This change also patches devops pause VM workflow. DevOps add [PauseAnnotation](https://github.com/vmware-tanzu/vm-operator/blob/main/api/v1alpha3/virtualmachine_types.go#L114) to …

:sparkles: Implement admin override to pause VM reconciliation

---

webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

The mutating webhook sets the default spec.biosUUID, which validating webhook rejects for non-admin users.
Will revisit how-to re-enable privilege check, but this will get e2e tests passing again in the meantime.

🐛 Disable spec.biosUUID privilege check

---

.github/configs/labeler.yml
.github/workflows/pr-labeler.yml
.github/workflows/testing-needed.yml

This PR updates the **pr-labeler** and **testing-needed** GitHub action workflows to exclude generated files when calculating the changed lines of code (LoC).  This ensures that proper labels (size and testing-needed) are attached to a PR based on the calculated LoC.
Testing Done:
- Submitted this change to main in my fork and verified in a PR changing both generated and non-generated files: https://github.com/dilyar85/vm-operator/pull/26
- Output from the `pr-labeler` job:
```console
2024/05/02 14:27:44 Counting changes in file a/README.md
2024/05/02 14:27:44 Counting changes in file b/README.md
2024/05/02 14:27:44 Count line +
2024/05/02 14:27:44 Count line +
2024/05/02 14:27:44 Ignoring file a/api/v1alpha2/zz_generated.conversion.go …
```

🌱 Update GitHub actions to exclude generated files when checking diff

---

api/v1alpha3/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
docs/ref/api/v1alpha3.md
pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit.go
webhooks/virtualmachine/mutation/virtualmachine_mutator.go

This patch stores the Cloud-Init instance ID derived from either spec, the object UID, or the annotation, back into spec if the derived version is different than what is in spec. Additionally, the annotation that can overrride the instance ID is deleted once its value is stored in the spec.
This patch also updates some documentation to make the logic more clear, as well as provide historical context for why certain logic exists in the first place.
Fixes `NA`
```release-note
Store …
```

 🌱 Store resolved Cloud-Init instance ID in spec

---

go.mod
go.sum
pkg/providers/vsphere/network/network.go
pkg/providers/vsphere/network/network_test.go
pkg/providers/vsphere/vmprovider_vm2_test.go

This change addresses changes in https://github.com/vmware-tanzu/nsx-operator/pull/546 on SubnetPort APIs. It includes:
- vifID -> attachment.id
- logicalSwitchID -> networkInterfaceConfig.logicalSwitchUuid
- macAddress and ipAddresses move under networkInterfaceConfig
- ipAddresses.netmask goes away.
- ipAddresses.ip -> networkInterfaceConfig.ipAddresses.ipAddress becomes a CIDR format (implicit netmask)
Fixes N/A
Testing done:
- Built CSP with customized wcp-agent, ako, nsx-ujo and cayman_vmop
- Deployed vpc networking …

:seedling: Update VPC networking NSX SubnetPort APIs

---

.github/workflows/ci.yml
Dockerfile

This patch updates the GitHub workflow to build VM Operator using Golang 1.22.3. This patch also updates the project's Dockerfile to use Golang 1.22.3 as well.
Please note, the go.mod files are not updated because the project's modules do not require anything from Go 1.22. Until such time, the project *can* still be built using Go 1.21.
This patch also addresses the vulncheck errors due to https://pkg.go.dev/vuln/GO-2024-2824.
Fixes #461 
Replaces https://github.com/vmware-tanzu/vm-operator/pull/461
**Please add a release …

🌱 Go 1.22.3

---

api/v1alpha3/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
controllers/virtualmachine/virtualmachine_controller.go
controllers/virtualmachine/virtualmachine_controller_intg_test.go
pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit.go
webhooks/virtualmachine/validation/virtualmachine_validator.go

For VMs created prior to v1alpha3, populate the new fields for use with discovery and B/R:
- spec.biosUUID
- cloudInit.instanceID

:bug: Upgrade VMs for use with Instance ID Discovery

---

pkg/util/vmopv1/resize.go
pkg/util/vmopv1/resize_test.go

This annotation will be used for VM resizing to keep track of which and at what revision a VM was last resize from.
Add very basic Set/Get methods for this. This is really just to get what & how is stored in the annotation out there.
Fixes #
Just very basic get/set functions for now. This will all be built on later.
```release-note
NONE
```

🌱 Add last VM Resize annotation

---

controllers/virtualmachine/v1alpha2/virtualmachine_controller.go

Cross-port of #512 to the 8.0U3 product branch.
Fixes `NA`
```release-note
Fix requeue delay when retrying to create VM
```

🐛 Fix requeue delay if trying to create VMs (8.0U3 x-port)

---

pkg/builder/auth.go
pkg/builder/auth_test.go
pkg/builder/builder_suite_test.go

This patch updates the IsPrivilegedUser function for webhooks to support the membership in the system:masters group as signal the user is privileged. This is consistent with the Kubernetes documentation at
https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles.
This also means the integration tests in this project that depend on envtest will now access the API server as an admin.
Fixes `NA`
This blocks https://github.com/vmware-tanzu/vm-operator/pull/518 since it has a failing IT that expects the …

🌱 Support system:masters for IsPrivilegedUser

---

pkg/providers/vsphere/network/network.go

This patch supports DHCP for VPC networking. VM Operator expect SubnetPort that uses DHCP to have `Status.NetworkInterfaceConfig.MACAddress` to be empty if Subnet/SubnetSet is configured for DHCP. This is the current SubnetPort status. https://github.com/vmware-tanzu/nsx-operator/issues/559 tracks the effort to return nil ipAddress for DHCP SubnetPort.
```
networkInterfaceConfig:
ipAddresses:
- gateway: 172.26.1.193
ipAddress: /26
logicalSwitchUUID: a22d4111-e7da-4396-94b7-ee80a1c25494
```
Fixes N/A
Manual testing done on …

:sparkles: Support DHCP for VPC networking

---

config/local/vmoperator/local_env_var_patch.yaml
config/wcp/vmoperator/manager_env_var_patch.yaml

This patch fixes a bug where the FSS for the feature FSS_WCP_MOBILITY_VM_IMPORT_NEW_NET was added into pkg/config but not to the deployment YAML.
Fixes `NA`
```release-note
NONE
```

🐛 Add FSS_WCP_MOBILITY_VM_IMPORT_NEW_NET to yaml

---

controllers/virtualmachine/virtualmachine_controller.go
controllers/virtualmachine/virtualmachine_controller_intg_test.go
controllers/virtualmachine/virtualmachine_controller_suite_test.go
pkg/config/config.go
pkg/config/default.go
pkg/config/env.go
pkg/config/env/env.go
pkg/config/env_test.go

During the VM create and VM power on steps, we may need to requeue the VM for reconciliation internally. We do that via a RequeueAfter that controller runtime provides. Improve the integration test to cover these steps.
Parameterized the requeue delays values so they can be changed if needed if needed. When VM create is not blocking, and when we start to use the property.
Fixes #
```release-note
NONE
```

🌱 Add integration tests to cover VM create requeue delays

---

Makefile
api/v1alpha3/virtualmachine_types.go

This patch fixes an issue with the make generate target. Specifically, "go generate ./api/...". This used to work in Go 1.21, but it no longer works across modules in Go 1.22. This patch fixes the issue.
Fixes `NA`
```release-note
NONE
```

🐛 Fix make generate

---

hack/verify-codegen.sh

This PR fixes a bug in the verify-codegen.sh to get the actual exit code from the executed make commands. This ensures that the verify-codegen GitHub workflow job terminates with the correct exit code when the make generate commands fail.
The previous code would always capture the exit code as 0, e.g.:
```bash
if ! false; then echo "${?}"; else echo "fine"; fi;
```
would print out "0" even though the `false` command exits with `1`.
See https://github.com/vmware-tanzu/vm-operator/actions/runs/9098850495/job/25010046314?pr=519 where the `make generate` fails with an error message printed out, but the GitHub workflow was reported as successful.  …

🐛 Fix verify-codegen.sh to get exit code correctly

---

api/v1alpha1/virtualmachine_conversion.go
api/v1alpha1/virtualmachine_conversion_test.go
api/v1alpha1/zz_generated.conversion.go
api/v1alpha2/virtualmachine_conversion.go
api/v1alpha2/zz_generated.conversion.go
api/v1alpha3/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
controllers/virtualmachine/virtualmachine_controller.go
controllers/virtualmachine/virtualmachine_controller_intg_test.go
pkg/providers/vsphere/virtualmachine/configspec.go
pkg/providers/vsphere/virtualmachine/configspec_test.go
webhooks/virtualmachine/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

For VM Import, we want the desired instance UUID to match the underlying instance UUID of the VM
Note: needs #492 merged before doc update

✨ Add VirtualMachineSpec.InstanceUUID

---

pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_resize_test.go
pkg/providers/vsphere/vsphere_suite_test.go
pkg/util/resize/configspec.go
pkg/util/resize/configspec_test.go
test/builder/vcsim_test_context.go

This is just the minimal plumbing needed to go through resize when the VM is in steady-state off. Lots of supporting plumbing is still needed like handling the last resize annotation when the VM Class does not exist, and building the full ConfigSpec that includes expected network devices, but this lets us work on the end to end resize.
This also copies the existing getUpdateArgsFn hack that we have as a holdover from the old Session days that we'll likely need to clean up as we have time.
Fixes #
**Please add a release …

✨ Plumb through basic end to end resize

---

api/v1alpha3/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
pkg/providers/vsphere/vmprovider_vm_utils.go
pkg/util/vmopv1/vm.go
pkg/util/vmopv1/vm_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

This patch introduces support for VirtualMachine resources that were not originally deployed by VM Service, and therefore do not have an associated VirtualMachineImage.
Fixes `NA`
Please note that unlike #510, this change does not synthesize a fake image based on the existing VM. This is because the only time the VM Image resource is ever read is during create, IFF the VM cannot be found in the inventory. Since this never happens for imported VMs, there is never a call to `GetVirtualMachineImageSpecAndStatus`.
**Please add …

✨ Support for imageless VirtualMachine resources

---

pkg/util/image/status_to_label.go
pkg/util/image/status_to_label_test.go

These values come from the CL Item which may not be valid k8s label values. Don't try to assign the label if the value is invalid since we won't be able to update the k8s image.
Fixes #
```release-note
The VirtualMachineImage OS ID, Version, and Type labels will only be add if the corresponding values are valid Kubernetes label values.
```

🐛 Check for valid image OS image labels keys and values

---

pkg/util/resize/configspec.go
pkg/util/resize/configspec_test.go

For the fields that are either comparable or bool pointer and have an equivalent field in the ConfigInfo, compare then during resize. This is mostly just a start on how to best start comparing all the fields in the ConfigSpec/ConfigInfo.
Fixes #
```release-note
NONE
```

🌱 Compare basic ConfigSpec.Hardware fields for resize

---

pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/vmprovider_vm_resize_test.go
pkg/util/resize/configspec_test.go
pkg/util/vmopv1/resize_devops.go
pkg/util/vmopv1/resize_devops_test.go

For certain fields in the ConfigSpec, there are fields that a user can set in the VM Spec that take precedence over what is set in the VM Class ConfigSpec.
Fixes #
```release-note
NONE
```

🌱 Override resize ConfigSpec fields from VM Spec

---

pkg/providers/vsphere/client/client.go
pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/vmlifecycle/create.go
pkg/providers/vsphere/vmlifecycle/create_contentlibrary.go
pkg/providers/vsphere/vmprovider.go
pkg/providers/vsphere/vmprovider_resourcepolicy.go
pkg/providers/vsphere/vmprovider_vm.go

This patch removes the ClusterModule and ContentLibrary clients from the vSphere client. Instead, those clients are instantiated where they are used. This simplifies the dependency graph for the pkg/providers/vsphere/client package, making it easier to move towards a future without the provider model.
Fixes `NA`
```release-note
NONE
```

🌱 Remove ClusterModule & Content Library clients from vSphere client

---

Makefile
config/crd/external-crds/topology.tanzu.vmware.com_availabilityzones.yaml
config/crd/external-crds/topology.tanzu.vmware.com_vspherezones.yaml
config/default/kustomization.yaml
go.mod

This patch updates the generate-external target to always generate the topology API CRDs from externa/tanzu-topology as well as removes those same CRDs from the VM Operator infrastructure YAML. This allows a separate workflow for installing the topology APIs to a Supervisor.
Fixes `NA`
```release-note
The VM Operator infrastructure YAML no longer includes the topology APIs.
```

🌱 Generate topology API CRDs & rm from infra yaml

---

webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

This change adds validations for maximum supported hardware version in the VM spec minHardwareVersion. We will need update this everytime we pull in govmomi types that exposes a newer hardware version that VM Service can support.
Fixes # N/A
Adding kubebuilder:validations for the Maximum cannot handle create/update with brownfield API versions v1a1/a2 VMs.
```
Validate minHardwareVersion when creating or updating VMs to prevent setting field to an unsupported version.
```

🌱 Add validations to minHardwareVersion to not exceed max supported hardware version

---

.markdownlintrc
docs/tutorials/deploy-vm/with-pvc.md
mkdocs.yml

This patch provides a documentation example for how to deploy a VM with an additional disk provided by a PVC.
Fixes `NA`
```release-note
Tutorial on deploying VM with additional disk provided by PVC
```
----
📚 Documentation preview 📚: https://vm-operator--537.org.readthedocs.build/en/537/

📖 Deploy VM w additional disk from PVC

---

Makefile
hack/test.sh

This patch excludes the `./api` module from coverage. This is because there is too much generated code in the API schemas that is not able to be tested due to the way the code is generated. For example, in `./api/v1alpha2/zz_generated.conversions.go`:
```go
func RegisterConversions(s *runtime.Scheme) error {
if err := s.AddGeneratedConversionFunc((*ClusterVirtualMachineImage)(nil), (*v1alpha3.ClusterVirtualMachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
return Convert_v1alpha2_ClusterVirtualMachineImage_To_v1alpha3_ClusterVirtualMachineImage(a.(*ClusterVirtualMachineImage), b.(*v1alpha3.ClusterVirtualMachineImage), scope)
}); err != nil {
return err
}
```
There are hundreds of these in the `v1alpha1`, `v1alpha2`, …

🌱 Exclude ./api from coverage (but still test it)

---

pkg/util/ptr/ptr.go
pkg/util/ptr/ptr_test.go

This patch updates the Overwrite[T any] function from pkg/util/ptr to be more generic such that it can take pointers or primitives.
Fixes `NA`
```release-note
Update pkg/util/ptr.Overwrite[T any] to accept pointers *or* primitives.
```

🌱 Make pkg/util/ptr.Overwrite more generic

---

controllers/infra/configmap/infra_configmap.go
controllers/infra/configmap/infra_configmap_controller_intg_test.go
go.mod
pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit.go
pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit_test.go
pkg/util/cloudinit/cloudconfig.go
pkg/util/cloudinit/cloudconfig_test.go
pkg/util/cloudinit/validate/validate.go

This patch replaces all uses of `gopkg.in/yaml.v3` with `sigs.k8s.io/yaml`. This change is to ensure there is a singular convention for how objects are marshaled/unmarshled to/from YAML within VM Operator, regardless of whether they are Kubernetes runtime objects. The package `sigs.k8s.io/yaml` is in fact just a wrapper around `gopkg.in/yaml.vN`, with the additional logic of first marshaling the objects to JSON before converting them to YAML.
Fixes `NA`
```release-note
Replace …
```

🌱 Replace gopkg.in/yaml.v3 with sigs.k8s.io/yaml

---

controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_intg_test.go
controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_unit_test.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_intg_test.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_unit_test.go
controllers/contentlibrary/utils/constants.go
controllers/virtualmachine/virtualmachine_controller.go
controllers/virtualmachine/virtualmachine_controller_unit_test.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
controllers/virtualmachineservice/virtualmachineservice_controller.go
controllers/virtualmachineservice/virtualmachineservice_controller_intg_test.go
controllers/virtualmachinesetresourcepolicy/virtualmachinesetresourcepolicy_controller.go
controllers/virtualmachinesetresourcepolicy/virtualmachinesetresourcepolicy_controller_unit_test.go
test/builder/dummies.go

Finalizers on Kubernetes resources are expected to be fully qualified domain names.  API server validations had a bug where they would skip validating the format of finalizers on CRDs.  That bug: https://github.com/kubernetes/kubernetes/issues/119445 has been fixed recently in 1.29.  As a result, we are now seeing warnings for all finalizers on all resources in our controllers.
This change fixes the finalizer strings to conform to upstream standards. For now, we will have to maintain two finalizers if the controller is reconciling resources that were created by old VM operator.
```
root@42081df27b4c6563c62b6641e6fbf74d [ ~ ]# k get vm -n parunesh-ns -o=jsonpath={.items[].metadata.finalizers} | jq [
"vmoperator.vmware.com/virtualmachine"
] …
```

:bug: Update finalizers to conform to upstream standards

---

.golangci.yml

This patch updates the golangci config file to allow/deny certain imported packages based on where they are used within the project.
Fixes `NA`
```release-note
NONE
```

🌱 Lint allowed/denied packages

---

Makefile
hack/tools/go.mod
hack/tools/go.sum

This patch updates k8s.io/code-generator to 0.30.1 following the resolution of the missing "--input-dirs" flag problem in the issue https://github.com/kubernetes/code-generator/issues/172.
Fixes `NA`
```release-note
Update k8s.io/code-generator from 0.29.0 to 0.30.1
```

🌱 Update k8s.io/code-generator to 0.30.1

---

controllers/infra/configmap/infra_configmap.go
controllers/infra/configmap/infra_configmap_test.go

This patch fixes an issue reading the infra config map due to the switch to sigs.k8s.io/yaml for marshaling/unmarshaling. It uses JSON tags instead of YAML tags. A test was also added to validate this.
Fixes `NA`
```release-note
NONE
```

🐛 Fix issue reading infra config map tags

---

api/v1alpha3/virtualmachinereplicaset_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
config/rbac/role.yaml
controllers/virtualmachinereplicaset/virtualmachinereplicaset_controller.go
controllers/virtualmachinereplicaset/virtualmachinereplicaset_controller_intg_test.go
controllers/virtualmachinereplicaset/virtualmachinereplicaset_controller_suite_test.go
controllers/virtualmachinereplicaset/virtualmachinereplicaset_delete_policy.go
pkg/util/replicaset_label.go
pkg/util/replicaset_label_test.go

This commit adds support for creating, deleting and scaling a VirtualMachineReplicaSet resource.  When a VirtualMachineReplicaSet is created, it is reconciled to create the desired number of virtual machine replicas specified in its spec.
Similarly, during scale out/scale in, the controller reconciles the replicas to match the desired state by either creating or deleting VirtualMachine objects.  Note that a new replica is only created when the controller detect that it requires a new replica (as opposed to a rollout that is triggered via modification of the template spec in a Deployment).
When the VirtualMachineReplicaSet resource is deleted, all of its owned virtual machine replicas are also cleaned up.  The controller relies on the …

:sparkles: VirtualMachineReplicaSet CRUD/Scale Up Scale Down support

---

controllers/virtualmachineclass/virtualmachineclass_controller_unit_test.go

This patch increases the coverage for the VM Class controller to above 70%.
Fixes `NA`
```release-note
NONE
```

🌱 Increase coverage for VM Class controller to >70%

---

pkg/topology/availability_zones.go
pkg/topology/availability_zones_test.go

Remove unused const and errs
Remove an unnecessary check for no AZs since GetAvailabilityZones() already returns an error for that case
Make an error string consistent with others
Remove an unnecessary copy()
Fixes #
```release-note
NONE
```

🌱 Misc topology cleanup

---

controllers/virtualmachinewebconsolerequest/v1alpha1/patch/suite_test.go
controllers/virtualmachinewebconsolerequest/v1alpha1/patch/utils_test.go
pkg/patch/suite_test.go
pkg/patch/utils_test.go

This patch fixes an issue in the `pkg/patch` and `controllers/virtualmachinewebconsolerequest/v1alpha1/patch` packages. Both packages would occasionally report only `16%` coverage instead of `78%`. For example, https://github.com/vmware-tanzu/vm-operator/pull/553 showed `pkg/patch` at `78%`, whereas
https://github.com/vmware-tanzu/vm-operator/pull/552 showed it at `16%`. When the lower coverage was detected, Ginkgo did not detect any tests in the package, ex.:
```shell
Running Suite: Patch Suite - /home/runner/work/vm-operator/vm-operator/pkg/patch
================================================================================
Random Seed: 1717175300
Will run 0 of 0 specs
Ran 0 of 0 Specs in 0.000 seconds
SUCCESS! -- 0 Passed | 0 Failed | 0 …
```

🐛 Fix coverage for both patch packages

---

.github/workflows/ci.yml

This patch updates the coverage thresholds to '80 90' where 80% is the minimum threshold and 90% is the *target* floor. This patch also updates the GitHub action so that the job will fail if the coverage dips below the 80% floor.
Fixes `NA`
~~It turns out the threshold values inclusive for failure detection, despite the documentation for [`fail_below_min`](https://github.com/irongut/CodeCoverageSummary?tab=readme-ov-file#fail_below_min):~~
> Fail the workflow if the overall Line Rate is below lower threshold - true or …

🌱 Coverage thresholds; fail on below 80%

---

.github/workflows/ci.yml
Dockerfile
api/go.mod
go.mod
hack/tools/go.mod

This PR upgrades to go1.22.4 to address a vulnerability reported in the `net/netip` package (before go1.21.11, from go1.22.0-0 before go1.22.4).
Fixes https://pkg.go.dev/vuln/GO-2024-2887
Any existing PR should be rebased after this change is merged to pass the vulncheck-go GitHub Action job.
```release-note
Upgrade to go 1.22.4 version.
```

🌱 Upgrade go1.22.4 to address vulnerability GO-2024-2887

---

Makefile

This patch defaults `GOTOOLCHAIN` to `local` to use the Go version on the system and avoid downloading the one specified in the Go module. For more information on `GOTOOLCHAIN`, please see https://go.dev/doc/toolchain.
Fixes `NA`
This change _will_ force developers to have the correct Go version installed locally. For example, if Go 1.22.3 is installed and `make modules` is executed, then the following error occurs:
```shell
go: go.mod requires go >= 1.22.4 (running go 1.22.3; GOTOOLCHAIN=local)
make: *** [Makefile:253: …
```

🌱 Default GOTOOLCHAIN to LOCAL

---

pkg/util/resize/configspec.go
pkg/util/resize/configspec_test.go

This change adds support for resize when some of the fields in the configSpec are modified. Namely,
- CPU affinity
- CPU hot add and remove
- CPU latency sensitivity
- CPU perf counter (VPMC)
- CPU resource allocation
Fixes # N/A
N/A
```
Support resizing fields: CPU affinity, hot add, hot remove, latency sensitivity, perf counter, resource allocation
```

✨ Resize fields: CPU affinity, hot add, hot remove, latency sensitivity, perf counter, resource allocation

---

api/v1alpha3/virtualmachine_types.go
pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_resize_test.go
pkg/util/ptr/ptr.go
pkg/util/ptr/ptr_test.go
pkg/util/resize/configspec.go
pkg/util/vmopv1/resize.go
pkg/util/vmopv1/resize_devops.go
pkg/util/vmopv1/resize_devops_test.go
pkg/util/vmopv1/resize_test.go

This includes most of the infra around resize so that most of the remaining work is just being able to build the full resize Reconfigure ConfigSpec.
Improve the handling of user/devops fields by only updating the resize ConfigSpec if the current value - as from the ConfigInfo - is different.
Fixes #
```release-note
NONE
```

✨ Handle VM Class Resize annotations

---

pkg/util/resize/configspec.go
pkg/util/resize/configspec_test.go

This change supports resize of the VM's extra config settings when the class has differing key/value pairs.
Fixes #N/A
N/A
```
Support extra Config resize
```

✨ Resize ExtraConfig

---

cmd/web-console-validator/main.go
pkg/webconsolevalidation/server.go
pkg/webconsolevalidation/server_test.go

This patch increases the code coverage for the `pkg/webconsolevalidation` package from 51 to 100%.
```console
$ ./hack/test.sh ./pkg/webconsolevalidation
...
PASS
coverage: 100.0% of statements
composite coverage: 100.0% of statements
```
Fixes `NA`
```release-note
NONE
```

🌱 Increase coverage for web-console-validation server from 51-->100%

---

pkg/util/resize/configspec.go
pkg/util/resize/configspec_test.go

This is some low hanging fruit needed to replace the pre-power on reconfigure with resize.
The behavior of these fields is a little different than others: only potentially update them if it is currently unset.
Fixes #
```release-note
NONE
```

🌱 Resize Annotation and ManagedBy fields

---

pkg/providers/vsphere/vmprovider.go
pkg/providers/vsphere/vmprovider_test.go
pkg/providers/vsphere/vsphere_suite_test.go
test/builder/vcsim_test_context.go

This patch updates the vSphere VM provider to return early when syncing VM Image content for non-OVF type library items. This avoids unnecessary VC calls to fetch files when reconciling non-OVF type images (e.g. ISO).  
This patch also adds some tests to verify the existing `SyncVirtualMachineImage` function, aiming to increase the overall coverage for `pkg/providers/vsphere`.
Fixes N/A
N/A.
```release-note
Skip syncing VMI content for non-OVF type content library items.
```

🌱 Skip syncing VMI content for non-OVF type content library items

---

docs/ref/api/v1alpha2.md
docs/ref/api/v1alpha3.md

I missed running `generate-api-docs` when adding the VirtualMachineReplicaSet APIs.  As a result, the markdown docs haven't been updated.  This change fixes that.
```release-note
NONE
```
----
📚 Documentation preview 📚: https://vm-operator--580.org.readthedocs.build/en/580/

:book: Sync VirtualMachineReplicaSet API docs generated from CRDs

---

pkg/providers/vsphere/virtualmachine/configspec.go
pkg/providers/vsphere/virtualmachine/configspec_test.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/util/ensure_disk_controller.go
pkg/util/ensure_disk_controller_test.go

This patch adds a function for ensuring all disks in a ConfigSpec point to a valid controller.
Fixes #
```release-note
NONE
```

🐛 EnsureAllDisksPointToController

---

pkg/util/resize/configspec.go
pkg/util/resize/configspec_test.go

Support resizing a VM with the Virtual Machine ConfigSpec's console preferences setting.
Fixes #N/A
N/A
```
Support resizing VMs with console preferences settings
```

✨ Resize Console Preferences

---

api/v1alpha1/virtualmachine_conversion.go
api/v1alpha1/virtualmachine_conversion_test.go
api/v1alpha1/zz_generated.conversion.go
api/v1alpha2/virtualmachine_conversion.go
api/v1alpha2/virtualmachine_conversion_test.go
api/v1alpha2/zz_generated.conversion.go
api/v1alpha3/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
docs/concepts/workloads/vm.md
docs/ref/api/v1alpha3.md
pkg/providers/vsphere/resources/vm.go
pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/session/session_vm_update_test.go
pkg/providers/vsphere/virtualmachine/backup.go
pkg/providers/vsphere/virtualmachine/configspec.go
pkg/providers/vsphere/virtualmachine/configspec_test.go
pkg/providers/vsphere/vmlifecycle/bootstrap.go
pkg/util/vmopv1/network.go
pkg/util/vmopv1/network_test.go
pkg/util/vsphere/vm/guest_id.go
pkg/util/vsphere/vm/guest_id_test.go
pkg/util/vsphere/vm/suite_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

This PR includes the following changes:
- A new `vm.spec.guestID` API in v1alpha3 and related conversion in v1alpha1 and v1alpha2.
- Also add the missing instanceUUID conversion in v1a1
- Doc updates for this new API.
- Deploy a VM with `configSpec.guestID` if it's set in the VM Spec.
- Reconfigure a VM with the updated guestID (different from VM's ConfigInfo) before powering it on.
- Disallow updating `vm.spec.guestID` if a VM is powered on.
- Tests to cover all the above implementations. 
Depending on if a VM has been created, the VM's condition will be updated when an unsupported guestID is specified:
- If the VM has not yet been created, the `VirtualMachineCreated` condition will be marked as false with a message indicating an invalid …

✨ Add vm.spec.guestID API and its implementation

---

pkg/util/resize/configspec.go
pkg/util/resize/configspec_test.go

If the flag is set, Common CBRC (Content Based Read Cache) digest cache is enabled for the virtual machine.
Common CBRC cache is shared between the hot added disks in the VM
Fixes # N/A
N/A
```
Resize CBRC Cache Enabled
```

✨Resize Flags: CBRC Cache Enabled

---

controllers/virtualmachineservice/providers/loadbalancer_provider.go
controllers/virtualmachineservice/providers/loadbalancer_provider_test.go
controllers/virtualmachineservice/virtualmachineservice_controller.go

This patch adds the NCP TCP protocol annotation to Services.Type=LB if the health check port is specified.
Fixes `NA`
```release-note
Add "ncp/healthCheckProtocol": tcp to Services.Type=LB annotations if a health check port is specified for VirtualMachineServices when the network topology is NCP.
```

🌱 Add NCP protocol annotation if NCP port health check

---

pkg/providers/vsphere/vmprovider_vm_utils.go
pkg/providers/vsphere/vmprovider_vm_utils_test.go

The v1a1 VM Metadata (Bootstrap) didn't have a field to specify the CM or Secret key for the CloudInit userdata. In v1a2, we added a Key field, and that field is required so on version convert we use "user-data". However, that key - or any user data - may not exist in the CM or Secret and the user may only want to provide the default user SSH public keys, allow that to succeed.
Fixes #585 
Workaround is to just add "user-data" to the CM or Secret Data
```release-note
A VM created …
```

🐛 Fix v1a1 CloudInit with no user-data only ssh public keys

---

pkg/util/resize/configspec.go
pkg/util/resize/configspec_test.go
webhooks/virtualmachine/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go

VMs prior to the resize feature will not have the last-resize annotation that we will set on new VMs at create time. When the ClassName changes set the last-resized annotation so we'll evaluate a resize when the VM powerstate allows.
Add a quick for a braino and last second refactor that caused us to match all devices instead of just PCI passthru devices. I need to do some more clean up and refactoring of the tests to make this more natural to test.
Fixes #
```release-note
NONE …
```

🌱 Resize Brownfield VMs

---

pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/session/session_vm_update_test.go
pkg/providers/vsphere/virtualmachine/backup.go
pkg/providers/vsphere/virtualmachine/backup_test.go
pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit.go
pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit_test.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_test.go
pkg/util/configspec.go
pkg/util/configspec_test.go
pkg/util/option_values.go
pkg/util/option_values_test.go
pkg/util/resize/configspec.go

This patch introduces the type OptionValues in "pkg/util". This new type simplifies working with []vimtypes.BaseOptionValue properties such as ExtraConfig.
@dougm , it occurs to me after writing this ... should this just be in GoVmomi?
Fixes #570
Please note there are _two_ commits for this PR:
1. The actual business logic.
2. A patch where the files affected from the previous patch have their `pkg/util` packages imported according to the correct rules as `pkgutil`. 
This enables reviewers to focus on the business logic …

🌱 OptionValues helper

---

controllers/virtualmachineservice/providers/loadbalancer_provider.go
controllers/virtualmachineservice/providers/loadbalancer_provider_test.go
controllers/virtualmachineservice/virtualmachineservice_controller.go

This reverts commit 8905a4c8117437d4ebd4313115073dfe3c6ead5f, reversing changes made to 50afa4dcbbf610c7b48e24dcd7e7aea98238d625.
According to @DanielXiao:
> Previously some changes were made on on NCP for LB healthcheck and we were asked to use `"ncp/healthCheckNodePort": "6443"` if we want to enable LB healthcheck on kube-apiserver. During POC, we found vm-operator manage this annotation with VMService annotation `"virtualmachineservice.vmoperator.vmware.com/service.healthCheckNodePort"` but a HTTP healthcheck is created unexpectedly because lack of the NCP protocol annotation `"ncp/healthCheckProtocol": "tcp"`.
>
> Then we requested you to add this annotation. This is actually a feature regression because annotation …

🐛 Revert "Merge pull request #584 from akutz/feature/vmsvc-ncp-health-check"

---

pkg/util/option_values.go
pkg/util/option_values_test.go
pkg/util/vmopv1/resize_devops.go
pkg/util/vmopv1/resize_devops_test.go

The MMIO memory size can be set via an annotation on the VM, that then results in two entries being added to the VM's ExtraConfig.
Fixes #
Another small step to replacing the pre power on reconfigure with resize.
```release-note
NONE
```

🌱 Support MMIO ExtraConfig during resize

---

pkg/util/resize/configspec.go
pkg/util/resize/configspec_test.go

This change supports the resize of some boolean configSpec fields namely
-FixedPassthruHotPlugEnabled
-NestedHVEnabled
-SevEnabled
-VmxStatsCollectionEnabled
Fixes # N/A
N/A
```
Support resize of FixedPassthruHotPlugEnabled, NestedHVEnabled, SevEnabled, VmxStatsCollectionEnabled
```

✨ Resize Miscellaneous bool configSpec fields

---

pkg/util/resize/configspec.go
pkg/util/resize/configspec_test.go

Support reconfiguring VMs with the Memory Reservation Locked to Max. Additionally, this change makes sure that the setting cannot be accidentally set to false when the desired config spec has PCI passthrough devices
Fixes # N/A
N/A
```
Support resize of Memory Reservation Locked to Max
```

✨Resize: Memory Reservation Locked to Max

---

pkg/util/resize/configspec.go
pkg/util/resize/configspec_test.go

This PR adds support for resizing GMM (guest monitoring mode) and encrypted vMotion modes
Fixes # N/A
N/A
```
Resize Guest Monitoring Mode and Encrypted vMotion modes
```

✨ Resize: Guest Monitoring (GMM) and Encrypted vMotion modes

---

pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_utils.go

This field was being assigned twice in the create VM workflow. While here, don't set the field for classless VMs: the Kind and Name fields of the ref would be empty in that case, and a little misleading to set the field for VMs without.
Fixes #
```release-note
NONE
```

🌱 Remove duplicate VM.Status.Class assignment

---

controllers/volume/volume_controller.go

Only log while waiting for the VM to be created - as determined by the Status.BiosUUID being set - if the VM has volumes.
Fixes #
```release-note
NONE
```

🌱 Reduce Volume controller log spam while creating VMs

---

pkg/config/config.go
pkg/config/default.go
pkg/config/env.go
pkg/config/env/env.go
pkg/config/env_test.go

This patch introduces a placeholder FSS for the Unified Storage Quota work, FSS_PLACEHOLDER_WCP_UNIFIED_STORAGE_QUOTA.
Fixes `NA`
```release-note
NONE
```

🌱 Placeholder FSS for Unified Storage Quota

---

pkg/util/resize/configspec.go
pkg/util/resize/configspec_test.go

Change adds support for resizing N_Port ID Virtualization settings for the VM.
Fixes # N/A
VMware doc on NPIV: https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-storage/GUID-E05D5E0A-89A3-4948-8F61-F86A84128446.html
```
Support resize of NPIV settings
```

✨Resize N_Port ID Virtualization settings

---

api/v1alpha3/virtualmachine_types.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_test.go

This change adds the vCenter annotation on the VirtualMachine custom resource.  Among other things, this annotation can be used to determine whether a VM is being restored on the same vCenter where it was originally created.
```release-note
Add vCenter UUID annotation on the VM
```

🌱 Add the vCenter UUID annotation on the VM

---

.github/workflows/ci.yml
Dockerfile
api/go.mod
go.mod
hack/tools/go.mod

Go 1.22.5 is required to addresses the vulncheck errors due to https://pkg.go.dev/vuln/GO-2024-2963.
```
Vulnerability #1: GO-2024-2963
Denial of service due to improper 100-continue handling in net/http
More info: https://pkg.go.dev/vuln/GO-2024-2963
Standard library
Found in: net/http@go1.22.4
Fixed in: net/http@go1.22.5
```
Fixes https://pkg.go.dev/vuln/GO-2024-2963
None.
```release-note
Upgrade VM Operator to golang 1.22.5
```

🌱 Go 1.22.5

---

pkg/util/resize/configspec.go
pkg/util/resize/configspec_test.go

vSphere doesn't support legacy console preferences anymore. Hence, VM service doesn't have to.
Fixes # N/A
N/A
```
Remove Resize Console Preferences support as vSphere doesn't support it.
```

🌱 Remove resize console preferences

---

pkg/providers/vsphere/virtualmachine/configspec.go
pkg/util/configspec.go
pkg/util/configspec_test.go

The VM Class specified guestID is not supported. Ignore if set.
The guestID is either specified explicity by
- the VM spec (or)
- falls back to the VM Image/OVF
Fixes # N/A
N/A
```
Ignore VM Class provided guestID
```

🐛  Ignore VM Class specified default guestID "otherGuest64"

---

api/v1alpha1/zz_generated.conversion.go
api/v1alpha2/virtualmachineimage_conversion.go
api/v1alpha2/zz_generated.conversion.go
api/v1alpha3/virtualmachineimage_types.go
config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_unit_test.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_unit_test.go
docs/ref/api/v1alpha3.md

This PR introduces a new `type` field in v1alpha3 VM image status and displays it in the kubectl output print columns.  
This enables users to quickly check the image type without fetching the corresponding content library item from the image CR.
```console
$ kubectl get vmi -n sdiliyaer-test
NAME                    DISPLAY NAME                                  TYPE   IMAGE VERSION   OS NAME                 OS VERSION   HARDWARE VERSION   CAPABILITIES
vmi-59d0c8cad9fa84376   centos-stream-8-vmservice-v1alpha1.20210528   OVF                    centos8_64Guest         8            17
vmi-613b445de62052870   ubuntu-23.10-live-server-amd64                ISO
$ kubectl get cvmi
NAME                    DISPLAY NAME …
```

🌱 Add image type in VirtualMachineImage and ClusterVirtualMachineImage status

---

controllers/virtualmachine/virtualmachine_controller.go
controllers/virtualmachine/virtualmachine_controller_unit_test.go

In the recent changes to support the break-glass admin overrides, we changed the behavior of the pause annotation for regular (non delete) reconciles so that we now _always_ add the finalizer regardless of the pause annotation.
This change fixes this by reverting the old behavior of returning early if the pause annotation is present.  This also means that now both reconcile methods (Create/Update and Delete) behave consistently when this annotation is present.
```release-note
Revert to returning early if the pause annotation is present on the VM
```

:bug: Revert to returning early if the pause annotation is present on the VM

---

pkg/providers/vsphere/virtualmachine/configspec.go
pkg/providers/vsphere/virtualmachine/configspec_test.go

UnitNumber is required for PlaceVmsXCluster w/ VpxdVmxGeneration fss enabled

🐛 Set VirtualDisk.UnitNumber when placing with multiple clusters

---

test/builder/dummies.go
webhooks/virtualmachine/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

This PR adds required webhook code to mutate and validate a VM with the `vm.spec.cdrom` field as listed below:
- [Mutation] Add default CD-ROM name and image kind if not provided.
- [Mutation] Set VM's image name from CD-ROM image name if the former is not provided.
- [Validation] Disallow creating (or updating when the VM is powered off) multiple CD-ROMs with duplicate image backing.
- [Validation] Disallow adding/removing/updating CD-ROM when the VM is powered on (except for changing connection state only).
Fixes N/A.
- Manually verified all the above cases in an internal testbed with this PR deployed.
- Updated the VM mutation and validation …

✨ Update VM mutating/validating webhook related to CD-ROM spec

---

pkg/providers/vsphere/vmprovider_vm_resize_test.go
pkg/util/vmopv1/resize.go
pkg/util/vmopv1/resize_test.go

Allow an existing VM to be synced to the class that is currently points to when the opt-in annotation is present.
Fixes #
```release-note
NONE
```

🌱 resize: support same class annotation on brownfield VMs

---

.gitignore
config/crd/external-crds/cns.vmware.com_storagepolicyquotas.yaml
config/crd/external-crds/cns.vmware.com_storagepolicyusages.yaml
config/rbac/role.yaml
controllers/controllers.go
controllers/storagepolicyquota/storagepolicyquota_controller.go
controllers/storagepolicyquota/storagepolicyquota_controller_suite_test.go
controllers/storagepolicyquota/storagepolicyusage_controller_intg_test.go
controllers/storagepolicyquota/storagepolicyusage_controller_unit_test.go
pkg/util/kube/gvk.go
pkg/util/kube/spq.go
pkg/util/kube/spq_test.go

This patch adds the controller that creates StoragePolicyUsage resources for StoragePolicyQuota resources applied to namespaces.
Fixes #
```release-note
StoragePolicyQuota controller creates StoragePolicyUsage resources for tracking VM usage
```

🌱 StoragePolicyQuota controller

---

pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/vmlifecycle/update_status.go
pkg/providers/vsphere/vmlifecycle/update_status_test.go
pkg/providers/vsphere/vmprovider_vm_resize_test.go

After a resize update the VM Status.Class to reflect the updated class that was just applied.
Fixes #
```release-note
NONE
```

🌱 resize: update VM Status.Class after resizing

---

api/v1alpha3/virtualmachine_types.go

Currently, we will unconditionally try to register a VM when it is restored using a backup/restore vendor, or a DR solution.  This isn't always ideal if the solution wants to prepare the infra, or customize the VM on vSphere before registering the VM with Supervisor.
This change introduces an ExtraConfig key that can be used to opt-out of the automatic registration workflow.
```release-note
Introduce the ExtraConfig key to allow opt-out from auto register
```

:seedling: Introduce the ExtraConfig key to allow opt-out from auto register

---

pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_test.go

The storage policy datastore query is only needed for ISO images.

🐛 Only set vmPathName when using ISO image

---

pkg/providers/vsphere/network/network.go
pkg/providers/vsphere/network/network_test.go

To accommodate NSX Operator's newly introduced `ExternalAddressBinding` CR, which is to associate an External IP to a VM that will eventually associate an external IP to subnet port. Their ask is for VM Operator to provide interface name in `VPCAttachmentRef`.
Fixes N/A
This change needs to be merge around the same time NSX Operator merges their change.
```release-note
NONE
```

:seedling: Include both vm_name and interface_name in VPCAttachmentRef

---

pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_resize_test.go
pkg/util/resize/configspec.go
pkg/util/resize/configspec_test.go

Add support for resize of just CPU & memory. For ease, this was just made a part of the existing pre-power on reconfigure flow, while the full resize has its own path that will eventually replace the former.
Fixes #
```release-note
VirtualMachine resize of just CPU and Memory.
```

✨ resize: VM resize of just CPU and Memory

---

pkg/providers/vsphere/vmlifecycle/bootstrap.go

This PR skips the default LinuxPrep bootstrap if a VM is deployed from ISO (i.e., having a CD-ROM attached). This avoids VM deployment errors when the Linux ISO-type image doesn't have vmtools installed.
Fixes N/A.
**Are there any special notes for your reviewer**
Manually deployed a Linux ISO-type VM with this change in an internal testbed and verified the VM is powered on successfully without the default customization applied.
```release-note
Skip default LinuxPrep bootstrap for ISO VM deployment.
```

🌱 Skip default LinuxPrep bootstrap for ISO VM deployment

---

api/v1alpha3/virtualmachine_types.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_test.go
pkg/util/annotations/helpers.go
pkg/util/annotations/helpers_test.go

Today, we have certain exclusion rules in place that govern whether or not we persist the configuration of VirtualMachine in the ExtraConfig for use by backup/restore or disaster recovery solutions.  However, there might be cases where an entity wants to explicitly opt into backup.
This change introduces an annotation that can be placed on the VirtualMachine resource that lets VM operator skip the exclusion checks when determining whether or not to store the VM's config in ExtraConfig.
```release-note
Introduce an annotation for unconditional opt into backup
```

:seedling: Introduce an annotation for unconditional opt into backup

---

api/v1alpha2/virtualmachine_types.go
api/v1alpha3/virtualmachine_types.go
pkg/providers/vsphere/vmlifecycle/update_status.go
pkg/providers/vsphere/vmlifecycle/update_status_test.go
pkg/providers/vsphere/vmprovider_vm_resize_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go

If a resize is pending - likely because the VM is powered on and either the VM Spec.ClassName has been updated or the opt-in annotation is present and the class itself has changed - report that in a condition.
Fixes #
```release-note
NONE
```

🌱 resize: add condition to indicate if resize is available

---

pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/vmprovider_vm_resize_test.go

This defers updating the VMs configuration of these fields to the pre-power on reconfigure like it currently done today. The power off resizing will only care about CPU and memory until we enable full resizing.
Fixes #
```release-note
NONE
```

🌱 resize: Remove DevOps overrides from CPU/Memory resize

---

api/v1alpha1/virtualmachine_conversion.go
api/v1alpha1/virtualmachine_conversion_test.go
api/v1alpha2/virtualmachine_conversion_test.go
config/rbac/role.yaml
controllers/virtualmachine/virtualmachine_controller.go
go.mod
go.sum
pkg/manager/manager.go
pkg/providers/vsphere/network/network.go
pkg/providers/vsphere/network/network_test.go
pkg/providers/vsphere/vmprovider_vm2_test.go
test/builder/fake.go
webhooks/virtualmachine/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go

For tenant manager support, there is a design to support APIService for VPC, and the plan is to use APIGroup `nsx.vmware.com`. So NSX Operator decided to change VPC CRDs APIGroup to `crd.nsx.vmware.com`. What affects VMOP is:
- securitypolicies.crd.nsx.vmware.com
- subnets.crd.nsx.vmware.com
- subnetsets.crd.nsx.vmware.com
- subnetports.crd.nsx.vmware.com
Fixes N/A
It will go after https://github.com/vmware-tanzu/nsx-operator/pull/638 with updated imported api.
```release-note …
```

🌱 Change APIGroup for VPC

---

pkg/providers/vsphere/placement/zone_placement_test.go
pkg/providers/vsphere/vcenter/folder_test.go
pkg/providers/vsphere/vcenter/getvm_test.go
pkg/providers/vsphere/vcenter/resourcepool_test.go
pkg/providers/vsphere/vmprovider_resourcepolicy_test.go
pkg/providers/vsphere/vmprovider_vm2_test.go
pkg/providers/vsphere/vmprovider_vm_resize_test.go
pkg/providers/vsphere/vmprovider_vm_test.go
test/builder/vcsim_test_context.go

This patch updates vcsim tests when WCP_Workload_Domain_Isolation enabled. 
- Updated `CreateWorkloadNamespace` to create namespaced Zone CR when FSS enabled.
- Test both FSS enabled/disabled for `zone_placement_test.go`.
- Test only FSS enabled for `folder_test.go`, `vmprovider_resourcepolicy_test.go` ect because they only cares `nsInfo.Namespace` during tests.
Fixes # N/A
```release-note
NONE
```

:seedling: Update vcsim tests under WCP_Workload_Domain_Isolation

---

controllers/controllers.go

This patch puts the StoragePolicyQuota controller behind the UnifiedStorageQuota FSS. This prevents an issue with the controller that is addressed in PR #643. This patch is a stop-gap to fix an issue on main breaking testbeds while the buggy version of this controller, which should not yet be enabled, is enabled by default due to the lack of the FSS.
Fixes `NA`
```release-note
NONE
```

🐛  Put StoragePolicyQuota controller behind FSS

---

pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/session/session_vm_update_test.go
pkg/util/vsphere/vm/cdrom.go
pkg/util/vsphere/vm/cdrom_test.go
pkg/util/vsphere/vm/suite_test.go
test/builder/dummies.go
test/builder/vcsim_test_context.go

This patch updates the CD-ROM reconciliation workflow to ensure the ISO-type library item is synced, which is required to connect a CD-ROM that's backed by such an item from a subscribed content library.
To save data storage, the sync is only triggered when the CD-ROM has a "connected" spec and the backing content library file is not cached.
The `cdrom_test.file` has been updated to maintain 100% coverage:
```console
$ go test -coverprofile=/tmp/coverage.out -run ^TestVSphereVirtualMachine$ github.com/vmware-tanzu/vm-operator/pkg/util/vsphere/vm
ok  	github.com/vmware-tanzu/vm-operator/pkg/util/vsphere/vm	102.026s	coverage: 86.1% of statements
$ go tool cover -func=/tmp/coverage.out | grep …
```

🐛 Sync subscribed ISO library item before connecting CD-ROM

---

config/local/vmoperator/local_env_var_patch.yaml
config/wcp/vmoperator/manager_env_var_patch.yaml

This patch adds the FSS_STORAGE_QUOTA_M2 env var to the VM Op manifests that allows the value to be plumbed through from other components.
Fixes `NA`
```release-note
Add FSS_STORAGE_QUOTA_M2 to manifests
```

🌱 Add FSS_STORAGE_QUOTA_M2 to manifests

---

docs/concepts/workloads/guest.md

b2c80d5fef added the v1a3 template fields and functions
Fixes #
```release-note
Update docs to reference the v1alpha3 prefixed template functions and fields
```
----
📚 Documentation preview 📚: https://vm-operator--652.org.readthedocs.build/en/652/

 📖 Update vApp template function names for v1a3

---

docs/concepts/workloads/vm.md

In v1a2+ these enums became capitalized
Fixes #
```release-note
Update capitalization of v1alpha2 and later power state related enums
```
----
📚 Documentation preview 📚: https://vm-operator--653.org.readthedocs.build/en/653/

📖 Update docs for v1a2+ power state enums

---

pkg/providers/vsphere/constants/constants.go
pkg/providers/vsphere/resources/vm.go
pkg/providers/vsphere/session/session.go
pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/session/session_vm_update_test.go
pkg/providers/vsphere/virtualmachine/configspec.go
pkg/util/resize/configspec.go
pkg/util/resize/configspec_test.go
pkg/util/vmopv1/resize_overwrite.go
pkg/util/vmopv1/resize_overwrite_test.go
pkg/util/vsphere/vm/guest_id.go
pkg/util/vsphere/vm/guest_id_test.go

This patch does three things:
1. The VM object's namespace and name are stored in ExtraConfig as the keys `vmservice.namespace` and `vmservice.name`.
2. The VM's vSphere property `config.managedBy` is _always_ set to reflect the VM is managed by VM Service if it is not set to this value.
3. There is now support for *always* ensuring certain properties are set during each reconcile, regardless of the VM's power state or whether or not the VM is paused by the admin. For example, the aforementioned namespace/name ExtraConfig keys are included, as well as the VM's `config.managedBy` property.
**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when …

✨ Perennial properties

---

pkg/providers/vsphere/constants/constants.go
pkg/providers/vsphere/virtualmachine/configspec.go
pkg/util/vmopv1/resize_overwrite.go
pkg/util/vmopv1/resize_overwrite_test.go

This patch updates the ExtraConfig properties `vmservice.namespace` and `vmservice.name` to be a single field, `vmservice.namespacedName`. This simplifies watching for changes based on this property.
Fixes `NA`
```release-note
NONE
```

🌱 Update vmservice.namespace|name to be single field

---

pkg/prober/probe/guestinfo.go
pkg/prober/probe/guestinfo_test.go
pkg/providers/vsphere/vmprovider_vm_test.go

This patch updates the GuestInfo prober to correctly treat ExtraConfig properties retrieved by their key index as OptionValue types instead of thinking their value is returned directly.
Additionally, tests that use vC Sim have been added for the provider's GetVMProperties function that validate the new assumption about retrieving indexed ExtraConfig keys.
Fixes `NA`
```release-note
Fix bug (ish) with GuestInfo prober that incorrectly treated indexed keys as strings instead of …
```

🐛 ExtraConfig keys as OptionVals when getting props / prober

---

.golangci.yml
controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller_unit_test.go
pkg/context/operation/operation_context.go
pkg/context/operation/operation_context_test.go
pkg/context/operation/operation_suite_test.go
pkg/providers/vsphere/resources/vm.go
pkg/providers/vsphere/session/session_vm_update_test.go
pkg/providers/vsphere/virtualmachine/backup.go
pkg/providers/vsphere/virtualmachine/backup_test.go
pkg/providers/vsphere/vmlifecycle/create.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/util/vsphere/vm/power_state.go
test/builder/unit_test_context.go

This patch adds support for emitting distinct events for VM create/ update operations, whether successful or otherwise.
Fixes `NA`
```release-note
Creating/updating a VM now results in CreateSuccess, CreateFailure, UpdateSuccess, and UpdateFailure events.
```

✨ Emit distinct create/update VM events

---

api/v1alpha3/virtualmachine_types.go
pkg/providers/vsphere/virtualmachine/backup.go
pkg/providers/vsphere/virtualmachine/backup_test.go
pkg/providers/vsphere/vmprovider_vm.go
test/builder/vcsim_test_context.go

This change
- Introduces a new annotation and an extraConfig Key to track the latest backup-version
- The backup version is a monotonically increasing number which uses the time.Now().Unix() method.
- Skip backup when backupVersion drift is detected (ie) backup version annotation > current backup extraConfig version. This indicates a restore being tried. backup will retry until the drift is fixed by a registration.
- Do backup when backupVersion annotation doesn't exist (or) when backupVersion and current backup extraconfig keys match (or) backup version annotation < extraConfig backup version.
- Update and persists a new version when a change is detected during each backup.
- Testing for the above.
**Which issue(s) is/are addressed by this …

✨ Implement Backup-version for Incremental Restore support

---

controllers/virtualmachine/volume/volume_controller.go
controllers/virtualmachine/volume/volume_controller_unit_test.go

This fix prevents ":detaching" from being appended to the names of volumes being detached from VMs more than once.
This bug could account for rapid memory growth in VM Operator. For example, see this [Go playground](https://go.dev/play/p/q55HeO1oMHw):
```golang
package main
import (
"fmt"
"unsafe"
)
func sizeOfStr(s string) uintptr {
return uintptr(len(s)) + unsafe.Sizeof(s)
}
func main() {
name := "my-volume"
for i := 0; i < 1000; i++ {
fmt.Printf("i=%d, len=%d, sizeof=%d\n", i, len(name), sizeOfStr(name))
name = name + ":detaching"
}
}
```
By the end of this program's execution, we see:
```
i=997, len=9979, sizeof=9995
i=998, len=9989, sizeof=10005
i=999, len=9999, sizeof=10015
```
Thus, a volume detaching `N` times would take up `N*10` …

🐛 Stop adding ":detaching" to volumes more than once

---

pkg/providers/vsphere/placement/zone_placement.go
pkg/providers/vsphere/placement/zone_placement_test.go
pkg/topology/availability_zones_test.go
test/builder/dummies.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

This patch handles Zones that are being deleted. We don't want to allow new VMs to be created in zones that are being deleted.
- If VM deployment specifies a zone that is being deleted by SSO user, validation webhook will reject the creation.
- If VM deployment specifies a zone that is being deleted by admin, validation webhook will allow the creation.
- If VM deployment specifies a valid zone at create time, zone got deletionTimestamp later, still place it in the zone.
- For placement, filter out the to be deleted zones so we don't have it as a candidate.
Fixes # N/A …

🌱 Handle zones that are being deleted under WCP_Workload_Domain_Isolation

---

api/v1alpha1/virtualmachine_conversion.go
api/v1alpha2/virtualmachine_conversion.go
api/v1alpha3/virtualmachine_types.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
pkg/providers/vsphere/session/session_vm_update.go
pkg/util/annotations/helpers.go
pkg/util/annotations/helpers_suite_test.go
pkg/util/annotations/helpers_test.go

This change renames the "pause-reconcile" annotation used to pause the reconciliation of a VM to "paused".  This is consistent with other components using "paused" to indicate an entity being paused.
Additionally, introduce a helper package that can be used to check if an annotation is present (regardless of the value) in a readable way.
**Testing Done:**
1. Create a VM on v1alpha3 version with `paused` annotation set.
```
{
"key": "vmoperator.vmware.com/paused",
"value": "something"
}
```
2. Ensure that the VM doesn't have `pause-reconcile` annotation set
```
#
```
3. Fetch the resource at v1alpha2 and v1alpha1 version and ensure that the `pause-reconcile` annotation is set.
```
{
"key": "vmoperator.vmware.com/pause-reconcile",
"value": …
```

:seedling: Rename the pause-reconcile annotation to paused

---

api/backup/backup.go

Now that we are moving to an opt-in vs opt-out workflow for automatic registration, introduce an ExtraConfig key that allows VMs to participate in this workflow.
Eventually, we will remove the disableAutoRegistration ExtraConfig key once all references have been ported over to this key.
```release-note
Introduce ExtraConfig key for enable automatic registration
```

✨ Introduce ExtraConfig key for enable automatic registration

---

pkg/providers/vsphere/resources/vm.go
pkg/providers/vsphere/vmlifecycle/bootstrap.go
pkg/providers/vsphere/vmlifecycle/bootstrap_vappconfig.go
pkg/providers/vsphere/vmlifecycle/bootstrap_vappconfig_test.go
pkg/util/configspec.go
pkg/util/configspec_test.go

This patch fixes a panic that occurs when the vimtypes JSON encoder is used to log a ConfigSpec that includes a field of type interface set to a pointer w a nil value. This patch:
* Prevents the issue discovered in the `GetOVFVAppConfigForConfigSpec` to `GetMergedvAppConfigSpec` code path
* Adds support for `SafeConfigSpecToString` as a function that can be used to prevent this from ever happening again.
Fixes `NA`
```release-note
Do not panic when logging ConfigSpec that …
```

🐛 Fix panic when logging ConfigSpec w nil iface pointer

---

main.go
pkg/manager/manager.go
pkg/manager/options.go

controller-runtime can be configured to start the pprof server so use that instead of our own code.
Fixes #
```release-note
NONE
```

🌱 Use controller-runtime built-in pprof server

---

controllers/infra/capability/infra_capability_controller.go
controllers/infra/capability/infra_capability_controller_suite_test.go
controllers/infra/capability/infra_capability_controller_unit_test.go
pkg/manager/cache.go

We want capabilities updates to be reflected in the non-leader pod as well so the webhooks are aware of the current enabled capabilities.
Remove the VMProvider from the infra capability controller. It was not used, and we don't want it on the non-leader pods due to VC session limits (and it would need the other infra controllers to be non-leader as well to pick up cred rotations)
Fixes #
```release-note
NONE
```

🐛 Start infra capability controller for non-leader pods too

---

go.mod
go.sum
pkg/manager/manager.go
pkg/providers/vsphere/network/network.go
pkg/providers/vsphere/network/network_test.go
pkg/providers/vsphere/vmprovider_vm2_test.go
test/builder/fake.go
webhooks/virtualmachine/mutation/virtualmachine_mutator.go

It consumes the latest VPC APIs. Their API directory path got finalized after code review, updated as below: https://github.com/vmware-tanzu/nsx-operator/tree/main/pkg/apis/vpc/v1alpha1
Fixes #N/A
```release-note
NONE
```

:seedling: Update VPC APIs to latest version

---

pkg/providers/vsphere/virtualmachine/backup.go
pkg/providers/vsphere/virtualmachine/backup_test.go

Vendor's partial restore (e.g. single disk) method may create a new, non-FCD disk. The restored disk has new UUID and lives the the VM's directory, not the fcd/ directory. Given that FCD disk names are unique, we consult the backup data to compare using `FileName` before `Uuid`.

🐛 Handle disk backing changes when backing up PVCDiskData

---

api/v1alpha3/virtualmachine_types.go
pkg/providers/vsphere/virtualmachine/backup.go
pkg/providers/vsphere/virtualmachine/backup_test.go

This change indicates the status of the latest backup as a condition on the VM resource to inform the latest backup.
Fixes # N/A
Any suggestions for naming the condition welcome
```
Add condition to indicate the status of latest backup
```

🌱 Introduce condition to indicate the status of latest backup

---

pkg/providers/vsphere/session/session.go
pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/session/session_vm_update_test.go
pkg/providers/vsphere/vmlifecycle/update_status.go
pkg/providers/vsphere/vmlifecycle/update_status_test.go
pkg/providers/vsphere/vmprovider_vm.go

We can save one RT in every reconcile since we have to fetch the VM properties anyways until we can really fix this old session code.
Update the session tests to use the same properties selector that is used in the prod code. For the short term update the sessions tests to use Summary.Runtime instead of Runtime for the power state. Longer term it would be better for these tests to not conflate the selector used for UpdateVirtualMachine() input and test assertions.
Fixes #
GetVMClusterComputeResource() was called enough to …

Use ResourcePool field out of the VM properties

---

pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/virtualmachine/cdrom.go
pkg/providers/vsphere/virtualmachine/cdrom_test.go
pkg/providers/vsphere/virtualmachine/delete.go
pkg/providers/vsphere/virtualmachine/extraconfig.go
pkg/providers/vsphere/virtualmachine/extraconfig_test.go
pkg/providers/vsphere/virtualmachine/virtualmachine_suite_test.go
pkg/util/vsphere/vm/vm.go
pkg/util/vsphere/vm/vm_suite_test.go
pkg/util/vsphere/vm/vm_test.go

This patch removes the package imports from util/vsphere/vm that reference the VM Op API or Kubernetes code. The package util/vsphere/vm is meant to be pure vSphere code, and should never reference anything related to Kubernetes.
Fixes `NA`
```release-note
NONE
```

🌱 Refactor VM Op imports out of util/vsphere/vm

---

Makefile
hack/build-container.sh

This patch adds support for using podman instead of docker. If podman is detected, it will be used in place of docker to build images as well as bring up Kind clusters.
Fixes `NA`
```release-note
Support Podman
```

🌱 Support podman

---

controllers/virtualmachine/volume/volume_controller.go
controllers/virtualmachine/volume/volume_controller_intg_test.go

Even if a VM has pause annotation set, we end up reconciling the volumes of a VM.  This results in volumes being detached from paused VMs.  This change fixes that behavior by returning early if the paused annotation is found on the VM.
```release-note
Do not reconcile volumes if VM has pause annotation set
```

:bug: Do not reconcile volumes if VM has pause annotation set

---

go.mod
go.sum

VPC APIs have made below changes so VMOP needs to update as well. Per my evaluation, these changes don't affect VMOP. All CRD changes are merged to NSX Operator v4.2.0 branch(for VC main).
- VPCNetworkConfiguration change: https://github.com/vmware-tanzu/nsx-operator/commit/a627525885a153833ac506e563d837fffbccedf3
- SubnetPort change: https://github.com/vmware-tanzu/nsx-operator/commit/567ccf01634d1b1b69a12950bbbbfae47b669cab
- Subnet/SubnetSet change: https://github.com/vmware-tanzu/nsx-operator/commit/4e4decd56d10720d662eb4e23c78e2eeec65a363
- IPAddressAllocation change: https://github.com/vmware-tanzu/nsx-operator/commit/b4c6c00303d5852e896c7e7cd2f99c81df059cc5
**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue …

:seedling: Update VPC APIs to latest v4.0.2

---

pkg/context/generic/generic_context.go
pkg/context/generic/generic_context_test.go
pkg/context/generic/generic_suite_test.go
pkg/context/operation/operation_context.go
pkg/context/operation/operation_context_test.go
pkg/context/operation/operation_suite_test.go
pkg/providers/vsphere/virtualmachine/backup.go
pkg/util/kube/cource/cource_context.go
pkg/util/kube/cource/cource_context_test.go

This patch introduces a generic context that may be used to quickly create context implementations that can share information up and down the call stack. The `cource` and `operation` contexts have been refactored to use the new generic context.
Fixes `NA`
```release-note
NONE
```

🌱 Generic context

---

pkg/providers/vsphere/vmprovider_vm.go

This change fixes the backup version to use time in milliseconds since a backup can happen within the same second.
Fixes # N/A
N/A
```
NONE
```

🌱 Change Backup version to use UnixMilli()

---

webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

Currently, we allow imageless VM creation when importing a VM is supported.  However, after a VM is restored by a VADP based vendor or a DR solution, the destination vCenter and Supervisor might not be the same as the primary.  As such, any references to images might be stale.
This change modifies the existing code to allow imageless VMs if the VM operator supports restoring into existing VMs.
```release-note
Allow imageless VM creation when Incremental Restore FSS is enabled
```

Allow imageless VM creation when Incremental Restore FSS is enabled

---

pkg/providers/vsphere/virtualmachine/backup.go
pkg/providers/vsphere/virtualmachine/backup_test.go

Persisting last-applied-config annotation and managed fields could doubles the size of the strings we are handling during backup.  Drop those when recording backup.
Fixes N/A.
- Updated unit tests to reflect this change and also verified backup data in an internal testbed:
```console
$ kubectl get vm -n sdiliyaer-test test-vm -o yaml --show-managed-fields
apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachine
metadata:
annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"vmoperator.vmware.com/v1alpha1","kind":"VirtualMachine","metadata":{"name":"test-vm","namespace":"sdiliyaer-test"},"spec":{"className":"best- …
```

🌱 Drop managedFields and last-applied-config annotation from backup

---

api/v1alpha3/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
docs/ref/api/v1alpha1.md
docs/ref/api/v1alpha2.md
docs/ref/api/v1alpha3.md

This PR updates the guestID values link to the latest vSphere 8.0U3 version and adds the mapping to the required hardware versions.
It also updates the `cdrom.connected` doc to call out unmounting the device before disconnection, as noted in the linked [KB article](https://knowledge.broadcom.com/external/article?legacyId=2144053).
Fixes N/A.
This PR will address some of the issues reported in internal system tests.
```release-note
Update guest ID and cdrom.connected API docs.
```
----
📚 Documentation preview 📚: https://vm-operator--702.org.readthedocs.build/en/702/

🌱 Update guest ID and cdrom.connected API docs

---

.github/workflows/ci.yml
Dockerfile
api/go.mod
go.mod
hack/tools/go.mod

Go 1.22.7 is required to addresses the CI vulncheck error reported in https://pkg.go.dev/vuln/GO-2024-3106.
```console
Vulnerability #1: GO-2024-3106
Stack exhaustion in Decoder.Decode in encoding/gob
More info: https://pkg.go.dev/vuln/GO-2024-3106
Standard library
Found in: encoding/gob@go1.22.5
Fixed in: encoding/gob@go1.22.7
Example traces found:
Error:       #1: test/builder/test_suite.go:299:10: builder.TestSuite.Register calls ginkgo.RunSpecs, which eventually calls gob.Decoder.Decode
```
Fixes https://pkg.go.dev/vuln/GO-2024-3106.
N/A.
```release-note
Upgrade VM Operator to golang 1.22.7
```

🌱 Go 1.22.7

---

.github/workflows/ci.yml
Dockerfile
api/go.mod
go.mod
hack/tools/go.mod

This reverts commit 9652755c88c0fd41581aa7b561b2ea13a3dd3eed.
Going back to Go 1.22.5 until we have a release cayman-go branch internally with 1.22.7. We will need to live with the vulncheck error until then. 
Fixes # N/A
Waiting to see if we can get a cayman_go release branch with 1.22.7 sooner. DO NOT MERGE this PR until then
```
NONE
```

Revert "Go 1.22.7" back to "Go 1.22.5"

---

.github/workflows/ci.yml
Dockerfile
api/go.mod
go.mod
hack/tools/go.mod

This reverts commit d802316f6228cf8a4b80ceffc17829adf2954ef2.
Re-introduce Go 1.22.7 changes
Fixes # N/A
Waiting for cayman_go 1.22.7 to be merged
```
Update Go 1.22.7
```

Re-introduce Go 1.22.7

---

controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
controllers/virtualmachineservice/virtualmachineservice_controller.go
pkg/manager/cache.go
pkg/manager/manager.go
pkg/providers/vsphere/network/network.go

This patch adds support for stripping managed fields for objects entering the cache. The controller-runtime [documentation for this transformer](https://github.com/kubernetes-sigs/controller-runtime/blob/38546806f2faf5973e3321a7bd5bb3afdbb5767d/pkg/cache/cache.go#L350-L362) states:
> If you are not explicitly accessing managedFields from your code, setting this as `DefaultTransform` on the cache can lead to significant reduction in memory usage.
as well as the PR, https://github.com/kubernetes-sigs/controller-runtime/pull/2791, which states:
> There are no known issues when using this as a `DefaultTransform` unless there is explicit code to access objects `ManagedFields` and can lead to a significant reduction in memory usage.
Given that VM …

✨ Strip managed fields for cached objects

---

pkg/util/kube/predicates.go

This patch updates the VM Class predicate used by the VM controller to match if the class cannot be found due to the name being empty.
Fixes `NA`
```release-note
Do not filter VMs with empty class names in VM Class predicate
```

🐛 Match VMs if class name is empty in predicate

---

go.mod
pkg/providers/vsphere/virtualmachine/configspec.go
pkg/providers/vsphere/virtualmachine/configspec_test.go
pkg/util/ensure_disk_controller.go
pkg/util/ensure_disk_controller_test.go

Some VC placement changes now require the disks to have unit number assigned so update EnsureDisksHaveControllers()  to do that.
Fixes #
```release-note
NONE
```

🐛 Have EnsureDisksHaveControllers() alloc unit numbers

---

pkg/providers/vsphere/network/nsxt.go

With the effort of rebranding `NSX-T` to `NSX`, this change uses `NSX` in error messages instead of `NSX-T`. I didn't change any internal facing wording.
Fixes #N/A
```release-note
NONE
```

:seedling: Rebrand NSX-T to NSX

---

webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

CAPV needs to be able to provision VMs in draining zones prior to the zone being deleted.
Since TKG is now managed via kapp it does not have a well-known NS so we cannot hard code the service account name like we do with other accounts. This check does not need to be fool proof in the sense that this is advisory and everything in the zone is eventually going to be deleted.
Fixes #
```release-note
NONE
```

🌱  Allow CAPV to still create VMs in draining zones

---

.github/workflows/ci.yml

`gcr.io/cluster-api-provider-vsphere` project has been deleted. Temporarily disabling jobs while this image finds a new home
```
/usr/bin/podman run --rm -t -v "$(pwd)":/build:ro gcr.io/cluster-api-provider-vsphere/extra/shellcheck
Trying to pull gcr.io/cluster-api-provider-vsphere/extra/shellcheck:latest...
Error: initializing source docker://gcr.io/cluster-api-provider-vsphere/extra/shellcheck:latest: unable to retrieve auth token: invalid username/password: denied: Project cluster-api-provider-vsphere has been deleted.
make: *** [Makefile:258: lint-shell] Error 125
``` …

:seedling: Temporarily disable markdown & shell lint jobs

---

config/local/vmoperator/local_env_var_patch.yaml
config/wcp/vmoperator/manager_env_var_patch.yaml
pkg/config/config.go
pkg/config/env.go
pkg/config/env/env.go
pkg/config/env_test.go

This change adds the feature state switch for WCP Simplified Enablement to vm operator.
This is a precursor to a change which will have vm-operator web console use an API Server DNS name to login in instead of a virtual IP if a load balancer is not provided. However, we want for this change to be FSS guarded.
This reopens https://github.com/vmware-tanzu/vm-operator/pull/713, which had to be closed due to a CLA issue.
Fixes #
```release-note
```

🌱 Add FSS_WCP_SIMPLIFIED_ENABLEMENT

---

api/v1alpha2/sysprep/conversion/v1alpha2/sysprep_conversion.go
api/v1alpha2/sysprep/conversion/v1alpha3/sysprep_conversion.go
api/v1alpha2/virtualmachine_conversion_test.go

This patch fixes an NPE when doing conversion between v1a2 and v1a3 VMs that have partial inline sysprep configs.
Fixes `NA`
```release-note
NONE
```

🐛 Fix NPE when converting partial inline sysprep

---

pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/vmprovider_vm_resize_test.go
webhooks/virtualmachine/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go

Guard the CPU/Memory limited resize by the ResizeNeeded() check. Note that we're only covering CPU/Memory specific resizing here: the other UpdateFoo() were previously there, and this seems the best compromise when having to switch from full resize to hacking in the CPU/Memory limited resize in the old Session update path.
Reorg the resize specific vm_provider tests to better group related tests, and reduce some magic numbers.
Fixes #
```release-note
NONE
```

🐛 Only CPU/Memory resize when actually needed

---

api/v1alpha1/virtualmachineclass_conversion.go
api/v1alpha1/virtualmachineclass_conversion_test.go
api/v1alpha2/virtualmachineclass_conversion.go
api/v1alpha2/virtualmachineclass_conversion_test.go
api/v1alpha3/virtualmachineclass_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml

This patch updates the VM Class's reserved slots value to zero or a positive integer.
Fixes `NA`
```release-note
NONE
```

🌱 Restrict VM Class reserved slots >=0

---

pkg/providers/vsphere/virtualmachine/backup.go
pkg/providers/vsphere/virtualmachine/backup_test.go

When recording PVC disk data for the backup, we added code that first checks disks by their filenames first before falling back to using UUIDs.  This was done to support partial (disk only restore).
Since partial restore no longer relies on the PVC disk data, we no longer need to do this.  The current code also has a side effect of not handling disks restored with a new PVC name.
This effectively reverts the commit: c3a0c36.
```release-note
Do not fall back to using filenames for PVC disk backup
```

:seedling: Do not fall back to using filenames for PVC disk backup

---

webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator.go
webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_intg_test.go
webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_suite_test.go
webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_unit_test.go
webhooks/unifiedstoragequota/webhooks.go
webhooks/webhooks.go

Defines a new webhook server to act as the plug-in endpoint for the unified storage quota management admission webhook
Fixes #
```release-note
Support the unified storage quota extension service
```

:sparkles: Define new unified storage quota management plugin webhook

---

api/v1alpha1/virtualmachine_conversion.go
api/v1alpha1/virtualmachine_conversion_test.go
api/v1alpha2/virtualmachine_conversion.go
api/v1alpha2/virtualmachine_conversion_test.go

- SetAnnotation() after pause annotation rename from v1a1/a2 <-> a3.
- Also adds an additional test for v1a1ConfigMapAnnotation being set
Fixes # N/A
N/A
```
NONE
```

🌱 SetAnnotation() after pause annotation rename conversion

---

api/v1alpha3/virtualmachineimage_types.go
controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
controllers/contentlibrary/utils/utils.go
pkg/util/image/status_to_label.go
pkg/util/image/status_to_label_test.go

This PR adds image type info as labels to VMI & CVMI objects so that they can be filtered by label selector from the client side. It also updates the `SyncStatusToLabels` function to remove any labels if the values from image status is empty or invalid.
Fixes N/A.
- Added tests to maintain 100% coverage:
```console
ok  	github.com/vmware-tanzu/vm-operator/pkg/util/image	0.481s	coverage: 100.0% of statements
```
- Deployed the change to an internal testbed and verified expected labels in both VMI and CVMI objects:
```console
$ kubectl get cvmi -o json | jq '.items[] | {"image.vmoperator.vmware.com/type": …
```

🌱 Add image type label in VMI and CVMI objects

---

api/v1alpha3/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
docs/ref/api/v1alpha3.md
pkg/providers/vsphere/session/session_vm.go
pkg/providers/vsphere/session/session_vm_update_test.go
pkg/providers/vsphere/vmlifecycle/create_clone.go

This PR updates the `bootDiskCapacity` reconciliation process to skip resizing boot disks for ISO VMs since they're managed by PVCs. It also updates the API docs to reflect this behavior.
Fixes N/A.
We're not enforcing this via webhook to minimize changes to the current ISO workflow. A future release may introduce this enforcement or add support for resizing ISO VM boot disks.
```release-note
Skip resizing ISO VM boot disk and update API docs.
```
----
📚 Documentation preview 📚: https://vm-operator--732.org.readthedocs.build/en/732/

🐛 Skip resizing ISO VM boot disk

---

config/rbac/role.yaml
controllers/infra/controllers.go
controllers/infra/validatingwebhookconfiguration/validatingwebhookconfiguration_controller.go
controllers/infra/validatingwebhookconfiguration/validatingwebhookconfiguration_controller_intg_test.go
controllers/infra/validatingwebhookconfiguration/validatingwebhookconfiguration_controller_suite_test.go
controllers/infra/validatingwebhookconfiguration/validatingwebhookconfiguration_controller_unit_test.go
controllers/storagepolicyquota/storagepolicyquota_controller.go
controllers/storagepolicyquota/storagepolicyquota_controller_intg_test.go
controllers/storagepolicyquota/storagepolicyquota_controller_unit_test.go
controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
pkg/util/kube/spq/spq.go
pkg/util/kube/spq/spq_test.go

Add ValidatingWebhookConfiguration controller to watch vm-operator's ValidatingWebhookConfiguration for changes and update the CA Bundle of any StoragePolicyUsage accordingly.
Fixes #
```release-note
Allow Storage Quota Extension Service to communicate with Storage Quota webhook
```

:sparkles: Add ValidatingWebhookConfiguration controller

---

config/local/vmoperator/local_env_var_patch.yaml
config/wcp/vmoperator/manager_env_var_patch.yaml
controllers/infra/zone/zone_controller.go
pkg/util/vsphere/watcher/watcher.go
pkg/util/vsphere/watcher/watcher_context.go
pkg/util/vsphere/watcher/watcher_context_test.go

This patch removes the lock from the vm watcher, making it more performant and safer since the lock is no longer held when closing the watcher and/or adding/removing references, during which network requests can be made. There is no need for a lock anymore since the vim objects are not set to nil when the watcher is closed. They will still be garbage collected when the watcher itself goes out of scope.
This patch also explicitly defines the `ASYNC_SIGNAL_DISABLED` env var in the deployment YAML to make it clear how to disable this feature.
Fixes `NA`
**Are there any …

🌱 Remove lock on vm watcher

---

config/webhook/kustomization.yaml
config/webhook/storage_quota_webhook_configuration.yaml

This PR adds a ValidatingWebhookConfiguration to allow the storage quota webhook to be called upon create/update of virtual machines
Fixes #
```release-note
NONE
```

:seedling: Add ValidatingWebhookConfiguration for storage quota webhook

---

config/rbac/role.yaml
controllers/virtualmachine/virtualmachine/virtualmachine_controller.go

Otherwise results in CLBO with FSS_WCP_VMSERVICE_BYOK=true due to:
> Failed to watch *v1alpha1.EncryptionClass:... encryptionclasses.vmencryption.vmware.com is forbidden

🐛 BYOK: Add vm controller permission for watching encryptionclasses

---

config/crd/external-crds/encryption.vmware.com_encryptionclasses.yaml
config/rbac/role.yaml
controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
external/byok/api/v1alpha1/doc.go
external/byok/api/v1alpha1/groupversion_info.go

This patch updates the API group of the EncryptionClass API to be `encryption.vmware.com`.
Fixes `NA`
```release-note
NONE
```

🌱 Change EncryptionClass API group

---

config/default/kustomization.yaml

This patch is an addendum to the change that updated vmencryption to encryption.
Fixes #
```release-note
NONE
```

🌱 Import correct encryption CRD in kustomize

---

api/v1alpha3/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
docs/ref/api/v1alpha3.md
webhooks/virtualmachine/validation/virtualmachine_validator.go

This PR updates the API doc for the `crypto.encryptionClassName` field to reflect the validation logic in the VM webhook, which requires an encrypted storage class when this field is set. It also adds a comment in the webhook code explaining why the error is returned on `encryptionClassName` even though the validation checks the storage class.
Fixes N/A.
We should probably return both fields in the validating webhook result once K8s supports combining field errors.
```release-note
Clarify storage class requirement for crypto.encryptionClassName API
```
----
📚 Documentation preview 📚: …

📖 Clarify storage class requirement for crypto.encryptionClassName API

---

go.mod
go.sum
pkg/vmconfig/crypto/crypto_reconciler_post_test.go

This patch fixes how the crypto error processor handles errors that are not, or whose trees do not include, vim faults, by pulling in https://github.com/vmware/govmomi/pull/3594.
Fixes `NA`
```release-note
NONE
```

🐛 Fix panic when crypto err does not include fault

---

api/v1alpha2/virtualmachine_types.go
api/v1alpha3/virtualmachine_types.go
pkg/providers/vsphere/vmlifecycle/update_status.go
pkg/providers/vsphere/vmprovider_vm_resize_test.go

We may have other configuration - such as disk encryption - that is handled separately and don't want to confuse that with this condition.
The prior name would be better used as a roll up if we ever need that.
Fixes #
```release-note
NONE
```

🌱 Rename resize related condition to ClassConfigurationSynced

---

config/certmanager/certificate.yaml
config/crd/kustomization.yaml
config/crd/patches/cainjection_in_clustervirtualmachineimages.yaml
config/crd/patches/cainjection_in_virtualmachineclasses.yaml
config/crd/patches/cainjection_in_virtualmachineimages.yaml
config/crd/patches/cainjection_in_virtualmachinepublishrequests.yaml
config/crd/patches/cainjection_in_virtualmachinereplicasets.yaml
config/crd/patches/cainjection_in_virtualmachines.yaml
config/crd/patches/cainjection_in_virtualmachineservices.yaml
config/crd/patches/cainjection_in_virtualmachinesetresourcepolicies.yaml
config/crd/patches/cainjection_in_virtualmachinewebconsolerequests.yaml
config/default/kustomization.yaml
config/default/manager_auth_proxy_patch.yaml
config/default/manager_leader_election_id_patch.yaml
config/default/manager_webhook_patch.yaml
config/local-vcsim/kustomization.yaml
config/local/kustomization.yaml
config/local/vmoperator/kustomization.yaml
config/rbac/auth_proxy_service.yaml
config/replacements/kustomization.yaml
config/wcp-no-configmap/kustomization.yaml
config/wcp/kustomization.yaml
config/wcp/vmoperator/kustomization.yaml
config/wcp/vmoperator/service_metrics_port_patch.yaml
config/web-console-validator/web_console_validator.yaml
config/webhook/kustomization.yaml
config/webhook/service.yaml
config/webhook/webhookcainjection_patch.yaml

This patch updates the use of Kustomize to no longer use the deprecated symbols, ex. vars, patchesStrategicMerge, and patchesJson6902. These have been replaced with replacements and patches (respectively).
Fixes `NA`
To validate this I ran `make kustomize-local` and applied it to a local Kind cluster to ensure the YAML was valid. I also ran the same on `main` and compared the results to the PR:
```shell
diff -u config/local/infrastructure-components-original.yaml config/local/infrastructure-components.yaml
```
```diff
--- …
```

🌱 Remove use of deprecated kustomize symbols

---

pkg/util/kube/crypto.go
pkg/util/kube/crypto_test.go
pkg/util/kube/storage.go
webhooks/virtualmachine/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_suite_test.go

This patch updates the VirtualMachine mutation webhook to set the default EncryptionClass on VMs when the StorageClass supports encryption and a default EncryptionClass is available in the VM's namespace.
Fixes `NA`
```release-note
NONE
```

🌱 Set default EncryptionClass on VM when available

---

Makefile

This patch (re)introduces support for the Makefile targets kustomize-wcp and kustomize-wcp-no-configmap.
Fixes `NA`
```release-note
Support Makefile target kustomize-wcp
```

🌱 Support kustomize-wcp

---

.github/workflows/ci.yml
Makefile
hack/deploy-local-certmanager.sh
hack/deploy-local.sh

This patch adds support for a GitHub action that verifies the WCP manifests by deploying a Kind cluster and ensuring the WCP manifests can be applied to the cluster successfully.
Fixes `NA`
Verified on my fork at https://github.com/akutz/vm-operator/actions/runs/11386366887/job/31678406635.
```release-note
Add GitHub action to verify the WCP manifests
```

🌱 GitHub action to verify WCP manifests

---

controllers/virtualmachine/volume/volume_controller.go
controllers/virtualmachine/volume/volume_controller_intg_test.go
controllers/virtualmachine/volume/volume_controller_unit_test.go
pkg/providers/vsphere/constants/constants.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

This patch includes two changes:
1. The first change removes the validation that prevents PVCs from being attached to VMs that are encrypted with `spec.crypto.encryptionClassName`.
2. The second change ensures Instance Storage PVCs created on behalf of VMs using BYOK will have the annotation `encryption.vmware.com/encryption-class-name` set to the value of the VM's `spec.crypto.encryptionClassName` field. This annotation on the PVC allows CSI to know which `EncryptionClass` to use to encrypt the volume.
Fixes `NA`
**Please …

✨ Support PVCs with BYOK

---

pkg/providers/vsphere/session/session_vm_update_test.go
pkg/providers/vsphere/virtualmachine/cdrom.go
pkg/providers/vsphere/virtualmachine/cdrom_test.go
test/builder/dummies.go

This PR updates the CD-ROM reconciliation to verify image's ready condition before retrieving ISO backing files. This prevents mounting unready ISO files to VMs. Also moving this logic into a separate function for better code readability.
Fixes N/A.
- Added new unit tests to maintain 100% code coverage of the `cdrom.go` file:
```console
$ go tool cover -func=/tmp/coverage.out | grep pkg/providers/vsphere/virtualmachine/cdrom.go
github.com/vmware-tanzu/vm-operator/pkg/providers/vsphere/virtualmachine/cdrom.go:33:			UpdateCdromDeviceChanges			100.0%
github.com/vmware-tanzu/vm-operator/pkg/providers/vsphere/virtualmachine/cdrom.go:118: …
```

🌱 Check image ready condition before mounting ISO

---

pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_test.go
pkg/vmconfig/crypto/crypto_reconciler.go
pkg/vmconfig/crypto/crypto_reconciler_post.go
pkg/vmconfig/crypto/crypto_reconciler_post_test.go
pkg/vmconfig/crypto/crypto_reconciler_pre.go
pkg/vmconfig/crypto/crypto_reconciler_pre_test.go
pkg/vmconfig/crypto/internal/crypto_reconciler_context.go

This patch adds several fixes/updates for the BYOK feature:
* Support for deploying unencrypted VMs with default key provider
This patch adds support for deploying unencrypted VMs even when there is a default key provider present on the system. This is a change from the previous behavior that would disallow deploying a VM on a non-encryption storage class or sans vTPM if there was a default key provider present. This would in effect enforce the need for encryption and its requirements. This patch treats new VMs as special and allows it to skip encryption IFF:
- the discovered provider is the default
- there is no vTPM
- the storage class does not support encryption
* Fixes a bug where a VM encrypted with the default key provider would get …

🌱 Fixes for Bring Your Own Key (BYOK) provider

---

webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

This patch fixes the validation webhook for updating classless VMs. The enabling of the Resize CPU FSS caused this validation to fail for importing classless VMs since the VM controller uses the deferred patch helper. The patch helper was failing to patch VMs with no class since the validation webhook prevented patches with empty class names.
Fixes `NA`
```release-note
NONE
```

🐛 Fix validate classless vm on update

---

config/rbac/role.yaml
controllers/infra/validatingwebhookconfiguration/validatingwebhookconfiguration_controller.go

This PR fixes a typo in the kubebuilder annotation in `validatingwebhookconfiguration_controller` that will cause manager pods to go into `CrashLoopBackOff`
Fixes #
```release-note
NONE
```

:bug: Fix typo in kubebuilder annotation for manager ClusterRole

---

pkg/util/kube/storage.go
pkg/util/kube/storage_test.go
pkg/vmconfig/crypto/crypto_reconciler_pre.go
pkg/vmconfig/crypto/crypto_reconciler_pre_test.go

This patch fixes how the crypto logic detects whether or not a device is being added/edited sans policy that supports encryption.
Previously this happened via a direct IOFILTERS check, but that may not be set in the profile on the device. Instead the profile ID must be used to query whether or not the profile supports encryption.
Fixes `NA`
```release-note
NONE
```

🐛 Fix how crypto detects device sans policy

---

config/webhook/storage_quota_webhook_configuration.yaml

This PR fixes the CEL expression used in the ValidatingWebhookConfiguration used for the Storage Quota webhook allowing it to handle optional paths correctly
Fixes #
```release-note
NONE
```

:bug: Correctly handle optional, nillable path in CEL expression

---

pkg/util/vsphere/watcher/watcher.go

This patch adds a watch on `config.keyId` and `config.hardware.device` to ensure VMs are reconciled when the underlying crypto state of the VM or its devices change.
Fixes `NA`
@dougm and I agree that while watching `config.hardware.device` seems broad, the devices should actually not change all that often. It is necessary to watch these to know when any PVCs are rekeyed.
```release-note
NONE
```

🌱 Watch crypto state

---

controllers/storageclass/storageclass_controller.go
controllers/storageclass/storageclass_controller_unit_test.go

If a StorageClass does not have a storagePolicyID, don't return an error from the Reconcile so we don't go into an endless error retry because an update to the StorageClass will cause a reconcile anyways.
Fixes #
```release-note
NONE
```

🌱  Avoid endless retry if StorageClass does not have policy ID

---

controllers/storagepolicyquota/storagepolicyquota_controller.go
controllers/storagepolicyquota/storagepolicyquota_controller_unit_test.go

If there is some create or patch error for one StoragePolicyUsage don't return early from the reconcile: the others may succeed. This was prompted by the double take the reconcile ending with a "return err" where by the end err is always nil.
While here, add missing assertion for the expected CABundle.
Fixes #
```release-note
NONE
```

🌱 Aggregate CreateOrPatch errors during StoragePolicyQuota reconcile

---

services/vm-watcher/vm_watcher_service.go

This patch fixes how the logger was plumbed into the async VM watcher service.
Fixes `NA`
```release-note
Ensure the async VM watcher service has a reference to the logger.
```

🐛 Plumb logger into async VM watcher service

---

controllers/virtualmachine/virtualmachine/virtualmachine_controller_intg_test.go
pkg/util/vsphere/watcher/watcher.go
pkg/vmconfig/crypto/crypto_reconciler_post.go
pkg/vmconfig/crypto/crypto_reconciler_post_test.go
services/vm-watcher/vm_watcher_service.go
services/vm-watcher/vm_watcher_service_test.go

This patch:
* Updates the logging for the async signal components.
* Fixes a panic in the crypto reconciler's `OnResult` func that can happen if a VM create fails or properties are not fetched and OnResult is called with a nil `moVM.Config` field.
Fixes `NA`
* Depends on #777, will rebase once that has merged.
* This PR has been validated on a real testbed.
* This PR's `HEAD` commit is 3639448373c9f561e2547b759b1f1dea98b0224c, which can be seen in the log below:
```
version="0.1.0+d683393+1.8.6+36394483+80628379" 
```
The …

🐛 Update async logging / fix NPE in crypt reconciler

---

pkg/manager/manager.go

The hub version schema is added with the spokes' schema right after this.
Fixes #
```release-note
NONE
```

🌱 Remove duplicate vmopv1.AddToScheme() call

---

controllers/virtualmachine/volume/volume_controller.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

CSI does not support this for VMs at the moment since it does not wait for VMs to be placed. CSI doesn't produce a very helpful error message for this condition, and there is an ask to provide immediate feedback so put this best-effort check in the validation webhook.
This uses field. Forbidden instead of field.NotSupported since the later does not take a string to provide a useful error message.
Fixes #
Temp/quick fix - I'm not otherwise a huge fan of this being here …

🌱 Disallow PVCs with WaitForFirstConsumer StorageClass

---

go.mod
go.sum

https://github.com/vmware/govmomi/pull/3603 fixes an existing race, we've been seeing more often since bumping Go to 1.23

🐛 deps: bump govmomi to fix vcsim PropertyCollector race

---

.github/workflows/ci.yml
Makefile
hack/build-container.sh

This patch adds support for building images targeting an architecture different than the host's by specifying GOARCH with the desired architecture. For example, the following command will build a linux/amd64 image, even when executed on an Apple silicon mac:
GOARCH=amd64 make image-build
Please note, this feature requires either Podman or a version of Docker that supports buildx.
This patch also:
- Renames all the `docker-*` targets to `image-*`. The docker aliases are retained for backwards-compatibility.
- Saves any images built with the `image-build` target to the file `artifacts/vmoperator-controller-GOOS_GOARCH.tar`.
- Adds a GitHub action that verifies the `linux/amd64` image can be successfully built using `GOOS=linux GOARCH=amd64 …

✨ Support building cross-arch images

---

go.mod
go.sum
pkg/vmconfig/crypto/crypto_reconciler_pre.go
pkg/vmconfig/crypto/crypto_reconciler_pre_test.go

56a5c8a2 removed keyID validation, as 'IsValidKey' used the ListKeys API which only returns keys cached in vCenter. The 'IsValidKey' impl now uses 'QueryCryptoKeyStatus' which checks keyID against the KMS.

🐛 byok: validate encryption class keyID if specified

---

pkg/providers/vsphere/vmlifecycle/bootstrap.go
pkg/providers/vsphere/vmlifecycle/update_status.go
pkg/providers/vsphere/vmlifecycle/update_status_test.go
pkg/util/network.go
pkg/util/network_test.go

This change cleans up duplicate nameservers when VM is deployed with multiple NICs. During validating multiple NICs VM deployment under VPC networking. We find GuestStackInfo will provide DNSConfig with duplicate ipAddresses and VMOP will parse that and return VM Status with the same duplicate nameservers. To provide better readability and reduce confusion, this patch will dedupe the field.
Fixes #
Testing done:
1. Deploy a VM with multiple NICs under VPC
```
apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachine …
```

:seedling: Clean up duplicate nameservers when deployed with multiple NICs

---

go.mod
go.sum
pkg/providers/vsphere/virtualmachine/cdrom.go
pkg/providers/vsphere/virtualmachine/cdrom_test.go

This PR updates the CD-ROM assignment to use govmomi's [CreateSATAController()](https://github.com/vmware/govmomi/blob/82b4ad6611804783301025a78fd26d0224ed594f/object/virtual_device_list.go#L401-L412) function when adding a new SATA controller. This ensures that new SATA controllers are created with a proper *bus number*. Otherwise, adding two or more SATA controllers would fail due to duplicate bus numbers (default with 0) among these controllers.
Fix N/A.
This change is verified by:
- Adding new tests (maintaining 100% code coverage of the `cdrmo.go` file).
- Successfully deploying and powering on a VM Service VM with max supported CD-ROMs (2 …

🐛 Set bus number when adding SATA controllers for CD-ROM assignment

---

pkg/providers/vsphere/virtualmachine/backup.go
pkg/providers/vsphere/virtualmachine/backup_test.go

This changes is purely cosmetic and for debugging ease. The backupData will always end up having a condition pointing to the previous successful backup while the annotation would be the newer one. This removes the ambiguity.
Fixes #
N/A
N/A
```
NONE
```

🌱Remove BackupUpToDate Condition from the backup data

---

docs/concepts/workloads/vm.md

This patch adds documentation to the VM docs that highlights what hardware is supported by VM Op VMs.
Fixes `NA`
```release-note
Document the hardware supported by VM Op managed VMs.
```
----
📚 Documentation preview 📚: https://vm-operator--800.org.readthedocs.build/en/800/

📖 Document supported hardware

---

pkg/providers/vsphere/virtualmachine/publish.go
pkg/providers/vsphere/vmlifecycle/create_contentlibrary.go
pkg/util/vapi.go

This patch updates the DeployOVF call to use the VAPI activationID header. The value is set to the VM's instance UUID. This means the vim.Task that Content Library spawns to track the actual DeployOVF operation will have its activationId field set to the value of vm.spec.instanceUUID. Thus VM Operator can find and track the task, even though the DeployOVF call is blocking and does not return a task ID.
Fixes `NA`
```release-note
Use vm.spec.instanceUUID as the VAPI activation ID …
```

🌱 Use VAPI ActivationID with DeployOVF

---

pkg/util/kube/storage.go
pkg/util/kube/storage_test.go

The PVCs accessible zones include all the zones that the selected datastore is accessible on, which may include zones that are not requested. We only want to consider accessible zones that were requested in our candidates.
Fixes #
```release-note
NONE
```

🌱 Better handle bound PVC placement with multiple accessible zones

---

controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
pkg/providers/vsphere/vmlifecycle/update_status.go
pkg/providers/vsphere/vmlifecycle/update_status_test.go
pkg/record/recorder_context.go
pkg/record/recorder_context_test.go
pkg/util/vsphere/watcher/watcher.go
test/builder/vcsim_test_context.go

This patch deprecates the use of ProbeManager for non-TCP probes when the AsyncSignal feature is enabled. This is because VMs will be reconciled as soon as their heartbeat or guestinfo information is updated, and thus readiness can be determined in the normal VM reconcile loop.
Fixes `NA`
```release-note
The ProbeManager framework is deprecated for non-TCP probes when async signal is enabled.
```

✨ Deprecate ProbeManager for non-TCP probes

---

controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller_intg_test.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller_suite_test.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller_unit_test.go
controllers/virtualmachinereplicaset/virtualmachinereplicaset_controller_intg_test.go
pkg/config/config.go
pkg/config/default.go
pkg/config/env.go
pkg/config/env/env.go
pkg/config/env_test.go
pkg/providers/fake/fake_vm_provider.go
pkg/providers/vm_provider_interface.go
pkg/providers/vsphere/vmlifecycle/create.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm2_test.go
pkg/providers/vsphere/vmprovider_vm_resize_test.go
pkg/providers/vsphere/vmprovider_vm_test.go
pkg/providers/vsphere/vsphere_suite_test.go

This patch introduces an async variant on the provider's `CreateOrUpdateVirtualMachine` function. This new function, `CreateOrUpdateVirtualMachineAsync`, returns `<-chan error, error`, for when a non-blocking create is used.
Please note, support for async create is only enabled when the async signal feature is enabled. This is because the new async create workflow no longer:
- Falls into a post-create reconfigure, instead allowing async signal to enqueue a new reconcile when the create has completed.
- Requeues the VM after N time based on the VM's state, ex. when the VM is powered on and does not yet have an IP address. This also now relies on async signal when the feature is enabled.
While a non-blocking create does mean the reconciler …

✨ Support async create VM

---

pkg/backup/api/backup_types.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

SRM (Site Reliability Manager) needs to be able to change a VM's network interface to connect to the test failover network.  This change skips part of the validation webhook if a predefined test failover label is present on the VM resource.  This change introduces a label (as opposed to an annotation) because we want to allow server side indexing so clients can filter and operate on all VMs that are part of a test failover.  This will help with debuggability, and cleanup of test failed over VMs. 
A test failover does not need to add new interfaces, so keep that check as is.
**Testing Done**
- Existing unit tests as well as newly added tests
- Manually tested by loading VM operator in an env 
- Without the label
``` …
```

:seedling: Allow SRM to change network of a registered VM for test failover

---

pkg/constants/constants.go
pkg/providers/vsphere/placement/cluster_placement.go
pkg/util/vmopv1/vm.go
pkg/util/vmopv1/vm_test.go

This patch ensures the minimum hardware version is set to vmx-14 when a VM has a vTPM.
Fixes #
```release-note
Set minimum hardware version to vmx-14 when VM has vTPM
```

🐛 Set min HW version when VM has vTPM

---

pkg/providers/vsphere/placement/zone_placement_test.go
pkg/providers/vsphere/vcenter/getvm_test.go
pkg/providers/vsphere/vcenter/resourcepool_test.go
test/builder/vcsim_test_context.go

This is a leftover from when VCSim text context supported both v1a1 and v1a2 types during that transition.
Fixes #
```release-note
NONE
```

🌱 Remove old A2 function suffix

---

main.go
pkg/context/fake/fake_controller_manager_context.go
pkg/providers/vsphere/vmprovider.go
pkg/providers/vsphere/vmprovider_test.go
pkg/providers/vsphere/vmprovider_vm_test.go
pkg/providers/vsphere/vsphere_suite_test.go
pkg/util/ovfcache/internal/ovfcache_internal.go
pkg/util/ovfcache/internal/ovfcache_internal_suite_test.go
pkg/util/ovfcache/internal/ovfcache_internal_test.go
pkg/util/ovfcache/ovfcache.go
pkg/util/ovfcache/ovfcache_suite_test.go
pkg/util/ovfcache/ovfcache_test.go
test/builder/unit_test_context.go
test/builder/vcsim_test_context.go

This patch refactors the OVF cache into an context-based package so the cache may be shared across the project and not limited to the vSphere provider. This also simplifies a future refactor to transition the cache to using Secret/ ConfigMap resources in Kube for caching the OVF envelopes as opposed to an in-memory store.
Fixes `NA`
This is required for the Fast Deploy work in order to efficiently retrieve the OVF envelope for parsing its controllers/disks.
```release-note …
```

🌱 OVF Cache Package

---

controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_suite_test.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_suite_test.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller_intg_test.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller_suite_test.go
pkg/util/ovfcache/internal/ovfcache_internal.go
pkg/util/ovfcache/internal/ovfcache_internal_test.go
pkg/util/ovfcache/ovfcache.go

This patch fixes the issue where controllers getting the OVF cache from the context would panic because the original commit did not include the JoinContext call for the OVF cache in the controllers.
Fixes `NA`
```release-note
Fix panic when OVF cache is missing from context
```

🐛 Fix panic in controllers missing ovfcache

---

pkg/providers/vsphere/vmlifecycle/bootstrap_linuxprep.go
pkg/providers/vsphere/vmlifecycle/bootstrap_sysprep.go
pkg/providers/vsphere/vmlifecycle/bootstrap_vappconfig.go
pkg/providers/vsphere/vmlifecycle/bootstrap_vappconfig_test.go

This patch updates the behavior of the vAppConfig, LinuxPrep, and Sysprep bootstrap providers to wait on the VM to have a non-nil config.vAppConfig property when it is expected to exist.
Async create means we are no longer falling through to the update logic directly after create, instead, relying on the reconciler to be reentrant. That all works fine, but the problem is vpxd is sending signal on the property collector that the VM is ready prior to its config.vAppConfig property being set.
VM Op receives this signal and proceeds to reconcile the VM. Since previously we did not wait on an expected vAppConfig, we proceeded to configure and power on the VM. Once it is powered on, any customization that dependended upon the vAppConfig properties …

🐛 Wait on vAppConfig during async create

---

api/v1alpha3/virtualmachine_types.go
pkg/util/annotations/helpers.go
pkg/util/annotations/helpers_test.go
pkg/util/vmopv1/vm.go
pkg/util/vmopv1/vm_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

VMs that are imported, or registered already have the virtual machine created on the infrastructure.  As such, we don't need to apply the same strict validations for them such as making sure the image is not null / valid.  To that end, this change introduces an annotation that will be applied on the Imported, or Registered VMs.  This will allow our webhooks to skip these checks if the annotation is present.
For now, maintain the existing mechanism which allows _all_ VM creations to be imageless if the import or the incremental restore feature is enabled.  Once this change is merged, we will yank out that code to make that check stricter (only annotation based).
There;s also a change to the …

:seedling: Allow imported and registered VMs to skip image validation checks on Create/Update

---

pkg/providers/vsphere/vcenter/getvm.go
pkg/providers/vsphere/vcenter/getvm_test.go
pkg/providers/vsphere/vmprovider.go

Originally, we'd try to find a VM via its MoID, with a fallback to the Inventory by path. Since then, we've added the Instance and Bios UUIDs as preferred ways to find a VM. VMs are now created with a known Instance ID - that of the k8s VM UID - that we can use for lookup.
This removes lookup depending on k8s objects to determine if the VM exists that have a separate lifecycle than the VM.
Fixes #
```release-note
The lookup VM by the Inventory path final fallback is removed. VM …
```

🐛 Remove Inventory path fallback for GetVM

---

config/local/vmoperator/local_env_var_patch.yaml
config/wcp/vmoperator/manager_env_var_patch.yaml
controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_unit_test.go
controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_unit_test.go
pkg/config/config.go
pkg/config/env.go
pkg/config/env/env.go
pkg/config/env_test.go
pkg/util/kube/proxyaddr/proxy_address.go
pkg/util/kube/proxyaddr/proxy_address_test.go

Now that WCP_Simplified_Enablement FSS is enabled on main, we can safely remove it. 
Fixes #
```release-note
```

🌱 Remove WCP_Simplified_Enablement FSS

---

config/webhook/storage_quota_webhook_configuration.yaml

As part of StoragePolicyQuota Validating Webhook that runs inside VM Operator there is a check to ensure that the VM image is provided since this is where we obtain the image capacity from. This has the unintended side-effect of blocking vm creation for imageless VMs.
This patch modifies the ValidatingWebhookConfiguration used in the StoragePolicyQuota validation flow to ignore VM creation request where the image is not provided. This will prevent this webhook from blocking imageless VM creations, while allowing the VirtualMachine ValidatingWebhook to continue to perform image validation. 
**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when …

:bug: Do not invoke StoragePolicyQuota Validating Webhook for imageless VMs

---

pkg/providers/vsphere/virtualmachine/backup.go
pkg/providers/vsphere/virtualmachine/backup_test.go

Previously we'd base64+gzip "null" for this case but it is clearer to remove the EC entry in that case.
Fixes #
```release-note
NONE
```

🌱 Remove disk related backup field from ExtraConfig when empty

---

go.mod
go.sum
pkg/providers/vsphere/virtualmachine/backup_test.go

This patch updates the GoVmomi dependency to https://github.com/vmware/govmomi/commit/bde6f8c8ae045fea4a6fa3fac5c6da55620906b4 to support no longer encoding an unstable disk UUID in the PVC backup tests.
Please see https://github.com/vmware-tanzu/vm-operator/pull/824 for more information.
Fixes `NA`
```release-note
Do not hardcode PVC UUID in backup tests.
```

🌱 Do not hardcode PVC UUID in backup test

---

controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_intg_test.go
controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_unit_test.go

This PR fixes a potential race condition in unit tests by changing `v1a2ProviderCaller bool` type to `atomic.Bool`.  The race could happen if the WebConsoleRequest CR is reconciled multiple times, causing concurrent reads and writes.
Fixes https://github.com/vmware-tanzu/vm-operator/actions/runs/12355794076/job/34480234221?pr=823
N/A
```release-note
Fix race in WebConsoleRequest controller tests.
```

🌱 Fix race in WebConsoleRequest controller tests

---

api/v1alpha1/contentlibraryprovider_types.go
api/v1alpha1/contentsource_types.go
api/v1alpha1/virtualmachine_types.go
api/v1alpha1/virtualmachineclass_types.go
api/v1alpha1/virtualmachineclassbinding_types.go
api/v1alpha1/virtualmachineimage_types.go
api/v1alpha1/virtualmachinepublishrequest_types.go
api/v1alpha1/virtualmachineservice_types.go
api/v1alpha1/virtualmachinesetresourcepolicy_types.go
api/v1alpha1/webconsolerequest_types.go
config/crd/bases/vmoperator.vmware.com_clustervirtualmachineimages.yaml
config/crd/bases/vmoperator.vmware.com_contentlibraryproviders.yaml
config/crd/bases/vmoperator.vmware.com_contentsources.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineclassbindings.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachinepublishrequests.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachineservices.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachinesetresourcepolicies.yaml
config/crd/bases/vmoperator.vmware.com_webconsolerequests.yaml

This patch marks v1alpha1 as deprecated. The APIs ContentLibraryProvider, ContentSource, and VirtualMachineClassBinding, and WebConsoleRequest, along with their List variants, also indicate they are no longer supported in future versions.
Fixes `NA`
```release-note
Deprecate the v1alpha1 APIs 
```

✨ Mark v1alpha1 as deprecated

---

services/vm-watcher/vm_watcher_service.go
services/vm-watcher/vm_watcher_service_test.go

This patch updates the behavior of the VM watcher service to no longer return an error if there is an issue starting. While this is the correct behavior, it also results in CBLO for the VM Op pod if the reason for the error is external and not resolved.
For example, if a user configures the host name of vCenter to be invalid, the VM Op pod will be in CBLO until this is resolved. Again, this is technically correct, and resolves itself once the user fixes the misconfigured setting.
However, the VM Op pod becoming unavailable on a single-node Supervisor also means no webhooks are running, and this would be bad.
**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close …

🌱 Do not CBLO if VM watcher service fails

---

webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

If the VM Spec.Network was changed to/from nil, the validation webhook would NPE. 
Add a few basic update tests for VM Spec.Network.
Fixes #
I think the stems from late in v1a2 we decided to make most of the top level Spec/Status fields pointers and this was just missed.
```release-note
NONE
```

🐛  Fix potential VM validation webhook NPE for Spec.Network

---

api/v1alpha3/virtualmachine_types.go
pkg/backup/api/backup_types.go
pkg/util/annotations/helpers.go
pkg/util/annotations/helpers_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

We need a new annotation for failed over VMs so we can skip some webhook checks.  This is different from imported, or registered VMs since we will need to relax additional webhook checks such as allowing for network manipulation.
Remove the test failover annotation since that is no longer needed.
This annotation can be considered a replacement of the test failover annotation except it will be used by production failover workflows as well.
```release-note
Introduce a new annotation to identify failed over VMs
```

:seedling: Introduce a new annotation to identify failed over VMs

---

.golangci.yml
cmd/web-console-validator/main.go
controllers/infra/zone/zone_controller.go
controllers/util/encoding/encoding.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
pkg/util/vsphere/vm/power_state.go
pkg/vmconfig/crypto/crypto_reconciler_pre.go
test/builder/util.go
webhooks/virtualmachine/mutation/virtualmachine_mutator.go

In case these become wrapped errors later.
Fixes #
```release-note
NONE
```

🌱 Use errors.Is() to silence lint warnings

---

webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator.go
webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_unit_test.go

This PR updates the unified storage quota validating webhook to skip ISO-type images, as these VMIs don't have any disks listed under the status field.
Given the following VM YAML:
```console
$ cat vm-iso.yaml
apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachine
metadata:
name: test-vm-iso
namespace: sdiliyaer-test
spec:
className: best-effort-small
storageClass: wcpglobal-storage-profile
cdrom:
- name: cdrom1
image:
kind: VirtualMachineImage
name: vmi-da1c2e296c431a6eb
guestID: otherGuest
```
Current webhook denies the VM creation request:
```console
$ kubectl apply -f vm-iso.yaml
Error from server (Forbidden): error when creating "vm-iso.yaml": admission webhook "quota-create.validating.virtualmachine.v1alpha3.vmoperator.vmware.c …
```

🐛 Skip ISO images in unified storage quota validator

---

config/wcp/vmoperator/manager_env_var_patch.yaml
controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
go.mod
go.sum
pkg/config/config.go
pkg/config/env.go
pkg/config/env/env.go
pkg/config/env_test.go
pkg/providers/vsphere/client/client_test.go
pkg/providers/vsphere/contentlibrary/content_library_utils.go
pkg/providers/vsphere/placement/cluster_placement.go
pkg/providers/vsphere/placement/zone_placement.go
pkg/providers/vsphere/placement/zone_placement_test.go
pkg/providers/vsphere/virtualmachine/configspec.go
pkg/providers/vsphere/vmlifecycle/create.go
pkg/providers/vsphere/vmlifecycle/create_contentlibrary.go
pkg/providers/vsphere/vmlifecycle/create_contentlibrary_linked_clone.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/util/configspec.go
pkg/util/configspec_test.go
pkg/util/nil.go
pkg/util/nil_test.go
pkg/util/vmopv1/image.go
pkg/util/vmopv1/image_test.go
pkg/util/vsphere/client/client_test.go
pkg/util/vsphere/library/item_cache.go
pkg/util/vsphere/library/item_cache_test.go
pkg/util/vsphere/library/item_sync.go
pkg/util/vsphere/library/item_sync_test.go
pkg/util/vsphere/library/library_suite_test.go

This patch adds support for the Fast Deploy feature, i.e. the ability to quickly provision a VM as a linked clone, as an experimental feature that must be enabled manually. There are many things about this feature that may change prior to it being ready for production.
The patch notes below are broken down into several sections:
* **Goals** -- What is currently supported
* **Non-goals** -- What is not on the table right now 
* **Architecture**
* **Activation** -- How to enable this experimental feature
* **Placement** --  Request datastore recommendations
* **Disk cache** -- Per-datastore cache for Content Library item disk(s)
* **Create VM** --  Create linked clone directly from cached disk
The following goals are what is considered …

✨ Fast Deploy (Experimental)

---

pkg/providers/vsphere/vmlifecycle/create_contentlibrary_linked_clone.go

This patch fixes a linter error that occurs in GitHub actions due to a feature enabled prior to the Fast Deploy PoC PR being merged. That slipped in an issue the linter checks. This fixes that.
Fixes `NA`
This was handled in https://github.com/vmware-tanzu/vm-operator/pull/834, but #823 was merged after the linter came into effect, and this issue was not caught in that PR. However, this is why there was a [failure on `main`](https://github.com/vmware-tanzu/vm-operator/actions/runs/12505711663/job/34889502628)  after the PR …

🐛 Fix lint error about err checking

---

controllers/virtualmachine/volume/volume_controller.go
controllers/virtualmachine/volume/volume_controller_unit_test.go

This patch ensures the crypto information in status.volumes is preserved for PVCs.
Fixes `NA`
Depends on #842
```release-note
Preserve the crypto info in a managed volume's status.
```

🐛 Preserve crypto status in managed vols (PVC)

---

docs/tutorials/deploy-vm/README.md

The current redirect doesn't work as it points to https://vm-operator.readthedocs.io/en/latest/tutorials/concepts/workloads/vm/#cd-rom.
This PR fixes it by redirecting to https://vm-operator.readthedocs.io/en/latest/concepts/workloads/vm/#cd-rom.
Fixes N/A.
None.
```release-note
NONE
```
----
📚 Documentation preview 📚: https://vm-operator--845.org.readthedocs.build/en/845/

📖 Fix broken link in the deploy VM doc

---

pkg/conditions/conditions.go
pkg/conditions/conditions_suite_test.go
pkg/conditions/conditions_test.go
pkg/conditions/getter.go
pkg/conditions/getter_test.go
pkg/conditions/merge.go
pkg/conditions/merge_strategies.go
pkg/conditions/merge_strategies_test.go
pkg/conditions/merge_test.go
pkg/conditions/patch_test.go
pkg/conditions/setter.go
pkg/conditions/setter_test.go
pkg/conditions/unstructured_test.go
pkg/patch/patch.go
pkg/providers/vsphere/vmprovider_vm_utils.go

This patch introduces the new type `Conditions` from `pkg/conditions`. This new type provides all of the same helper functions the package provides, but now for any slice of `metav1.Condition` objects. The previous helpers have been rewritten to use the new type.
Perhaps more importantly, the package has been updated to no longer require that the `Getter` and `Setter` interfaces refer to Kubernetes objects. Now the interfaces are valid for *any* Golang type that implements the get/set functions.
Finally, the `pkg/patch` package has also been updated to account for the changes to the `pkg/conditions` interfaces `Getter` and `Setter`.
**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, …

✨ Conditions helper & refactor

---

controllers/virtualmachineservice/virtualmachineservice_controller.go

This patch adds choosing NSXT lb when lb type unspecified during VPC networking. VPC started with only AVI lb and with design changes, this got overlooked. 
When the VirtualMachineService created in VPC networking includes annotations for `externalTrafficPolicy` and `healthCheckNodePort`, it's expected for VirtualMachineService to have annotation `ncp/healthCheckNodePort`.
Fixes # N/A
```release-note
NONE
```

:bug: Use NSX-T LB for VPC networking when lb unspecified

---

pkg/providers/vsphere/vmprovider_vm.go

This patch ensures the counter that tracks the number of concurrent creates is properly decremented if the getCreateArgs function fails when doing a non-blocking create.
Fixes `NA`
```release-note
Decrement concurrent creates counter if getCreateArgs fails
```

🐛 Decrement concurrent creates if getCreateArgs fails

---

controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller_unit_test.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_unit_test.go

The VMI Status.Disks[] field was added in v1a3 but since the cached content version will be the same, that field won't be populated.
Just a quick fix of checking for the present of disks. There is a WIP branch in this area that will fix it in a better way.
Fixes #
```release-note
NONE
```

🐛 Fix empty VMI Status.Disks[] after upgrade

---

config/local/vmoperator/local_env_var_patch.yaml
config/wcp/vmoperator/manager_env_var_patch.yaml
pkg/config/config.go
pkg/config/env.go
pkg/config/env/env.go
pkg/config/env_test.go

Since the WCP_TKG_Multiple_CL FSS has been enabled on main, and will be released with VCF 9.0
Removing all the occurrences of FSS_WCP_TKG_Multiple_CL.
Will keep the capabilities which are being set dynamically.
Fixes #848 
```release-note
Removed the WCP_TKG_Multiple_CL feature state switch as it has been enabled
```

:seedling: Remove FSS_WCP_TKG_Multiple_CL

---

docs/concepts/workloads/vm.md

This patch adds more documentation around rekeying an encrypted VM to explain that rekeying requires the encryption classes to have different provider and/or key IDs.
This patch adds more documentation around rekeying an encrypted VM to explain that rekeying requires the encryption classes to have different provider and/or key IDs.
Fixes `NA`
```release-note
Update docs for rekeying encrypted VM
```
----
📚 Documentation preview 📚: …

📖 Update VM crypto docs on rekey

---

controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller_intg_test.go
pkg/providers/vm_provider_interface.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_test.go

This patch adds support to the VirtualMachine controller for background reconciliation awareness. Rather, the controller is now aware if a VM is already being reconciled in a background thread due to an async operation and will not allow the VM to be reconciled again until the async operation is complete.
This is necessary due to someone rapidly applying VM yaml then deleting it. When this occurs it is possible that the vSphere VM is not deleted since its creation is occurring on a background thread. 
Fixes `NA`
**Please …

🐛 Background reconcile awareness support

---

controllers/infra/capability/configmap/configmap_capability_controller_suite_test.go
controllers/infra/capability/configmap/configmap_capability_controller_test.go
controllers/infra/capability/crd/crd_capability_controller_suite_test.go
controllers/infra/validatingwebhookconfiguration/validatingwebhookconfiguration_controller_suite_test.go
controllers/storageclass/storageclass_controller_suite_test.go
controllers/storagepolicyquota/storagepolicyquota_controller_suite_test.go
controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_suite_test.go
test/builder/test_suite.go

Also fix the feature state for the ConfigMap capabilities controller. It is only used when SVAsyncUpgrade is false but the setup was setting it to true. The fallout from this is that the WorkloadDomainIsolation feature is not via the capability when async upgrade is false so remove that from the integration tests.
Fixes #
The CM capability controller is mostly moot at this point, and it may be time to update the Default().
```release-note
NONE
```

🌱 Consistently use the default config for controller integration tests

---

config/local/vmoperator/local_env_var_patch.yaml
config/wcp/vmoperator/manager_env_var_patch.yaml
controllers/infra/zone/zone_controller_test.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller_intg_test.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller_unit_test.go
controllers/virtualmachinesetresourcepolicy/virtualmachinesetresourcepolicy_controller.go
controllers/virtualmachinesetresourcepolicy/virtualmachinesetresourcepolicy_controller_suite_test.go
main.go
pkg/providers/fake/fake_vm_provider.go
pkg/providers/vsphere/placement/zone_placement_test.go
pkg/providers/vsphere/vcenter/folder_test.go
pkg/providers/vsphere/vcenter/getvm_test.go
pkg/providers/vsphere/vcenter/resourcepool_test.go
pkg/providers/vsphere/vmlifecycle/update_status.go
pkg/providers/vsphere/vmlifecycle/update_status_test.go
pkg/providers/vsphere/vmprovider_resourcepolicy_test.go
pkg/providers/vsphere/vmprovider_vm2_test.go
pkg/providers/vsphere/vmprovider_vm_resize_test.go
pkg/providers/vsphere/vmprovider_vm_test.go
pkg/providers/vsphere/vsphere_suite_test.go
pkg/util/vmopv1/vm.go
pkg/util/vmopv1/vm_test.go
services/vm-watcher/vm_watcher_service_test.go
test/builder/vcsim_test_context.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

The feature WorkloadDomainIsolation has been enabled and thus its feature state switch should be removed, the enabled logic acting as the new, default, and only logic.
Please note, the updated placement logic is always true for non-vSphere Kubernetes Service (VKS) workloads. For VKS nodes, the placement logic is determined by the value of the WorkloadDomainIsolation capability.
Please note, the env var for the FSS is retained in the deployment YAML as "true" so as not to break testing that relies on reading this value.
Fixes `NA`
**Are there any special notes for your …

🌱 Remove FSS WorkloadDomainIsolation

---

config/local/vmoperator/local_env_var_patch.yaml
config/wcp/vmoperator/manager_env_var_patch.yaml
main.go
pkg/config/config.go
pkg/config/default.go
pkg/config/env.go
pkg/config/env/env.go
pkg/config/env_test.go
pkg/mem/mem.go
pkg/mem/mem_suite_test.go
pkg/mem/mem_test.go

This package adds support for emitting the results of a periodic call to `runtime.ReadMemStats`, enabling easily discovering the memory usage of the containers from the perspective of the Go runtime.
The environment variable `MEM_STATS_PERIOD` may be set to a valid time.Duration string to configure the interval, and it defaults to 10m.
The memory usage is emitted as soon as `main.go` begins, ex.:
```shell
I0121 09:38:11.853666   91609 mem.go:30] "MemStats" now=1737473891853622000 buckHashSys=1449862 debugGC=false enableGC=true frees=9602 gcCPUFraction=0.013948351398451445 gcSys=3138792 heapAlloc=4623544 heapIdle=1736704 heapInUse=6127616 heapObjects=18663 heapReleased=1703936 heapSys=7864320 lastGC=1737473891832972000 lookups=0 …
```

🌱 Emit memory statistics to log file / prometheus

---

pkg/providers/vsphere/vcenter/getvm.go
pkg/providers/vsphere/vcenter/getvm_test.go
pkg/providers/vsphere/vmprovider.go

If the VC session is invalid - like because the VC creds had rotated - GetVirtualMachine() could incorrectly return that the VM does not exist. If the lookup is being done to in response to the k8s VM being deleted, we would not actually delete the VC VM.
While here, improve how looking up by the MoID was done: we don't need to use the Finder instead just use the PropertyCollector. The old Finder lookup would always return an error if the MoID doesn't exist, which means that we could get stuck if the VM actually didn't exist. This would really only be an issue of we removed the VC VM but failed to remove our finalizer.
**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, …

🐛 Handle invalid VC Session in GetVirtualMachine()

---

controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller_intg_test.go
controllers/contentlibrary/utils/controller_builder.go
controllers/contentlibrary/utils/controller_builder_test.go

This patch fixes a panic in the ContentLibrary controllers that occurs due to a missing JoinContext for ovfcache in the Reconcile function.
Fixes `NA`
```release-note
NONE
```

🐛 Do not panic in CLS controllers

---

pkg/providers/vsphere/clustermodules/cluster_modules.go
pkg/providers/vsphere/clustermodules/cluster_modules_provider.go
pkg/providers/vsphere/clustermodules/cluster_modules_test.go
test/builder/vcsim_test_context.go

This keeps the for who or for what in the cluster module logs.
Also add the test logger in the VCSim context so we still get logs during the tests.
While here update the tests to not use an old v1a1 type.
Fixes #
```release-note
NONE
```

🌱 Update cluster modules provider to use context logger

---

config/wcp/vmoperator/cpu_resources_patch.yaml

This change increases the CPU and memory limits for the controller manager pod in VM operator deployment to support the desired scale for VCF 9.0.
Testing Done:
- Generated the manifest and verified that the CPU and memory limits were updated:
```
limits:
cpu: 1500m
memory: 1Gi
requests:
cpu: 100m
memory: 75Mi
```
```release-note
Increase CPU and memory limits for the controller manager pod
```

:seedling:  Increase CPU and memory limits for the controller manager pod

---

.github/workflows/ci.yml
go.mod

This patch updates go.mod to specify Go 1.23.5 and updates the GitHub actions to use the Go version from go.mod.
This patch also addresses https://pkg.go.dev/vuln/GO-2025-3420 and https://pkg.go.dev/vuln/GO-2025-3373, both fixed by updating from Go 1.23.4 to 1.23.5.
Fixes `NA`
```release-note
Use Go 1.23.5
```

🌱 Go 1.23.5 / GH Action uses go.mod

---

pkg/backup/api/backup_types.go
pkg/providers/vsphere/virtualmachine/backup.go
pkg/providers/vsphere/virtualmachine/backup_test.go

This change modifies the disk backup to also include disk UUIDs.  This allows us to look up and identify disks using UUIDs to differentiate classic disks from disks that should be FCDs.
For now, the disk UUIDs are only used in failover workflows since vSphere Replication guarantees that the disks will be restored with the same UUID as the primary/source.
This change is specific for failover of VMs.
```release-note
Include UUID of disk backing in disk backup
```

:seedling: Include UUID of disk backing in disk backup

---

controllers/contentlibrary/utils/controller_builder.go
controllers/contentlibrary/utils/controller_builder_test.go

This patch fixes an issue where the labels on the CVMI resources from the CCLI resources were missing. The labels were added via https://github.com/vmware-tanzu/vm-operator/pull/406 but were accidentally removed via
https://github.com/vmware-tanzu/vm-operator/pull/851.
When adding them back, there are now also tests to validate the logic works as there were no tests in the original PR.
Fixes #
Fixes https://github.com/vmware-tanzu/vm-operator/pull/872 on 9.0 release branch …

Fix missing labels on CVMI resources

---

controllers/contentlibrary/utils/controller_builder.go
controllers/contentlibrary/utils/controller_builder_test.go
pkg/providers/vsphere/contentlibrary/content_library_utils.go
pkg/providers/vsphere/contentlibrary/content_library_utils_test.go

Add back the content version check and Disks not empty hack. This will prevent duplicate CL task from being created when the CL item has not changed.
Clear arrays in the Image Status before updating them. This bug had been mostly masked by the short circuit check above but without clearing it the duplicate appends would eventually cause the object to exceed the allowed limit.
Fixes #
```release-note
Restore content library item content version short circuit check.
```

🐛 Fix duplicate append of Image.Status fields

---

controllers/infra/capability/crd/crd_capability_controller_test.go

I get occasional test failures in the CRD capability controller where numExits is one more than expected. Moving the reset to the BeforeEach() seems to fix it, or at least make it much less likely, and this is the ConfigMap controller already has it.
Fixes #
```release-note
NONE
```

🐛 Fix CRD capability controller numExit races

---

config/crd/kustomization.yaml

This patch adds the VMICache resource to the infrastructure YAML.
Fixes `NA`
```release-note
NONE
```

🌱 Add VMICache to infra YAML

---

pkg/providers/vsphere/resources/vm.go

This can contain useful info even when the task succeeds. We currently only ever care about the taskInfo when we also care if the task fails, so this was otherwise working.
This resource VirtualMachine package is super old, and only ever tested indirectly, and my eventual plan is to either remove it entirely or move it functionality into the virtualmachine package so just quick fix this now so it doesn't trip up anybody else later.
Fixes #
```release-note
NONE
```

🌱 Return taskInfo from successful VM Reconfigure task

---

controllers/infra/controllers.go

This patch fixes a bug where the zone controller was not loaded unless the Workload Domain Isolation capability was enabled. That logic is old and was supposed to be removed, but was missed.
Fixes `NA`
```release-note
Always load the zone controller
```

Always load the infra/zone controller

---

.github/workflows/ci.yml

This patch updates go.mod to use Go 1.23.6 to account for https://pkg.go.dev/vuln/GO-2025-3447.
Fixes `NA`
```release-note
Go 1.23.6
```

🌱 Go 1.23.6

---

.github/workflows/ci.yml

Cross-port of #887 to release/vc-9.0.0.
This patch updates go.mod to use Go 1.23.6 to account for https://pkg.go.dev/vuln/GO-2025-3447.
Fixes `NA`
```release-note
Go 1.23.6
```

🌱 (x-port vc-9.0.0) Go 1.23.6

---

config/wcp/vmoperator/cpu_resources_patch.yaml

Cross-port of https://github.com/vmware-tanzu/vm-operator/pull/869 to release/vc-9.0.0.
This change increases the CPU and memory limits for the controller manager pod in VM operator deployment to support the desired scale for VCF 9.0.
Testing Done:
- Generated the manifest and verified that the CPU and memory limits were updated:
```
limits:
cpu: 1500m
memory: 1Gi
requests:
cpu: 100m
memory: 75Mi
```
```release-note
Increase CPU and memory limits for the controller manager pod
```

🌱 (x-port vc-9.0.0) Increase CPU and mem limit for controller-manager pod

---

controllers/infra/controllers.go

Cross-port of https://github.com/vmware-tanzu/vm-operator/pull/886 to release/vc-9.0.0.
This patch fixes a bug where the zone controller was not loaded unless the Workload Domain Isolation capability was enabled. That logic is old and was supposed to be removed, but was missed.
Fixes `NA`
```release-note
Always load the zone controller
```

🐛 (x-port vc-9.0.0) Always load the infra/zone controller

---

pkg/backup/api/backup_types.go
pkg/providers/vsphere/virtualmachine/backup.go
pkg/providers/vsphere/virtualmachine/backup_test.go

This change modifies the disk backups to also include disk backing UUIDs.  This allows us to look up and identify disks using UUIDs to differentiate classic disks from disks that should be FCDs.
For now, the disk UUIDs are only used in failover workflows since vSphere Replication guarantees that the disks will be restored with the same UUID as the primary/source.
```release-note
Include UUID of disk backing in disk backup
```

:seedling: Include UUID of disk backing in disk backup (#864)

---

pkg/providers/vsphere/vcenter/getvm.go
pkg/providers/vsphere/vcenter/getvm_test.go
pkg/providers/vsphere/vmprovider.go

Cross-port of main https://github.com/vmware-tanzu/vm-operator/pull/866 to release/vc-9.0.0
If the VC session is invalid - like because the VC creds had rotated - GetVirtualMachine() could incorrectly return that the VM does not exist. If the lookup is being done to in response to the k8s VM being deleted, we would not actually delete the VC VM.
While here, improve how looking up by the MoID was done: we don't need to use the Finder instead just use the PropertyCollector. The old Finder lookup would always return an error if the MoID doesn't exist, which means that we could get stuck if the VM actually didn't exist. This would really only be an issue of we removed the VC VM but failed to remove our finalizer.
**Which issue(s) is/are …

(x-port vc-9.0.0) 🐛 Handle invalid VC Session in GetVirtualMachine()

---

pkg/providers/fake/fake_vm_provider.go
pkg/providers/vm_provider_interface.go
pkg/providers/vsphere/vmprovider_resourcepolicy.go
pkg/providers/vsphere/vmprovider_resourcepolicy_test.go

Long ago, this method was called from the VirtualMachine controller and used to determine if we could create the (TKG) VM. Now, what constituted the RP ready checks are done individually during the VM creation flow, leaving this method only being used for test assertions.
Fixes #
```release-note
NONE
```

🌱 Remove IsVirtualMachineSetResourcePolicyReady()

---

controllers/virtualmachineimagecache/virtualmachineimagecache_controller.go
pkg/errors/requeue_error.go
pkg/errors/requeue_error_test.go

If these empty Spec fields are updated, the Watch() will cause the controller to reconcile the object so we don't need to do a requeue.
Add NoRequeueError that returns the controller-runtime TerminalError that does not do a requeue but is logged and counted as an error.
While here, update the VMIC ReconcileNormal() to use the logger from the context instead of parent reconciler so the object name is still there.
Fixes #
There are a few other ways to do this:
- Just have the controller return the TerminalError directly but …

🌱 Do not requeue VMIC for empty Spec fields

---

.golangci.yml
controllers/virtualmachinereplicaset/virtualmachinereplicaset_controller.go
pkg/providers/vsphere/contentlibrary/content_library_provider.go
pkg/providers/vsphere/virtualmachine/backup.go
pkg/providers/vsphere/vmlifecycle/bootstrap.go
pkg/util/kube/spq/spq.go
pkg/util/vsphere/vm/hardware_version_test.go
pkg/util/vsphere/vm/power_state.go
pkg/util/vsphere/watcher/watcher_test.go
test/testutil/util.go
webhooks/virtualmachine/validation/virtualmachine_validator.go

Use %w instead of %v to wrap errors
Use errors Is() and As() and the govmomi equivalents instead of type casting/checking
Fixes #
```release-note
NONE
```

   🌱 Enable all errorlint checks

---

controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go

This patch updates many K8s client.List calls to use the UnsafeDisableDeepCopy option where it is possible to do so. This is done with caution, and only in places where the result is self-contained and there is little chance of mutating the objects from the cache. There is also a warning placed on every location where this option is used.
This patch improves performance.
Credit to @bryanv for thinking of this.
Fixes `NA`
```release-note
Use UnsafeDisableDeepCopy when listing …
```

🌱 Use UnsafeDisableDeepCopy when possible

---

pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_test.go
pkg/util/vsphere/watcher/watcher.go

This patch ensures only connected VMs are reconciled. If a VM is not in a connected state, it will not be requeued for reconciliation. Instead the watcher service will enqueue the VM for reconciliation once the VM's connection state has changed.
Fixes `NA`
```release-note
Reconcile VMs with connectionState == connected or reconcile when it changes to connected
```

🌱 Only reconcile connected VMs

---

docs/concepts/images/vm-image.md

The original link didn't seem to work anymore: https://cloud-images.ubuntu.com/releases/22.10/release-20230302/ubuntu-22.10-server-cloudimg-amd64.ova
Update it to the correct working one: https://cloud-images.ubuntu.com/releases/22.10/release-20230716/ubuntu-22.10-server-cloudimg-amd64.ova
All credit to Katarina Brookfield!
Fixes N/A.
None.
```release-note
Update ubuntu image link in documentation.
```
----
📚 Documentation preview 📚: https://vm-operator--898.org.readthedocs.build/en/898/

🌱 Fix broken ubuntu image link in docs

---

controllers/contentlibrary/utils/controller_builder_test.go
controllers/infra/secret/infra_secret_controller.go
controllers/infra/secret/infra_secret_controller_intg_test.go
controllers/infra/secret/infra_secret_controller_suite_test.go
pkg/config/config.go
pkg/config/default.go
pkg/config/env.go
pkg/config/env/env.go
pkg/config/env_test.go
pkg/constants/constants.go
pkg/providers/fake/fake_vm_provider.go
pkg/providers/vm_provider_interface.go
pkg/providers/vsphere/client/client.go
pkg/providers/vsphere/client/client_test.go
pkg/providers/vsphere/config/config.go
pkg/providers/vsphere/config/config_test.go
pkg/providers/vsphere/credentials/credentials.go
pkg/providers/vsphere/credentials/credentials_test.go
pkg/providers/vsphere/placement/zone_placement_test.go
pkg/providers/vsphere/vmprovider.go
pkg/providers/vsphere/vmprovider_test.go
pkg/providers/vsphere/vmprovider_vm2_test.go
pkg/providers/vsphere/vmprovider_vm_test.go
pkg/vmconfig/crypto/crypto_reconciler_pre_test.go
test/builder/vcsim_test_context.go

Only logout an existing VC client when the creds have actually changed. Previously, when the Infra Secret controller first starts it would have always logged the VC client if present. While this race has been present for a long time, the addition of the VM Watcher Service made this more likely now since that will usually create a VC client before the Infra secret has started.
Move the VC creds secret into a config param. Previously, the Infra Secret controller was hardcoding the secret name, while we'd otherwise obtain the name from the VMOP ConfigMap. This secret name hasn't changed since day 1 so just move it into our config.
In the fake VM provider, add gets of the config from the context since we now expect and require the config to be …

🐛 Avoid needlessly VC client logout when creds haven't changed

---

controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
pkg/providers/vsphere/virtualmachine/delete.go
pkg/providers/vsphere/virtualmachine/delete_test.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_test.go

This patch prevents VM Op from spawning DestroyVM_Task calls when a VM is not in a connected state. This is an addendum to https://github.com/vmware-tanzu/vm-operator/pull/896.
Fixes `NA`
```release-note
Do not delete non-connected VMs.
```

🌱 Do not delete non-connected VMs

---

pkg/providers/vsphere/vcenter/getvm.go

Properly use errors.Is() instead of As(), as Is() is not just a type comparison (ie, IsA[]()). I knew that but too easy to forget this. The errors.As() usage still worked correct because getVMNotFoundError did not contain any fields, so the underlying == still would match.
Fixes #
```release-note
NONE
```

🐛 Use sentinel not found error in GetVirtualMachine()

---

webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

For classless VMs the validation webhook rejects changes to any fields.  This basically prevents users from making any changes to imported VMs.
```release-note
Allow non-class changes to VM spec for classless VMs
```

:bug: Allow non-class changes to VM spec for classless VMs

---

webhooks/virtualmachine/validation/virtualmachine_validator.go

validateCdrom() was the only pointer receiver for this but it doesn't need to be and this fixes a Goland linter warning.
Fixes #
```release-note
NONE
```

🌱 VM validation validateCdrom() does not need to be pointer receiver

---

webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

This message was split over multiple lines. This might have been a left over from when doValidateWithMsg() was splitting the validation response by "," (since that is what is used to join the individual failure reasons) but that falls apart for messages that have "," in them so we just match by substring instead.
Fixes #
```release-note
NONE
```

🌱 Fix expected error message in VM network validation

---

pkg/util/resize/configspec_devices.go
pkg/util/resize/configspec_devices_test.go
pkg/util/resize/configspec_pci_devices.go
pkg/util/resize/configspec_test.go

For some upcoming work, we'll need to compare fields in the base VirtualDevice/VirtualController (besides the backing) so wire that up now. Commonize how we were doing the was device edited check deviceEdited().
I expect to use the cmp*Edit funcs in some later work so keep them around but add explicit unit tests for them.
Fixes #
```release-note
NONE
```

🌱 Add resize MatchVirtualDevice placeholder

---

config/local/vmoperator/local_env_var_patch.yaml
config/wcp/vmoperator/manager_env_var_patch.yaml
pkg/config/config.go
pkg/config/env.go
pkg/config/env/env.go
pkg/config/env_test.go
pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/session/session_vm_update_test.go
pkg/providers/vsphere/vmprovider_vm_test.go
test/builder/dummies.go
test/builder/vcsim_test_context.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

This PR removes the `ISO Support` FSS related code since it's been enabled on main for a while. The env var for the FSS is retained in the deployment YAML as "true" to avoid breaking internal tests that rely on reading this value.
**Which issue(s) is/are addressed by this PR?** 
Fixes N/A.
Ran `gobuild` internally and verified VMOP deployment from that build.
```release-note
Remove enabled feature state switch for ISO support.
```

🌱 Remove FSS ISO Support

---

pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/session/session_vm_update_test.go
pkg/providers/vsphere/virtualmachine/configspec.go

This is from the early days when we could only update the VM's Firmware - and most things for that matter - after the VM was created since Content Library did not support creating from a ConfigSpec. Since now CL supports that, and some time back I added support in CreateConfigSpec() for the firmware annotation, so the VM is just created with the specified firmware.
Changing the firmware of existing VM is generally not going to result in a booting VM, so at the moment I didn't implement similar support in resize. My preference would be to remove this.
Fixes #
**Are there …

⚠️ Remove UpdateConfigSpecFirmware()

---

pkg/util/vsphere/watcher/watcher.go
pkg/util/vsphere/watcher/watcher_context.go
services/vm-watcher/vm_watcher_service.go
services/vm-watcher/vm_watcher_service_test.go

API server rejects Patch requests when the zone controller is attempting to add a finalizer to the zone, causing the watcher to never start.  And since the watcher is the entity removing the finalizer, the zone stays stuck in deletion forever.  This change skips a zone from being patched if the zone is being deleted.
Additionally, do not watch folders backing a zone if the zone is marked for deletion and the zone does not contain the finalizer.  This can happen in situations where the zone controller has already removed the finalizer after stopping the watcher, but the zone is somehow not removed.
```release-note
Do not patch a zone with finalizer if it is being deleted
```

:bug: Do not patch a zone with finalizer if it is being deleted

---

controllers/virtualmachine/volume/volume_controller.go
controllers/virtualmachine/volume/volume_controller_intg_test.go
controllers/virtualmachine/volume/volume_controller_suite_test.go
controllers/virtualmachine/volume/volume_controller_unit_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

For PVCs that are using a WaitForFirstConsumer StorageClass, set the PVC selected-node annotation to one of the Node names that is in the same Zone as the VM (any Node is sufficient).
Fixes #
```release-note
For VM Volumes that reference a PVC with a WaitForFirstConsumer StorageClass, set the volume.kubernetes.io/selected-node annotation to that of a Node in the VM's Zone.
```

✨ Support PVCs with WFFC StorageClass

---

pkg/providers/vsphere/vmprovider_vm_resize_test.go
pkg/util/vmopv1/resize.go
pkg/util/vmopv1/resize_test.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go

For a classless VM, we'll store an empty class name in the LastResizedAnnotation value. Update ResizeNeeded() to instead compare that empty class name with the existing - now not empty class name - so it will now return that the VM needs a resize.
Fixes #
```release-note
Handle resize of VMs that were originally classless.
```

🐛 Handle resize for VMs that were classless

---

pkg/providers/vsphere/virtualmachine/configspec.go
pkg/providers/vsphere/virtualmachine/configspec_test.go

This patch ensures there are defaults for the ConfigSpec CPU/mem allocation fields for limits and shares.
The documentation for a ResourceAllocation object states that all (VM) fields must be set for certain APIs, including ImportVApp. A part of that API is used by the vpxd placement engine to construct fake VMs in order to support assignable hardware. Therefore:
CPU allocation:
- Ensure limit is set to -1 if there is a reservation.
Memory allocation:
- Ensure shares is not nil.
- Ensure limit is set to -1 if there is a reservation.
Fixes `NA`
**Are there any special notes …

🌱 Defaults for ConfigSpec CPU/mem alloc

---

pkg/util/vsphere/watcher/watcher.go
pkg/util/vsphere/watcher/watcher_context.go
services/vm-watcher/vm_watcher_service.go
services/vm-watcher/vm_watcher_service_test.go

API server rejects Patch requests when the zone controller is attempting to add a finalizer to the zone, causing the watcher to never start.  And since the watcher is the entity removing the finalizer, the zone stays stuck in deletion forever.  This change skips a zone from being patched if the zone is being deleted.
Additionally, do not watch folders backing a zone if the zone is marked for deletion and the zone does not contain the finalizer.  This can happen in situations where the zone controller has already removed the finalizer after stopping the watcher, but the zone is somehow not removed.
This is a crossport of: #913 
```release-note
Do …
```

🐛 (x-port vc-9.0.0) Do not patch a zone with finalizer if it is being deleted

---

controllers/storagepolicyquota/storagepolicyquota_controller.go
pkg/util/kube/spq/spq.go
pkg/util/kube/spq/spq_suite_test.go
pkg/util/kube/spq/spq_test.go
test/builder/dummies.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

Stop also checking the StoragePolicyQuota Status for the StorageClass name since that is only populated by CSI when a StoragePolicyUsage is created. Previously we would not create our VM SPU until the SPQ Status was populated by the pod SPU. This can lead to delays before we would determine that the StorageClass has been associated with the namespace.
Also, do not list all StoragePolicyQuotas during SPQ reconcile.  When reconciling a SQP, we would later end up listing all the SQP in the namespace to determine what storage classes are associated with the policy quota. We don't need to list all the SQPs since each one will be reconciled.
**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes …

🐛 Determine NS associated StorageClass only with Policy ID

---

pkg/providers/vsphere/virtualmachine/configspec.go
pkg/providers/vsphere/virtualmachine/configspec_test.go

Just like the MemoryAllocation.Shares, some changes in PlaceVmsXCluster now requires the Shares to always be set. Simplify some duplicated defaulting code for the CPU and Memory ResourceAllocationInfos.
Fixes #
```release-note
Default ConfigSpec CPU and Memory resource allocation to best-effort, to satisfy PlaceVmsXCluster requirement
```

🐛 Always set ConfigSpec CpuAllocation.Shares field

---

controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_unit_test.go

This patch fixes the way VM usage is reported for StoragePolicyUsage documents. Previously all VMs in a namespace would be summed to find a StoragePolicyUsage document's total usage. In fact only the VMs that use the same StorageClass as the StoragePolicyUsage should be included.
Fixes `NA`
Cross-porting this to 9.0 is going to be manual because of changes to the VM storage status on main. See https://github.com/vmware-tanzu/vm-operator/pull/865 for those changes.
```release-note …
```

🐛 Fix StorageClass usage for VMs

---

controllers/contentlibrary/utils/controller_builder.go

This patch defers the content version check of a VMI to the VMI Cache controller when Fast Deploy is enabled.
This change also allows the Fast Deploy FSS to be enabled after VMIs are already created without having to delete the VMIs and bounce the VM Op controller.
Fixes `NA`
```release-note
NONE
```

🐛 Defer content version check when Fast Deploy

---

controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_unit_test.go

This patch fixes the way VM usage is reported for StoragePolicyUsage documents. Previously all VMs in a namespace would be summed to find a StoragePolicyUsage document's total usage. In fact only the VMs that use the same StorageClass as the StoragePolicyUsage should be included.
Fixes #
```release-note
Do not over-count for when determining StorageClass usage.
```

[x-port 9.0] 🐛 Fix StorageClass usage for VMs

---

go.mod
hack/tools/go.mod

This PR updates VM Operator to use Golang 1.24.2 to fix vulncheck-go reported in CI: https://github.com/vmware-tanzu/vm-operator/actions/runs/14384515971/job/40336445216?pr=933
Fixes N/A.
Another PR will be submitted to the internal cayman_vm-operator repo to upgrade the cayman_go version as well.
```release-note
Golang 1.24.2
```

🌱 Golang 1.24.2

---

pkg/providers/vsphere/virtualmachine/backup.go
pkg/providers/vsphere/virtualmachine/backup_test.go

Currently, during virtual machine backup we make multiple calls to VC to fetch properties. However, these properties have already been fetched as part of the update flow prior to entering the backup flow. This PR removes these additional property fetches.
Fixes #
```release-note
NONE
```

:seedling: Remove duplicate property fetch during backup

---

pkg/providers/vsphere/virtualmachine/configspec.go
pkg/providers/vsphere/virtualmachine/configspec_test.go

For the old standalone VM Class VirtualDevice the generated ConfigSpec by WCP will not have the device key of those devices set. Unfortunately, some recent DRS PlaceVmsXCluster changes made it so that the placement ConfigSpec must have unique device keys. This is stricter than what is accepted for VM creation so DRS should eventually fix that but until that manually assign some device keys.
Fixes #
```release-note
Ensure device keys are set on passthrough devices in the placement …
```

🐛 Set device key for passthrough devices for placement

---

pkg/config/capabilities/capabilities_test.go
pkg/config/capabilities/capabilties.go
pkg/config/config.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

Relax the VM validation webhook so this is not longer treated as immutable with the capability is enabled. Still a lot of work remaining to allow network mutability end to end.
Fixes #
```release-note
NONE
```

🌱 Allow changes to VM Spec.Networks.Interfaces

---

pkg/constants/constants.go
pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_test.go
pkg/vmoperator.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

The VM SetResourcePolicy contains the cluster module info, so if the VM has the special cluster module annotation, enforce that the resource policy is set.  Post create, we only need the VM's resource policy to set the VM cluster module. We really only need if it is not already set but that is not easy to check as this point.
Fixes #
The only user of this is well behaved but otherwise this would have caused a panic.
```release-note
NONE
```

🐛 Require VM ResourcePolicyName when specifying a cluster module

---

config/local/vmoperator/local_env_var_patch.yaml
config/wcp/vmoperator/manager_env_var_patch.yaml
controllers/controllers.go
controllers/infra/controllers.go
controllers/virtualmachine/controllers.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
pkg/config/config.go
pkg/config/default.go
pkg/config/env.go
pkg/config/env/env.go
pkg/config/env_test.go
webhooks/webhooks.go

This PR removes the STORAGE_QUOTA_M2 FSS related code since it's been enabled on main for a while. The env var for the FSS is retained in the deployment YAML as "true" to avoid breaking internal tests that rely on reading this value.
Fixes #
```release-note
Remove enabled FSS STORAGE_QUOTA_M2 from vmoperator code
```

🌱 Remove enabled FSS STORAGE_QUOTA_M2 from vmoperator code

---

controllers/virtualmachineimagecache/virtualmachineimagecache_controller.go
controllers/virtualmachineimagecache/virtualmachineimagecache_controller_test.go
pkg/util/vsphere/library/item_cache.go
pkg/util/vsphere/library/item_cache_test.go

QueryVirtualDiskUuid only works for .vmdk, we need to check if other types exist, such as .nvram
Originally planned to use HostDatastoreBrowser.SearchDatastore via govmomi's [object.Datastore.Stat](https://github.com/vmware/govmomi/blob/a77f0207e1b0281252f37c2f40210b036fe3e7ea/object/datastore.go#L444) method, however:
- Would need to refactor so object.Datastore is plumbed through, instead of string DatastorePath:
`"[DatastoreName] dir/file.ext"`
- Considered using govmomi [object.DatastoreFile.Stat](https://github.com/vmware/govmomi/blob/a77f0207e1b0281252f37c2f40210b036fe3e7ea/object/datastore_file.go#L156), but has the same plumbing issue
- The Datastore HEAD method can use DatastorePath and avoids creating a Task / WaitForUpdates
- Both methods require the same Datastore.Browse …

FastDeploy: Use Datastore method to check if cache files exist

---

api/v1alpha4/virtualmachine_types.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller_unit_test.go
docs/concepts/workloads/vm.md
pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/session/session_vm_update_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

This patch adds support for the following annotations:
* `poweron.check.vmoperator.vmware.com`
This annotation prevents a VM from being powered on until the annotation is removed. Unlike the generic pause annotation, this annotation:
* Does not prevent the VM from being reconciled.
* Can exist multiple times in the format `poweron.check.vmoperator.vmware.com/<COMPONENT>: <REASON>`
This annotation can be applied to new VMs by non-privileged or privileged users. Only privileged users can modify or remove this annotation.
*  `delete.check.vmoperator.vmware.com`
This annotation prevents a VM from being deleted until the annotation is removed. Unlike the generic pause annotation, this annotation:
* Does not prevent the VM from being reconciled.
* …

✨ Support poweron.check and delete.check annotations

---

pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/session/session_vm_update_test.go
pkg/providers/vsphere/vmprovider_vm_test.go

We should be creating the VM with its desired configuration in the first place nowadays so this not needed.
Just comment out the network interface related stuff since it will be reused very soon for network mutability. 
Fixes #
```release-note
Remove remaining remnants of old post-create VM reconfigure.
```

✨ Nuke the old session based class VM updating

---

api/v1alpha2/virtualmachine_network_types.go
api/v1alpha3/virtualmachine_network_types.go
api/v1alpha4/virtualmachine_network_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
pkg/providers/vsphere/network/gosc.go
pkg/providers/vsphere/network/gosc_test.go
pkg/providers/vsphere/network/netplan.go
pkg/providers/vsphere/network/netplan_test.go
pkg/providers/vsphere/network/network.go
pkg/providers/vsphere/network/network_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

Allow setting the Interface Gateway{4,6} to "None" to indicate to not set the gateway that is provided from the underlying network provider in the network configuration. This can be useful when a VM is configured with multiple interfaces.
Remove an incorrect documentation note about the gateway: it is allowed to manually provide IP addresses without a gateway.
Fixes #
```release-note
VM.Spec.Network.Interfaces[].Gateway4 and Gateway6 can be set to "None" to not set the gateway …
```

✨ Add option to not configure gateway on interfaces

---

webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator.go
webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_unit_test.go

Remove the `vm.Spec.Image` check from the storage quota validator. [PR 822](https://github.com/vmware-tanzu/vm-operator/pull/822) introduced a change to the storage quota validating webhook configuration to skip quota validation for imageless VMs. So, this check is not needed as the validator will not be called if the value is not set.
Fixes #
```release-note
NONE
```

:seedling: Cleanup image check from storage quota validator create

---

pkg/providers/vsphere/network/gosc_test.go
pkg/providers/vsphere/network/list_interfaces.go
pkg/providers/vsphere/network/list_interfaces_test.go
pkg/providers/vsphere/network/netplan_test.go
pkg/providers/vsphere/network/network.go
pkg/providers/vsphere/network/network_test.go
pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/session/session_vm_update_test.go
pkg/providers/vsphere/vmprovider_vm2_test.go
pkg/providers/vsphere/vmprovider_vm_test.go
pkg/util/resize/backings.go
pkg/util/resize/backings_test.go
test/builder/vcsim_test_context.go

During power on, determine if any existing network interface need to added and/or removed from the VM, and delete the now orphaned network interface CRs after the VM has been reconfigured.
New interfaces will always get added as vmxnet3 devices.
Fixes #
```release-note
NONE
```

✨ Handle network interfaces changes during VM power on

---

api/utilconversion/fuzztests/conversion_fuzz.go
api/v1alpha1/conversion_test.go
api/v1alpha2/conversion_test.go
api/v1alpha3/conversion_test.go

This patch moves the utilconversion fuzz helpers into a sub-package in order to prevent those helpers from being imported into the dependency graph when building non-test packages.
This helps downstream projects like CSI that import our API module from being impacted by any versioning issues that occur out of the fuzz helper logic.
Fixes `NA`
```release-note
Move API fuzz helpers into sub-package.
```

🌱 Move utilconversion test helpers into pkg

---

webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator.go
webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_unit_test.go

Currently, the Storage Quota validator only returns the capacity of the first disk in the (c)vmi status, whereas it should be returning the sum of the capacities of all disks listed in the image status. This PR fixes this.
Fixes #
```release-note
Return the total capacity of all disks in an image during Storage Quota validation.
```

:bug: Storage Quota validator should return the sum of all disk capacities in image status

---

pkg/config/capabilities/capabilities_test.go
pkg/config/capabilities/capabilties.go
pkg/config/config.go

This PR introduces a new `VMGroups` feature which is set by the Supervisor Capability CRD entry `supports_VM_service_VM_groups`. This will be used to guard the VM Group feature related code.
Verified by deploying this change to an internal testbed with this Supervisor Capability set to true. VMOP logs:
```
I0516 18:14:36.331572       1 main.go:110] "Initial features from environment" logger="setup" features={"InstanceStorage":false,"K8sWorkloadMgmtAPI":false,"PodVMOnStretchedSupervisor":true,"TKGMultipleCL":false,"VMResize":false,"VMResizeCPUMemory":true,"VMImportNewNet":true,"WorkloadDomainIsolation":false,"VMIncrementalRestore":true,"BringYourOwnEncryptionKey":false,"SVAsyncUpgrade":true,"FastDeploy":false,"MutableNetworks":false,"VMGroups" …
```

🌱 Add Capability for VM Groups

---

api/v1alpha2/virtualmachine_network_types.go
api/v1alpha3/virtualmachine_network_types.go
api/v1alpha4/virtualmachine_network_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
pkg/providers/vsphere/network/netplan.go
pkg/providers/vsphere/network/netplan_test.go

This field is not required in the Netplan so also only set it in the generated Netplan if non-zero.
Use Gomega's HaveValue matcher to better assert Netplan fields that are pointers.
Fixes #
```release-note
The Metric field in the VirtualMachineNetworkRouteSpec is optional. Add a validation that if set, the metric must be greater than zero.
```

Make VM Route Metric field optional

---

pkg/builder/constants.go
pkg/builder/validating_webhook.go
pkg/builder/validating_webhook_test.go
pkg/constants/constants.go
webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator.go
webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_intg_test.go

This patch adds support for an annotation, `vmoperator.vmware.com.protected/skip-validation`, that works across all VM Operator objects and allows a privileged user to indicate that the validation webhooks should be skipped for the object to which said annotation is applied.
Please note, this annotation also results in bypassing the quota check for an object.
This is a useful, break-glass feature for fixing up objects in etcd that have gone screwy and need to be updated in ways that would violate the registered, validation webhooks.
Fixes `NA`
**Are there any special notes …

🌱 Support skip-validation annotation

---

webhooks/virtualmachine/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go

With the annotation, we should not add a default interface, but if there are interfaces present, we should still be setting any missing network provider refs.
Fixes #
```release-note
NONE
```

🌱 Ensure network interface provider ref is set even with no default annotation

---

api/v1alpha3/virtualmachine_types.go
api/v1alpha4/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
docs/concepts/workloads/vm.md
docs/ref/api/v1alpha1.md
docs/ref/api/v1alpha2.md
docs/ref/api/v1alpha3.md
docs/ref/api/v1alpha4.md
docs/tutorials/deploy-vm/iso.md

This patch updates the link to the official VMware docs for supported guest IDs.
Fixes `NA`
```release-note
Update link to guest OS identifiers.
```
----
📚 Documentation preview 📚: https://vm-operator--981.org.readthedocs.build/en/981/

📖 Update link to GuestOS IDs

---

pkg/providers/vsphere/network/netplan.go
pkg/providers/vsphere/network/netplan_test.go

It appears there was an upstream change that started to render an MTU of zero as "null" in the netplan configuration which is not valid.
Fixes #
First noticed in Ubuntu 24.04
```release-note
When using cloudinit bootstrap, only set the netplan MTU when greater than zero.
```

🐛 Only set Netplan MTU if a positive value

---

go.mod
go.sum

When vmop has FastDeploy enabled, it can fail transforming ovf to config spec due to govmomi's naming of "lsilogic-sas", rather than "lsilogicsas".
Pulling in this [govmomi fix](https://github.com/vmware/govmomi/pull/3796) supports both names.

deps: Bump govmomi to include CreateSCSIController fix

---

.github/workflows/ci.yml
Makefile
hack/verify-unfocus.sh

This patch adds a GitHub action that fails fast if any test in the pull request has a programattic test focus.
This patch adds a GitHub action that fails fast if any test in the pull request has a programattic test focus.
Fixes `NA`
```release-note
GitHub action fails fast if there is a test with a programmatic focus.
```

🌱 Verify unfocus

---

controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller_intg_test.go
controllers/virtualmachine/virtualmachine/virtualmachine_controller_unit_test.go
pkg/constants/constants.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

This patch adds support for the privileged annotation `vmoperator.vmware.com.protected/skip-delete-platform-resource` that may be used to skip the deletion of an underlying platform resource when the corresponding Kubernetes object is deleted.
This supports use cases such as rollback of import where the underlying VM should not be deleted even though the associated Kubernetes object is.
Fixes `NA`
```release-note
Support …
```

✨ Skip delete platform resource annotation

---

api/v1alpha1/virtualmachine_conversion.go
api/v1alpha1/zz_generated.conversion.go
api/v1alpha2/virtualmachine_conversion.go
api/v1alpha2/zz_generated.conversion.go
api/v1alpha3/virtualmachine_conversion.go
api/v1alpha3/zz_generated.conversion.go
api/v1alpha4/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
docs/ref/api/v1alpha4.md
pkg/providers/vsphere/vmlifecycle/update_status.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_test.go

This patch introduces the field spec.groupName to the VirtualMachine API.
This patch introduces the field spec.groupName to the VirtualMachine API.
Fixes `NA`
```release-note
Introduce spec.groupName to VM API.
```
----
📚 Documentation preview 📚: https://vm-operator--1004.org.readthedocs.build/en/1004/

🌱 Add spec.groupName to VM API

---

api/v1alpha4/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
pkg/providers/vsphere/vmlifecycle/create.go
pkg/providers/vsphere/vmlifecycle/create_fastdeploy.go
pkg/providers/vsphere/vmprovider_vm.go

This patch fixes an issue with how the VM home dir is cleaned up upon a failed fast deploy of a VM. If the VM home dir is already gone, the old code failed with a FileNotFound fault. Now that fault is ignored.
This patch also defaults VMs to use direct mode with Fast Deploy if the VM is using an encrypted storage policy.
Fixes `NA`
```release-note
NONE
```

Graceful VM dir cleanup / crypto+linked

---

config/webhook/manifests.yaml
controllers/virtualmachine/virtualmachinegroup/virtualmachinegroup_controller.go
pkg/constants/constants.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_test.go
webhooks/virtualmachine/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_suite_test.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
webhooks/virtualmachinegroup/mutation/virtualmachinegroup_mutator.go
webhooks/virtualmachinegroup/mutation/virtualmachinegroup_mutator_intg_test.go
webhooks/virtualmachinegroup/mutation/virtualmachinegroup_mutator_suite_test.go
webhooks/virtualmachinegroup/mutation/virtualmachinegroup_mutator_unit_test.go
webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator.go
webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator_intg_test.go
webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator_suite_test.go
webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator_unit_test.go
webhooks/virtualmachinegroup/webhooks.go
webhooks/webhooks.go

This PR updates the VM Group's controller to reconcile changes to `Spec.PowerState`, applying each member's `powerOnDelay` in order. It also adds mutation and validation webhooks for required operations.
In a nutshell, given the following VM Group YAML example:
```yaml
apiVersion: vmoperator.vmware.com/v1alpha4
kind: VirtualMachineGroup
metadata:
name: vmgroup-1
namespace: default
spec:
powerState: PoweredOn
members:   
- kind: VirtualMachine      
name: vm1
powerOnDelay: 1s
- kind: VirtualMachineGroup 
name: vmgroup-2
powerOnDelay: 2s
- kind: VirtualMachineGroup 
name: vmgroup-3
powerOnDelay: 3s
```
The power on sequence will be:
- Power on `vm1` after 1s
- Power on all VMs in `vmgroup-2` after 3s (1s + 2s)
- Power on all VMs in `vmgroup-3` …

✨ VirtualMachineGroup Power State Reconciliation

---

webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator.go
webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator_unit_test.go

This PR updates the VM Group validating webhook to only disallow `lastUpdatedPowerStateTime` annotation change if it's set directly by non-admin users. This ensures the non-admins can still update the VM Group's power state (which triggers the annotation change by mutating webhook) while preventing them from modifying the annotation directly.
While here, also formatted the code to keep line length under 80 chars where possible.
Fixes N/A.
- Updated tests to cover 100% of the validating webhook functionality: 
- Deployed this change to a testbed and verified that non-admin users cannot update the annotation directly, but can update the group's …

🐛 Relax VM Group webhook to allow power state changes

---

pkg/util/resize/backings.go
pkg/util/resize/backings_test.go
pkg/util/resize/configspec_pci_devcies_test.go
pkg/util/resize/configspec_pci_devices.go

This patch fixes how PCI Passthrough devices are handled when their backing is VirtualPCIPassthroughDvxBackingInfo. Previously they would be removed/added during a pre-poweron reconfigure due to the lack of proper device matching. This patch ensures if nothing has changed, the existing devices are not removed/added.
Fixes `NA`
```release-note
Do not remove/add PCI DVX devices on update if nothing has changed.
```

🐛 Fix PCI DVX devs on update

---

api/v1alpha4/virtualmachineclassinstance_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachineclassinstances.yaml
config/rbac/role.yaml
controllers/storagepolicyquota/storagepolicyquota_controller_unit_test.go
controllers/virtualmachineclass/virtualmachineclass_controller.go
controllers/virtualmachineclass/virtualmachineclass_controller_intg_test.go
controllers/virtualmachineclass/virtualmachineclass_controller_suite_test.go
controllers/virtualmachineclass/virtualmachineclass_controller_unit_test.go
pkg/constants/constants.go
test/builder/fake.go

Reconcile VM classes to create VM class instance.  An instance is created with an annotation containing the hash of the ConfigSpec.  Additionally, the instance object also has an OwnerReference to the corresponding class.  The controller ensures that at a time, only the instance mapping to the latest ConfigSpec hash is marked as active.  The active / inactive property is represented by a label to allow clients to query efficiently.
```release-note
Handle VM Class instances during VM class reconcile
```

:sparkles: Handle VM Class instances during VM class reconcile

---

webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

This has broken some E2E tests so temporarily disable those validation checks until this can all be sorted out.
Fixes #
```release-note
NONE
```

🐛 Disable schema not yet upgrade VM validation checks

---

api/v1alpha4/virtualmachine_types.go
api/v1alpha4/virtualmachinegroup_types.go
controllers/virtualmachinegroup/virtualmachinegroup_controller.go
controllers/virtualmachinegroup/virtualmachinegroup_controller_test.go

This PR combines the `reconcileVMMember` and `reconcileVMGMember` functions into a single `reconcileMember` in the VM Group controller, by introducing `VirtualMachineOrGroup` interface. This simplifies the reconciliation logic and reduces duplication, ensuring future updates to member reconciliation are consistent.
This PR also adds the tests in VM Group controller for member and power state reconciliation to improve test coverage.
Fixes N/A.
None.
```release-note
NONE
```

🌱 Consolidate reconcile member and add tests in VM Group controller

---

controllers/controllers.go
pkg/config/capabilities/capabilities_test.go
pkg/config/capabilities/capabilties.go
pkg/config/config.go

This change introduces a new capability for VM snapshots.  This will be leveraged by CCI to determine whether or not snapshot operation on a virtual machine is supported for a given VM.
```release-note
Introduce a capability for VM Snapshots
```

:seedling: Introduce a capability for VM Snapshots

---

pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/vmprovider_vm2_test.go

The VM's network interfaces can be modified when the VM is in the off steady state, so reconcile any differences during that state as well. This isn't strictly required since we will also do this when the VM is in the transitioning to on state, but it is nice to reflect changes before that.
Improve the checks the VM e2e tests to better assert that the Ethernet device is that of what we expect by asserting the External ID and MAC address.
Fixes #
```release-note
NONE
```

🌱 Handle network interface changes when VM is in powered off state

---

pkg/constants/constants.go
pkg/providers/vsphere/virtualmachine/snapshot.go
pkg/providers/vsphere/virtualmachine/snapshot_test.go
pkg/providers/vsphere/vmlifecycle/update_status.go
pkg/providers/vsphere/vmlifecycle/update_status_test.go
pkg/providers/vsphere/vmprovider.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_test.go
test/builder/vcsim_test_context.go

This change adds the capability to revert a VM from a given snapshot. This can be done by the user by modifying the currentSnapshot field of the VM's spec to point to the desired snapshot.
Along with reverting the VM to the given snapshot, we also roll back the VM's Kubernetes state (Spec, Labels, Annotations) to the state that was recorded in the Snapshot.  This is done by leveraging the state recorded for backup / restore.
Other changes include:
- Update the create snapshot workflow to be conditioned on the VM snapshot capability.  Also move the tests to be conditioned on the capability.  Added a test to ensure that if the capability is not enabled, no snapshots are created on the VM.
- A new annotation is added on the VM to indicate when …

:sparkles: Add support for reverting a VM to a given snapshot

---

controllers/virtualmachinesnapshot/virtualmachinesnapshot_controller.go
controllers/virtualmachinesnapshot/virtualmachinesnapshot_controller_intg_test.go
controllers/virtualmachinesnapshot/virtualmachinesnapshot_controller_unit_test.go
pkg/providers/vsphere/virtualmachine/snapshot.go

- Adding the logic to update the vm.status.currentSnapshot. Follow up of https://github.com/vmware-tanzu/vm-operator/pull/1032.
- Previously it updates the vm.spec.currentSnapshot as well. Remove that logic from vmSnapshot controller. 
Fixes #
```release-note
Update vm.status.currentSnapshot in snapshot controller
```

🌱 Update vm.status.currentSnapshot in snapshot controller

---

controllers/storagepolicyquota/storagepolicyquota_controller.go
controllers/storagepolicyquota/storagepolicyquota_controller_intg_test.go
controllers/storagepolicyquota/storagepolicyquota_controller_suite_test.go
controllers/storagepolicyquota/storagepolicyquota_controller_unit_test.go
controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_intg_test.go
controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_unit_test.go
pkg/util/kube/spq/spq.go
pkg/util/kube/spq/spq_test.go

Create a StoragePolicyUsage CR for vmSnapshot specifically so that later we could add snapshot quota related functionality
Fixes #
```release-note
Create a StoragePolicyUsage CR for vmSnapshot 
```

🌱Create StoragePolicyQuota for VMSnapshot

---

api/v1alpha3/virtualmachineimagecache_types.go
api/v1alpha3/zz_generated.conversion.go
api/v1alpha4/virtualmachineimagecache_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachineimagecaches.yaml
controllers/virtualmachineimagecache/virtualmachineimagecache_controller.go
controllers/virtualmachineimagecache/virtualmachineimagecache_controller_test.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/util/vsphere/library/item_cache.go
pkg/util/vsphere/library/item_cache_test.go
pkg/vmconfig/diskpromo/diskpromo_reconciler.go
pkg/vmconfig/diskpromo/diskpromo_reconciler_test.go

This patch updates the VMICache controller to create a top-level directory per cached item. This ensures there is no single, top-level directory per datastore for all cached disks/files. On VSAN, a top-level datastore directory is a volume, and having multiple, concurrent threads read/write to this volume can lead to read/write lock errors.
This patch also updates the disk promotion reconciler to ignore any disks that participate in snapshots. This prevents a VM from constantly being tagged as out-of-sync for disk promotion if the VM has a snapshot.
Finally, this patch causes disk promotion to wait until there is not a pending or running guest customization.
**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue …

🌱 VMICache location / disk promotion ignores snapshots & waits on guest customization

---

api/v1alpha4/virtualmachine_types.go
api/v1alpha4/virtualmachinegroup_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinegroups.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
controllers/virtualmachinegroup/virtualmachinegroup_controller.go
pkg/util/vmopv1/owner_refs.go
pkg/util/vmopv1/owner_refs_test.go
webhooks/virtualmachine/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
webhooks/virtualmachinegroup/mutation/virtualmachinegroup_mutator.go
webhooks/virtualmachinegroup/mutation/virtualmachinegroup_mutator_intg_test.go

This PR updates VM & VMG mutating webhook to remove stale group owner reference when `spec.GroupName` is changed. It also updates the VM Group controller to set owner reference (instead of controller reference) to its members.
Fixes N/A.
Deployed this change to an internal testbed and verified the VM's owner reference to group was added/removed as expected:
- Create a VM in group-1
```console
$ kubectl get vm -n sdiliyaer-test vm-1 -o json | jq '.spec.groupName,.metadata.ownerReferences'
"vmg-1"
[
{
"apiVersion": "vmoperator.vmware.com/v1alpha4",
"kind": "VirtualMachineGroup",
"name": "vmg-1",
"uid": "be2ae38d-539e-4db2-8d36-1519a68b9409"
}
] …
```

🌱 Remove stale owner ref when group name changes

---

pkg/providers/vsphere/vmprovider_vm_group_test.go

This patch fixes an issue where the old OVFReady condition was used in the VM group placement test instead of the new HardwareReady condition. This only occurred because the PR that made the constant change (#1069) was merged without any conflicts, even though it probably should have failed due to the PR merged ahead of it (#1066) that used this condition constant that had been changed.
Fixes `NA`
```release-note
NONE
```

🐛 Fix use of old condition constant

---

api/v1alpha1/zz_generated.conversion.go
api/v1alpha2/zz_generated.conversion.go
api/v1alpha3/zz_generated.conversion.go
api/v1alpha4/virtualmachine_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
pkg/context/virtualmachine_context.go
pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_group_test.go
pkg/providers/vsphere/vmprovider_vm_test.go
pkg/vmconfig/crypto/crypto_reconciler_pre.go
pkg/vmconfig/crypto/crypto_reconciler_pre_test.go
pkg/vmconfig/diskpromo/diskpromo_reconciler.go
pkg/vmconfig/diskpromo/diskpromo_reconciler_test.go

This patch fixes an issue where disks were being promoted twice due to a stale controller cache on systems with heavy load. The disk promotion reconciler depended upon the promo task reference to be written to the VM status, but upon re-entering reconcile, the status.taskRef field may be empty if the cache is not updated.
This fix removes status.taskRef and instead fetches all of a VM's recent tasks at the beginning of each reconcile.
Fixes `NA`
```release-note
NONE
```

🐛 Do not promote disks twice

---

pkg/providers/vsphere/placement/cluster_placement.go

VKS VMs have a very big ExtraConfig payload which causes a ton of logging output. Until we sanitize the EC for placement, bump the log levels to their prior value.
Fixes #
```release-note
NONE
```

🌱 Restore prior placement request/response log levels

---

pkg/constants/constants.go
pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/session/session_vm_update_test.go
pkg/providers/vsphere/vmprovider_vm_test.go
test/builder/dummies.go

A VM's cluster module membership is updated when the VM is switched from off to on. This change adds a new annotation to store the VM's cluster module UUID and updates the membership whenever there is a cluster module change. 
Fixes # N/A
N/A
```release-note
N/A
```

✨ update the CM's membership when the VM is in the steady-state

---

controllers/storagepolicyquota/storagepolicyquota_controller.go
controllers/storagepolicyquota/storagepolicyquota_controller_intg_test.go
controllers/storagepolicyquota/storagepolicyquota_controller_unit_test.go

Any resource related to VMSnapshot should be created only if its feature gate is enabled.
Verified in real env, by default
```
I0808 05:26:24.886316       1 storagepolicyquota_controller.go:160] "Skip creating storage policy usage for resource kind" logger="controllers.StoragePolicyQuota" kind="VirtualMachineSnapshot"
```
Once the feature gate is enabled, SPU is created
```
I0808 05:49:30.072534       1 capabilties.go:172] "Updated features from capabilities" logger="setup" dryRun=false diff="TKGMultipleCL=true,VMSnapshots=true,WorkloadDomainIsolation=true"
k get storagepolicyusage -n lubron-test wcpglobal-storage-profile-vmsnapshot-usage
NAME                                         AGE …
```

🌱 Only create SPU for snapshot when its feature gate is enabled

---

controllers/storagepolicyquota/storagepolicyquota_controller.go
controllers/storagepolicyquota/storagepolicyquota_controller_intg_test.go
controllers/storagepolicyquota/storagepolicyquota_controller_unit_test.go

…#1086)
Any resource related to VMSnapshot should be created only if its feature gate is enabled.
Cross port to 9.0.1 since this commit is already in https://github.com/vmware-tanzu/vm-operator/pull/1046
Fixes #
```release-note
None
```

🌱(xport 9.0.1) Only create SPU for snapshot when its feature gate is enabled (#1086)

---

pkg/context/virtualmachine_context.go
pkg/providers/vsphere/session/session_vm_update.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/vmconfig/crypto/crypto_reconciler_pre.go

This patch adds logging to record the VM's recent tasks when a VM is reconciled. The log level depends on the task's state. If running or in error, the standard level, 2, is used. Otherwise the task is logged at level 4.
This patch also updates `HasVMRunningTask` to ignore certain, well-known tasks that should not prevent VM Op from reconciling desired state.
Fixes `NA`
```release-note
NONE
```

🐛 Log the VM's recent tasks on reconcile / ignore certain tasks

---

api/v1alpha4/virtualmachine_storage_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
go.mod
go.sum
pkg/providers/vsphere/contentlibrary/content_library_utils.go
pkg/providers/vsphere/virtualmachine/cdrom_test.go
pkg/providers/vsphere/vmlifecycle/update_status.go
pkg/providers/vsphere/vmlifecycle/update_status_test.go

Consume new `GetVirtualDiskInfoByUUID` in govmomi introduced by https://github.com/vmware/govmomi/pull/3832 
Now when calculating the usage for VM, it exclude those snapshot related delta disks. Since we will calculate snapshot related usage in VMSnapshot CR instead of VirtualMachine CR.
And for VMI's usage, we still include all chains. Related detail can be found here https://github.com/vmware-tanzu/vm-operator/pull/1083#discussion_r2261235151
**More Info**
Updated VM status when the VM has two snapshots
```
volumes:
- attached: true
diskUUID: 6000C292-3c7a-7cbc-c945-0fb35c5a494b
limit: 10Gi
name: lubron-vm
requested: 10Gi
type: Classic
used: "24117592"
- attached: true
diskUUID: 6000C299-85a3-b188-e22e-3b6c3c3993d6
limit: 5Gi
name: …
```

🌱 Exclude snapshot related disks/files when calculating VM status storage usage

---

pkg/providers/vsphere/network/network.go
pkg/providers/vsphere/network/network_test.go

The fix to enable setting the EthCard ExternalID on non-NSXT DVPDs (NetOP in our case) is partially dependent on ESX host changes, and for upgrades the host version may very much lag of VC/VMOP versions.
The fallout from this is that like before we cannot easily uniquely identify NetOP interfaces so we'll fallback to the old best-effort matching by backing.
Fixes `NA`
```release-note
Disable externalID for NICs on VDS.
```

X-Port 9.0.1 -- 🐛 Disable ExternalID for NetOP interfaces

---

pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_test.go
webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator.go
webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator_unit_test.go

This change modifies the VM snapshot webhook to reject snapshot requests on VKS nodes.  This is done by checking for CAPI added labels on the VKS nodes which is already a contract / pattern that is followed in VM operator for other workflows (e.g., backup).
Since webhook validation based on labels is always race-y, this change also modifies the snapshot reconciliation workflow in the provider to skip taking snapshot of VKS nodes.
```release-note
Prevent snapshot of VKS nodes
```

:seedling: Prevent snapshot of VKS nodes

---

controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
controllers/virtualmachinegroup/virtualmachinegroup_controller.go
controllers/virtualmachinegroup/virtualmachinegroup_controller_test.go
pkg/util/vmopv1/vm.go
pkg/util/vmopv1/vm_test.go

This PR has the following two changes:
1. Add a new mapper func to trigger reconciliation of VMs when their group changes
- ensuring VM status is updated with the group's linked condition as soon as it is adopted by a group
- allowing immediate placement of the VM when the group has placement result ready
2. Updated the existing mapper func to trigger reconciliation of VM Groups when a linked member is updated
- ensuring VM Group's member status reflects the latest state of its members
Fixes N/A.
None.
```release-note
Enqueue reconcile between group to linked VM members.
```

🌱 Enqueue reconcile between groups and linked members

---

webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator.go
webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator_intg_test.go
webhooks/virtualmachinegroup/validation/virtualmachinegroup_validator_unit_test.go

This PR updates the VirtualMachineGroup validating webhook to verify the `spec.bootOrder` field doesn't contain duplicate members or the group itself. This ensures all group members have determined boot order delay.
The webhook also verifies a group's `spec.groupName` to not reference itself either.
Fixes N/A.
Deployed this change to an internal testbed and verified the expected workflow:
- VMG creation with duplicate/self-referenced members:
```console
$ cat vmg-duplicate-members.yaml
apiVersion: vmoperator.vmware.com/v1alpha5
kind: VirtualMachineGroup
metadata:
name: vmg-root
namespace: sdiliyaer-test
spec:
bootOrder:
- members:
- name: vm-1 …
```

🌱 Prevent duplicate and self referenced members in VM Group

---

controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
pkg/providers/fake/fake_vm_provider.go
pkg/providers/vm_provider_interface.go
pkg/providers/vsphere/virtualmachine/publish.go
pkg/providers/vsphere/virtualmachine/publish_test.go
pkg/providers/vsphere/vmprovider.go
pkg/providers/vsphere/vmprovider_vm.go
test/builder/dummies.go

This PR refactors the VirtualMachinePublishRequest flow to allow for publishing a vm as a template to a non-CLS backed library.
Fixes #
```release-note
Add support for publishing a VM to non-CLS backed libraries.
```

✨ Add support for publishing a VM to non-CLS backed libraries

---

controllers/contentlibrary/clustercontentlibraryitem/clustercontentlibraryitem_controller.go
controllers/contentlibrary/contentlibraryitem/contentlibraryitem_controller.go

Work had already been done to refactor the ContentLibraryItem and ClusterContentLibraryItem controllers to use the v1alpha2 ImageRegistry API. This PR enables these controllers by uncommenting the block where `AddToManager` is invoked.
Fixes #
```release-note
NONE
```

:seedling: Enable v1a2 (cluster)contentlibraryitem controller(s)

---

webhooks/virtualmachinepublishrequest/validation/virtualmachinepublishrequest_validator.go
webhooks/virtualmachinepublishrequest/validation/virtualmachinepublishrequest_validator_unit_test.go

Fixes #
```release-note
NONE
```

:seedling: Allow v1alpha2 spec.target.location.apiVersion in VirtualMachinePublishRequest validating webhook

---

api/test/v1alpha1/conversion_test.go
api/test/v1alpha2/conversion_test.go
api/test/v1alpha3/conversion_test.go
api/test/v1alpha4/conversion_test.go
api/v1alpha1/groupversion_info.go
api/v1alpha2/groupversion_info.go
api/v1alpha3/groupversion_info.go
api/v1alpha4/groupversion_info.go
external/byok/api/v1alpha1/groupversion_info.go
external/capabilities/api/v1alpha1/groupversion_info.go

When trying to convert unstructured object (v1alpha4.VM) to v1alpha5.VM running
```
k8sClient.Scheme().Convert(unstructuredObj, vm, nil) 
```
Got below error
```
failed to reconcile snapshot revert: converting (v1alpha4.VirtualMachine) to (v1alpha5.VirtualMachine): unknown conversion 
```
This is because here https://github.com/vmware-tanzu/vm-operator/blob/8cd71daf2c6142ddef8329f0bfa1082ed367676a/api/v1alpha4/groupversion_info.go#L29
```
localSchemeBuilder = schemeBuilder
```
localSchemeBuilder is a copy, not a pointer to schemeBuilder. 
While code here https://github.com/vmware-tanzu/vm-operator/blob/8cd71daf2c6142ddef8329f0bfa1082ed367676a/api/v1alpha4/zz_generated.conversion.go#L32 register the func to the copy. 
``` …
```

🐛Register conversion function to pointer of scheme

---

controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_intg_test.go
controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller_unit_test.go

Now I could see error in VMOP reconciling SPU for snapshot even the feature is not enabled. It doesn't cause issue, just producing red herring error log.
1. Updated logic to only reconcile SPU for VMSnapshot when the feature is enabled.
2. Updated test cases to test cases when snapshot feature is enabled or not.
**Testing**
Verified after turn off the snapshot feature flag, VMOP no longer reports error of not finding SPU for snapshot
```release-note
None
```

🐛Only reconcile SPU for Snapshot when feature is enabled

---

api/v1alpha2/virtualmachine_types.go
api/v1alpha2/virtualmachinegroup_types.go
api/v1alpha3/virtualmachine_types.go
api/v1alpha3/virtualmachinegroup_types.go
api/v1alpha4/virtualmachine_types.go
api/v1alpha4/virtualmachinegroup_types.go
api/v1alpha5/virtualmachine_types.go
api/v1alpha5/virtualmachinegroup_types.go
controllers/virtualmachinegroup/virtualmachinegroup_controller.go
controllers/virtualmachinegroup/virtualmachinegroup_controller_test.go
pkg/providers/vsphere/vmlifecycle/update_status.go
pkg/providers/vsphere/vmlifecycle/update_status_test.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_test.go
pkg/util/vmopv1/vmgroup.go
pkg/util/vmopv1/vmgroup_test.go

This PR updates the VirtualMachineGroup controller to set the group linked condition if a group belongs to another group (i.e. `VMG.Spec.GroupName` is not empty).
This PR also refactors the existing logic for updating the VM's group linked condition by using a single `UpdateGroupLinkedCondition()` function for both VM and VMG kind members via the `VirtualMachineOrGroup` type.
Fixes N/A.
Deployed this change to an internal testbed and verified both VM & VMG group linked condition as follows:
- Created a group with empty `Spec.GroupName` (no group linked condition)
```yaml
status:
conditions:
- lastTransitionTime: "2025-08-22T14:18:54Z"
message: …
```

🌱 Set group linked condition for nested child groups

---

pkg/providers/vsphere/vmprovider.go
pkg/providers/vsphere/vmprovider_test.go

Fixes #
There is a gap in what was delivered in https://github.com/vmware-tanzu/vm-operator/commit/7199b4bcd933945bef12469b94c34a90dee72589 and what was delivered in https://github.com/vmware-tanzu/vm-operator/commit/529ce6757ffd73cd7bba108fa1456fb3c5b4ac56 and https://github.com/vmware-tanzu/vm-operator/commit/fe407bb79e359987988a0da2a4fea41b7093bbbe
As a result, v1alpha2 ContentLibraryItems are failing this check https://github.com/vmware-tanzu/vm-operator/blob/main/pkg/providers/vsphere/vmprovider.go#L202 called by …

:bug: Update SyncVirtualMachineImage check to account for v1alpha2 ContentLibraryItem and ClusterContentLibraryItem types

---

pkg/providers/vsphere/virtualmachine/configspec.go
pkg/providers/vsphere/virtualmachine/configspec_test.go

This change augments the VM-VM zonal affinity (both required and preferred) workflows to add support for specifying MatchExpressions along with MatchLabels.
```release-note
Support MatchExpressions when specifying VM-VM zonal affinity
```

:seedling: Support MatchExpressions when specifying VM-VM zonal affinity

---

api/v1alpha5/virtualmachinepublishrequest_types.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
pkg/providers/vsphere/virtualmachine/publish.go
pkg/providers/vsphere/vmlifecycle/create_fastdeploy.go

The PR adds the VM publish request's UUID to the cloned VM template's extra configurations, so it could be used to verify if the VM template is associated with a VM publish request. The UUID extra configuration is removed when the VM template is used for creating a new VM. 
Fixes # N/A
More integration tests will be added once the final end-to-end flow for publishing an inventory VM is complete.  
```release-note
N/A
```

 🌱 Verify  if a VM Template is Associated with a VM Publish Request

---

pkg/providers/vsphere/virtualmachine/publish.go

Fixes #
```release-note
Preserve ExtraConfig when publishing a VM to Content Library OVF
```

:bug: Add flag to OVF CreateSpec to preserve ExtraConfig

---

controllers/virtualmachinesnapshot/virtualmachinesnapshot_controller.go
pkg/providers/vsphere/virtualmachine/snapshot_test.go
pkg/providers/vsphere/vmlifecycle/update_status.go
pkg/providers/vsphere/vmprovider_vm_snapshot.go
pkg/providers/vsphere/vmprovider_vm_test.go
pkg/util/kube/vmsnapshot.go
pkg/util/kube/vmsnapshot_test.go
test/builder/dummies.go

There is chance that the VM Spec's content of a Snapshot doesn't have the VM with latest apiVersion. When revert to snapshot, this PR extracts and converts the spec to latest (v1alpha5) version of VM.
Also fix the powerstate, it should match what the `vmsnapshot.spec.memory` is set, not the state of the vm
This can't be unit tested since snapshot.config is immutable.
Test in e2e env instead
Testing done:
Have a v1alpha4 env, create a vm, create a snapshot, then upgrade vmop to this commit. Then try revert VM
```
I0828 00:22:12.168815       1 vmprovider_vm.go:1447] "Restoring VM spec from snapshot" logger="virtualmachine-controller" VirtualMachine="lubron-test/lubron-vm" …
```

✨ Convert VM in extra config of snapshot to newest APIVersion

---

api/v1alpha5/virtualmachine_types.go
pkg/constants/constants.go
pkg/providers/vsphere/vmprovider_vm_snapshot.go
pkg/providers/vsphere/vmprovider_vm_test.go
pkg/providers/vsphere/vmprovider_vm_utils.go

When a snapshot revert operation fails, we now emit a condition on the VirtualMachine object to indicate the failure. This condition provides details about the failure, allowing users to understand the reason behind the unsuccessful revert attempt.
Once the revert operation fails, users will see a condition named `VirtualMachineSnapshotRevertSucceeded` set to `False` on the VirtualMachine object. The condition's message will contain information about the error encountered during the revert process.
Also, enhances documentations for the `VirtualMachineSnapshotRevertInProgressAnnotationKey` to clarify its behavior in failure scenarios.
**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes …

🌱  Emit a condition for a failed snapshot revert operation

---

pkg/providers/vsphere/vmprovider_vm_snapshot.go
pkg/providers/vsphere/vmprovider_vm_test.go
test/builder/dummies.go

For non-imported snapshots, so far the power state was being taken from the backed up VM YAML in ExtraConfig for the snapshot. This might not be the correct power state because, for example, in the case when one takes a snapshot of a Powered On VM without it's memory state, the snapshot power state would be off. The VM's resultant power state post revert should also be off.
None
```release-note
Reverts a VM to the same power state as that of the snapshot
```

🌱 Reverts a VM to the same power state as that of the snapshot

---

controllers/virtualmachine/volume/volume_controller.go
controllers/virtualmachine/volume/volume_controller_unit_test.go
pkg/config/capabilities/capabilities.go
pkg/config/capabilities/capabilities_test.go
pkg/config/config.go

This capability was only added for CCI support, and the local changes CSI maintains for the selected-node-is-zone annotation does not have a corresponding cap flag, but go ahead and add a basic check during our PVC WFFC reconciliation.
Fixes #
```release-note
NONE
```

🌱 Add PVC WFFC capability

---

controllers/virtualmachine/volume/volume_controller.go
controllers/virtualmachine/volume/volume_controller_intg_test.go

For WFFC PVCs set the selected-node annotation before the check for single stepping the attachments, so ideally we can update all the PVCs together to reduce the total time needed to bind all of the PVCs.
Fixes #
```release-note
NONE
```

🌱 Update WFFC PVCs earlier in volume reconciliation

---

pkg/providers/vsphere/network/network.go

NetOP will update the NetworkInterface Spec with the default network name so we don't want to then clear it.
Noticed when tracking down the cause of NetworkInterface with a high generation count.
Fixes #
```release-note
NONE
```

🐛 Do not unset NetOP network name with default network

---

controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_intg_test.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
pkg/context/virtualmachinepublishrequest_context.go
pkg/providers/fake/fake_vm_provider.go
pkg/providers/vm_provider_interface.go
pkg/providers/vsphere/virtualmachine/publish.go
pkg/providers/vsphere/vmprovider.go
pkg/providers/vsphere/vmprovider_vm.go

There was an issue where a VM Publish Request to an inventory-backed Content Library was not being marked completed. This was due to a call to CLS failing during the check for the vmi. This check needed to be updated to account for non-CLS backed libraries in order to allow for this check to succeed.
Fixes #
```release-note
NONE
```

:bug: Fix issue where publish requests to inventory-backed CL was not marked complete

---

pkg/config/capabilities/capabilities.go
pkg/config/capabilities/capabilities_test.go
pkg/config/config.go

This patch introduces a new 'VMSharedDisks' feature that is set by the Supervisor Capability CRD entry
'supports_shared_disks_with_VM_service_VMs'. The 'VMSharedDisks' feature will be used to guard code changes relate to shared disks, mainly to support Oracle RAC and Microsoft WSFC workloads.
Testing:
- When the capability is deactivated. 
- When the capability is activated. 
Fixes # N/A
N/A
```release-note
Add Capability for shared disks
```

🌱 Add Capability for shared disks

---

controllers/virtualmachinesnapshot/virtualmachinesnapshot_controller.go
pkg/providers/vsphere/virtualmachine/snapshot.go
pkg/providers/vsphere/virtualmachine/snapshot_test.go
pkg/providers/vsphere/vmlifecycle/update_status.go
pkg/providers/vsphere/vmprovider_vm.go
pkg/providers/vsphere/vmprovider_vm_snapshot.go
pkg/providers/vsphere/vmprovider_vm_test.go
pkg/util/kube/vmsnapshot.go
pkg/util/kube/vmsnapshot_test.go
pkg/util/vmopv1/vm.go
pkg/util/vmopv1/vm_test.go
pkg/vmconfig/diskpromo/diskpromo_reconciler_test.go

Refactoring snapshot code
1. Change `FindSnapshot` to return `VirtualMachineSnapshotTree` instead of `ManagedObjectReference`.
2. Change `SnapshotVirtualMachine` to return `VirtualMachineSnapshotTree` so following tasks could use it.
3. Not update `vmCtx.MoVM` while doing Property() call to fetch "snapshot" property, since `vmCtx.MoVM` will be shared by all the reconcile functions in updateVirtualMachine
4. Remove `FindSnapshotInTree` and `GetParentSnapshot` since they are not used anymore
5. `PatchSnapshotSuccessStatus` uses snapshot.state as source of truth to get powerstate
6. Add `ConvertPowerState` func to convert  `vimtypes.VirtualMachinePowerState` to `vmopv1.VirtualMachinePowerState`
7. Some logging clean up
**Please add a release …

🌱Refactor some snapshot related code

---

go.mod

Golang released CVE GO-2025-3956 which is addressed in 1.24.6.  Bump up to the latest version of 1.24.
```release-note
Bump up golang version to handle CVE GO-2025-3956
```

:seedling: Bump up golang version to handle CVE GO-2025-3956

---

webhooks/virtualmachine/mutation/virtualmachine_mutator.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_intg_test.go
webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go

Auto fill PVC's config based on the application type.
Referenced from the API definition [here](https://github.com/vmware-tanzu/vm-operator/blob/main/api/v1alpha5/virtualmachine_storage_types.go#L106-L124)
```
//   - OracleRAC      -- The volume is configured with
//                       diskMode=IndependentPersistent and
//                       sharingMode=MultiWriter
//   - MicrosoftWSFC  -- The volume is configured with
//                       diskMode=IndependentPersistent
```
```release-note
Add mutating webhook for rac and wsfc workload
```

🌱Add mutating webhook for rac and wsfc workload

---

docs/tutorials/deploy-vm/cloudinit.md

Fix a typo in the documentation.
```release-note
NONE
```
----
📚 Documentation preview 📚: https://vm-operator--1197.org.readthedocs.build/en/1197/

:bug: Fix typo in cloud-init docs

---

config/crd/patches/webhook_in_clustervirtualmachineimages.yaml
config/crd/patches/webhook_in_virtualmachineclasses.yaml
config/crd/patches/webhook_in_virtualmachineimages.yaml
config/crd/patches/webhook_in_virtualmachinepublishrequests.yaml
config/crd/patches/webhook_in_virtualmachines.yaml
config/crd/patches/webhook_in_virtualmachineservices.yaml
config/crd/patches/webhook_in_virtualmachinesetresourcepolicies.yaml
config/crd/patches/webhook_in_virtualmachinewebconsolerequests.yaml

Remove caBundle from conversion webhook defs
This is a x-port of #649 for the upcoming patch release on 8.0 U3.
```release-note
Remove caBundle from conversion webhook defs
```

[x-port] Remove caBundle from conversion webhook defs

---

api/v1alpha5/virtualmachinepublishrequest_types.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller_unit_test.go
pkg/providers/vsphere/virtualmachine/extraconfig.go
pkg/providers/vsphere/virtualmachine/extraconfig_test.go
pkg/providers/vsphere/virtualmachine/publish.go
pkg/providers/vsphere/virtualmachine/publish_test.go
pkg/providers/vsphere/vmprovider_vm.go

This PR adds logic to the VirtualMachinePublishRequest controller to handle encrypted VMs when publishing to an inventory-back ContentLibrary. There are three pieces:
- Encrypted VMs cannot be published to content library whose storage class does not support encryption
- Publish requests whose source VMs have a mix of encrypted and unencrypted disks will be rejected
- For encrypted VMs which are allowed, we set the storage policy of the target content library on each of the disks in the configSpec that is passed into the cloneSpec
Fixes #
**Are there any special notes for …

Handle publishing of encrypted VMs for inventory-backed ContentLibraries

---

webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

Previously we would restrict we restrict the bootstrap to only be changed with the VM was "off", but there isn't really a good reason to do so. The customization will be applied on the next powering on transition. Instead, just restrict the bootstrap provider type from being changed.
Remove a bogus "network can't change while powered on" test: this was just testing network mutability or not since we had no network related checks for just powered on.
Fixes #
```release-note
Allow …
```

🌱 Allow VM Spec.Bootstrap to be mutable

---

pkg/providers/vsphere/sysprep/secret.go
pkg/providers/vsphere/sysprep/secret_test.go

Setting the password with Sysprep does not require AutoLogin, but AutoLogon requires the password to be set. The validation webhook was correct but the check to later determine if the password was set was incorrect.
Fixes #
```release-note
Setting the administrator password with inline Sysprep should not require AutoLogin to be true 
```

🐛 Fix setting Sysprep password without AutoLogin

---

pkg/vmprovider/providers/vsphere2/session/session_vm_update.go
pkg/vmprovider/providers/vsphere2/session/session_vm_update_test.go

This patch fixes how PCI Passthrough devices are handled when their backing is VirtualPCIPassthroughDvxBackingInfo. Previously they would be removed/added during a pre-poweron reconfigure due to the lack of proper device matching. This patch ensures if nothing has changed, the existing devices are not removed/added.
Fixes `NA`
```release-note
Do not remove/add PCI DVX devices on update if nothing has changed.
```

🐛 x-port 8.0.3: Fix PCI DVX devs on update

---

webhooks/virtualmachine/validation/virtualmachine_validator.go
webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go

Add a few webhook validations for parity fields when capability is not enabled.
Fixes #
```release-note
NONE
```

🌱 Disallow LinuxPrep password when VCD parity is not enabled

---

api/v1alpha2/virtualmachinegroup_types.go
api/v1alpha2/zz_generated.conversion.go
api/v1alpha3/virtualmachinegroup_types.go
api/v1alpha3/zz_generated.conversion.go
api/v1alpha4/virtualmachinegroup_types.go
api/v1alpha4/zz_generated.conversion.go
api/v1alpha5/virtualmachinegroup_types.go
config/crd/bases/vmoperator.vmware.com_virtualmachinegroups.yaml
controllers/virtualmachinegroup/virtualmachinegroup_controller.go
controllers/virtualmachinegroup/virtualmachinegroup_controller_test.go
pkg/providers/vsphere/vmprovider_vm_group.go
pkg/providers/vsphere/vmprovider_vm_group_test.go

This PR updates the VM Group controller during group placement reconciliation by: 
- Skipping VM members that already have the `topology.kubernetes.io/zone` label, preventing unnecessary DRS placement (VM controller already ignores the group placement result for these VMs).
- Reassigning placement for VM members whose UID does not match the group member status, ensuring accurate placement status when a VM is recreated with the same name but not removed from the group.
All the required API changes are backported to v1alpha2 to maintain compatibility with VKS (still on v1a2).
**Which issue(s) is/are addressed by this PR?** 
Fixes N/A.
- Rewrote the group placement tests to verify all the cases …

🌱 Skip VM with zone label and address recreated VM in group placement

---

pkg/config/capabilities/capabilities.go
pkg/config/capabilities/capabilities_test.go

This patch sets VSpherePolicies feature based on
supports_iaas_compute_policies Supervisor capability.
Fixes # N/A
N/A
```release-note
NONE
```

🌱 Add capability for VSphere policies
