vmware-tanzu/vm-operator

- config/local/vmoperator/local_env_var_patch.yaml
- config/wcp/vmoperator/manager_env_var_patch.yaml
- controllers/webconsolerequest/webconsolerequest_controller.go
- controllers/webconsolerequest/webconsolerequest_intg_test.go
- controllers/webconsolerequest/webconsolerequest_unit_test.go
- hack/deploy-wcp.sh
- pkg/lib/env.go
- pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
- webhooks/virtualmachineclass/validation/virtualmachineclass_validator_unit_test.go
- webhooks/webconsolerequest/validation/webconsolerequest_validator.go
- webhooks/webconsolerequest/validation/webconsolerequest_validator_intg_test.go
- webhooks/webconsolerequest/validation/webconsolerequest_validator_unit_test.go
remove unused FSS
- WCP_VMService_Public_Cloud_BYOI (enabled in main),
- WCP_VMService (enabled in main),
- WCP_VMService_UnifiedTKG_BYOI (replaced by WCP_Unified_TKG)
> Remove unused FSS 

- pkg/vmprovider/providers/vsphere/session/session_vm_update.go
- pkg/vmprovider/providers/vsphere/session/session_vm_update_test.go
- pkg/vmprovider/providers/vsphere/vmprovider_vm.go
- pkg/vmprovider/providers/vsphere/vmprovider_vm_test.go
We should not completely fail the VM reconcile if the VM image goes away. This change includes:
- When update VM, best effort to get VM image status and do not return any error.
- Check if VM image status is empty when getting VM image.
- Update extra config based on VM image status. Return error if
- image status is nil, while JSON_EXTRA_CONFIG exists in the global config but is missing from VM config.
- image status is nil, VM metadata is not cloud-init and defer cloud-init config key exists in the VM config.
Test done:
- make test
- make test-integration
- WCP env: 
Manually verified:
- Deploy a VM using vmi vmi-8ba052935d29cd377:
```
root@423fc941a1a0ea2ff656bc3b2a1ef962 [ ~ ]# k get vm vm-ubuntu-1 -n test-ns -ojsonpath={.spec.imageName}
vmi-8ba052935d29cd377 …
```
> Best effort to update VirtualMachine

- pkg/vmprovider/providers/vsphere/session/session_vm_customization.go
- pkg/vmprovider/providers/vsphere/session/session_vm_customization_test.go
This patch ensures that the vAppConfig transport is set to GuestInfo when a user selects the CloudInit transport with the CloudInit prep option.
This ensures that CloudInit(Prep) works even if a user selects a VM Class that does not have a CD-ROM and VM Image where the vAppConfig transport is set to ISO.
This patch basically apes https://github.com/vmware-tanzu/vm-operator/commit/92e73100916ec8a1ed22ce8ccbdd17aa3ffb29c8, which solved the same issue for the `OvfEnv` and `vAppConfig` transports.
This patch was validated by:
1. Replacing VM Operator on a running Supervisor with an image built with this patch.
1. A new VM was deployed:
```yaml
apiVersion: v1
kind: Secret
metadata:
name: my-vm-bootstrap-data
namespace: my-namespace
stringData:
user-data: |
#cloud-config
ssh_pwauth: true
users: …
```
> Set CloudInit(Prep) transport to GuestInfo

- docs/index.md
- docs/user-guide/bootstrap.md
- docs/user-guide/examples/demo.md
- mkdocs.yml
This patch provides an initial take on documenting the VM Op bootstrap providers.
> Bootstrap Provider Docs

- Makefile
- hack/deploy-local.sh
While here, fix sleep usage to work with non-GNU sleep command.
> Update kind k8s version to 1.24

- pkg/vmprovider/providers/vsphere/session/session_vm_update.go
This patch skips reconfiguring a suspended VM prior to it being powered on since suspended VMs cannot tolerate many different kinds of reconfiguration.
Fixes `NA`
Related to #152
```release-note
Skips reconfigure when powering on a suspended VM.
```
> Do not reconfig suspended VM pre power-on

- Makefile
This patch updates the `generate-go-conversions` target to support either Symlink (default) or Docker as a fallback for running the `conversion-gen` tool when the local sources are not cloned in the path expected by said tool.
The env var `CONVERSION_GEN_FALLBACK_MODE` may be used to set the fallback mode. This defaults to `symlink`, but can also be set to `docker`.
Fixes `NA`
The fastest way to verify this PR's symlink mode is with Docker:
```shell
GOLANG_IMAGE="golang:$(go env GOVERSION | cut -c3-)" && \
[ "$(go env …
```
> ✨ Use Symlink or Docker for generate-go-conversions fallback

- docs/concepts/workloads/vm.md
Adds documentation to explain the various resources of a VM such as CPU, memory, storage and network.
Fixes #105 
N/A
```release-note
NONE
```
----
:books: Documentation preview :books:: https://vm-operator--189.org.readthedocs.build/en/189/
> 📖  Documentation for VM's resources (CPU, Memory, Storage and Network)

- config/webhook/manifests.yaml
- test/builder/utila2.go
- webhooks/virtualmachinewebconsolerequest/v1alpha2/validation/webconsolerequest_validator.go
- webhooks/virtualmachinewebconsolerequest/v1alpha2/validation/webconsolerequest_validator_intg_test.go
- webhooks/virtualmachinewebconsolerequest/v1alpha2/validation/webconsolerequest_validator_suite_test.go
- webhooks/virtualmachinewebconsolerequest/v1alpha2/validation/webconsolerequest_validator_unit_test.go
- webhooks/virtualmachinewebconsolerequest/v1alpha2/webhooks.go
- webhooks/virtualmachinewebconsolerequest/webhooks.go
Adds the v1a2 webconsolerequest validation webhooks and tests. 
Fixes #
N/A
N/A
```
```
> ✨ Add v1a2 webconsolerequest validation webhooks

- config/crd/kustomization.yaml
This change includes the v1a2 webconsole CRD in the combined manifest.
Fixes # N/A
N/A
```
N/A
```
> 🌱Include the v1a2 webconsole CRD in the combined CRD manifest

- pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status.go
- pkg/vmprovider/providers/vsphere2/vmlifecycle/update_status_test.go
Try to not show interfaces and IPs that aren't informative. On TKG nodes especially there will a lot of pseudo interface and routes that just make the output hard to read.
This is just the first pass and we'll likely need more refinement later.
```release-note
In the v1a2 Status.Network, certain devices and routes are not shown to reduce clutter. Specifically, pseudo devices and link and interface local routes are skipped.
```
> ✨ Reduce some clutter in v1a2 Status.Network

- pkg/vmprovider/providers/vsphere2/network/network.go
- pkg/vmprovider/providers/vsphere2/network/network_test.go
- webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
- webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
This change checks for v1a1 network named interfaces before creating or updating netIfs with the new naming convention.
Fixes # N/A
N/A
```
N/A
```
> ✨ Finalize network v1a2 naming convention

- api/v1alpha1/virtualmachine_conversion.go
In v1a1 we added the VsphereVolume to allow the resize of the OVF disks. It was something done quickly, and really never ended up being used, and the interface isn't very user friendly for general purpose for "VM Service" VMs. In v1a2 we just have a single field for resizing the boot disk. As best as we're able to propagate the boot disk field across versions.
```release-note
The v1alpha1 VM Spec.Volumes.VsphereVolumes has been replaced in v1alpha2 VM Spec.Advanced.BootDiskCapacity
```
> ✨ Version conversion support for v1a2 BootDiskCapacity

- webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
- webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
This change adds validation on Bootstrap vAppConfig Properties.
1) `Key` is required field https://github.com/vmware-tanzu/vm-operator/blob/main/api/v1alpha2/common/types.go#L75
2) `Value` is optional and is `ValueOrSecretKeySelector`, In which `From` and `Value` is mutually exclusive. https://github.com/vmware-tanzu/vm-operator/blob/main/api/v1alpha2/common/types.go#L49
Fixes # N/A
```release-note
Add validation on Bootstrap vAppConfig Properties
```
> :seedling:Add validation on Bootstrap vAppConfig Properties

- controllers/contentlibrary/v1alpha2/clustercontentlibraryitem/clustercontentlibraryitem_controller_intg_test.go
Fixes the reason when asserting the failure reason for CVMI workflow
n/a
Test changes only
```release-note
NONE
```
> 🐛 Fixes the reason to assert for CVMI workflow

- .github/workflows/notify-gchat-on-issue-comment.yml
- .github/workflows/notify-gchat-on-issue.yml
- .github/workflows/notify-gchat-on-pr.yml
This patch adds workflows to notify the wcp-vmservice-dev channel on Google Chat when there is activity related to issues, issue comments, and PRs. Due to the nature of testing workflows, these were validated in the repo https://github.com/akutz/validate-notify-gchat. Please see its action history for validation.
Fixes `NA`
These workflows can _absolutely_ be improved upon. This is just an initial stab at them to ensure the channel is notified when issues/PRs are opened. …
> ✨ Notify Google Chat workflows

- api/v1alpha1/conversion_test.go
- api/v1alpha1/virtualmachine_conversion.go
Fixes b54465
```release-note
NONE
```
> 🐛 Check probe spec pointers for nil during conversion

- .github/workflows/gnotify.py
See if this fixes it
```release-note
NONE
```
> 🌱 Fix getting the user login in MR opened action

- pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils.go
- pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
>  ✨ Honor SecretKeySelector Optional in v1a2 bootstrap

- api/v1alpha1/virtualmachineimage_conversion.go
When the v1a2 FSS is enabled, all VMI and CVMIs are missing the conditions when requesting a v1a1 object. This patch introduces a fix wherein when no false conditions are reported during the down conversion of a VMI (or CVMI), it sets all the child conditions as True.
Also, the latest transition time for True conditions was missing during the down conversion. To fix that, we set the transition time from the Ready condition to each of the child conditions since we do not have the individual times for each of those conditions anymore.
n/a
**Are there any special notes for …
> 🐛 Fixes VMI/CVMI condition conversion

- docs/tutorials/deploy-apps/README.md
- docs/tutorials/deploy-apps/nfs-server-and-client.md
- mkdocs.yml
This patch adds documentation for a tutorial on how to deploy an NFS server and client based on an Ubuntu image.
Fixes `NONE`
```release-note
Tutorial on deploying an NFS server that exports mounts via a VirtualMachineService and client that mounts them
```
----
📚 Documentation preview 📚: https://vm-operator--319.org.readthedocs.build/en/319/
> 📖 Tutorial on deploying NFS server/client

- .github/workflows/ci.yml
- .github/workflows/gnotify.yml
- .github/workflows/post-coverage-to-pr.yml
- .github/workflows/testing-needed.yml
This patch updates the version of several GitHub actions, including the ones responsible for checkout, setting up Go and Python, etc.
Fixes `NA`
```release-note
NONE
```
> 🌱 Update GitHub actions versions

- .github/workflows/ci.yml
- Makefile
This patch adds a GitHub action to verify the site's docs can be successfully built with mkdocs.
Fixes `NONE`
```release-note
NONE
```
> ✨ GitHub action to verify docs

- api/v1alpha1/virtualmachine_conversion.go
- api/v1alpha1/virtualmachine_conversion_test.go
There will likely be some upcoming changes on how the v1a1 PrereqReady condition is handled and filtered out but add some tests first.
```release-note
NONE
```
> 🌱 Add tests for VM Condition version conversion

- pkg/vmprovider/providers/vsphere2/vmprovider_vm2_test.go
Use the existing "E2E" VM tests also test the common bootstrap types. This addresses most of the code coverage in DoBootstrap(). Prior to b60ed71f8e, these only used the CloudInit bootstrap.
```release-note
NONE
```
> 🌱 Add back bootstrap config to VMs in vmE2ETests()

- pkg/metrics2/constants.go
- pkg/metrics2/vmservice_metrics.go
> 🌱 Use v1a2 VM created condition to infer metrics phase

- api/v1alpha1/virtualmachine_conversion.go
- api/v1alpha1/virtualmachine_conversion_test.go
If we have a v1a1 PrereqReady condition we can use that to fill in the similar v1a2 Conditions.
Also remove the PrereqReady condition from the v1a2 Conditions
Fixes # N/A
N/A
```
```
> Use the v1a1 PrereqReady condition to populate v1a2 conditions

- .github/workflows/ci.yml
Run CI workflows on PRs to the release branches
Fixes # N/A
N/A
```NONE
```
> 🌱 Run ci on PRs to the release branches

- .github/workflows/ci.yml
Run ci on PRs to the release branches
Fixes # N/A
N/A
```NONE
```
> 🌱Run ci workflows for PR created on release branches

- webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
> 🌱 Remove dup validate instance stoarge call in VM webhook update

- config/rbac/role.yaml
- controllers/virtualmachine/v1alpha1/virtualmachine_controller.go
- controllers/virtualmachine/v1alpha2/virtualmachine_controller.go
- webhooks/virtualmachine/v1alpha1/mutation/virtualmachine_mutator.go
- webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
Storagepolicyquota should be plural. Remove singular virtualmachine that didn't end up mattering since we have several virtualmachines elsewhere.
```release-note
NONE
```
> 🐛 Remove singular role resource names

- external/ncp/api/v1alpha1/virtualnetwork_types.go
- pkg/config/config.go
This PR introduces new network provider type as NSXT_VPC. 
Fixes N/A
```release-note
Introduce new network provider type as NSX_VPC
```
> :sparkles: Introduce Network Provider Type NSXT_VPC

- pkg/vmprovider/providers/vsphere2/virtualmachine/configspec.go
- pkg/vmprovider/providers/vsphere2/virtualmachine/configspec_test.go
The VC placement call PlaceVmsXCluster() cannot cope with VirtualEthernetCards that do not have a backing. Since a backingless card cannot really influence the placement decision remove them from the ConfigSpec used for placement. The underlying bug appears to only impact VirtualEthernetCards.
Backingless VirtualEthernetCards can occur in NSX-T since we cannot resolve the DVPG from the LSX-T LogicalSwitchUUID until we know the CCR. The backing is assigned after placement when we know the CCR so the VM is created on the correct DVPG.
```release-note
NONE
```
> 🐛 Remove backingless VirtualEthernetCards from placement ConfigSpec

- webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
- webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_unit_test.go
While we still do the right thing if this is not set, by ensuring the network type is set v1a1 version conversion will show the correct networkType.
I'm just doing this on the create for now. Update will get sorted out later on multi-nic / the fly network changes work.
```release-note
NONE
```
> 🌱 Ensure Network field is set in network interfaces

- pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
This was missed in ee239cf5.
Fixes #
```release-note
NONE
```
> 🌱 Use API VirtualMachineImageV1Alpha1Compatible const

- pkg/vmprovider/providers/vsphere2/vmprovider_vm.go
Until we can clean up the larger issues around this code this will prevent another missed assignment like was fixed in aac0374c.
Fixes #
```release-note
NONE
```
> 🌱 Assign whole BootstrapData struct in VM update reconcile path

- .github/workflows/ci.yml
- Dockerfile
This fixes recent CVEs.
Fixes #
```release-note
NONE
```
>  🌱 Bump go version to 1.21.8

- webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
- webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
Since TCP ReadinessProbe won't work in VPC networking. Update the validation webhook to disallow that field when under VPC networking.
Fixes N/A
Testing done:
- When TCP readinessProbe specified in VM deployment yaml, validation webhook will throw an error.
```
readinessProbe:
tcpSocket:
port: 8888
periodSeconds: 30
timeoutSeconds: 20
---
Error from server (spec.readinessProbe.tcpSocket: Forbidden: VPC networking doesn't allow TCP readiness probe to be specified): error when creating "vm-read.yaml": admission webhook …
```
> :sparkles: Disallow TCP readiness probe under VPC Networking

- controllers/volume/v1alpha2/volume_controller.go
- controllers/volume/v1alpha2/volume_controller_unit_test.go
When find the CnsNodeVmAttachments for the given VM, we need to match up the attachments' Spec.NodeUUID with the VM's BiosUUID. Add an index on the NodeUUID field so that if the namespace has a lot of attachments the List() only returns the attachments for our VM.
Fixes #
This is just a WIP MR.
```release-note
NONE
```
> ✨ Add client Index on the CnsNodeVmAttachment Spec.NodeUUID

- api/v1alpha1/virtualmachine_types.go
- config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
- docs/concepts/workloads/guest.md
- docs/concepts/workloads/vm-example.yaml
- docs/concepts/workloads/vm.md
- docs/ref/api/v1alpha1.md
- docs/ref/api/v1alpha2.md
- docs/start/contrib/submit-change.md
- docs/tutorials/deploy-apps/nfs-server-and-client.md
- docs/tutorials/deploy-vm/README.md
- docs/tutorials/deploy-vm/cloudinit.md
- docs/tutorials/deploy-vm/vappconfig.md
- docs/tutorials/troubleshooting/ip-assignment.md
- docs/tutorials/troubleshooting/publish-vm.md
This patch updates the in-repo documentation for v1alpha2.
Fixes `NA`
```release-note
Update documentation for v1alpha2
```
----
📚 Documentation preview 📚: https://vm-operator--434.org.readthedocs.build/en/434/
> 📖 Update docs for v1alpha2

- controllers/volume/v1alpha2/volume_controller.go
- controllers/volume/v1alpha2/volume_controller_unit_test.go
When the PVC for a Volume changes the prior CnsNodeVmAttachment needs to be deleted and a new one that refers to the new ClaimName needs to be created. since CNS won't reconcile an already attached volume.
Fixes #
All the more reason that I want to remove the CnsNodeVmAttachment workflow and do this in house.
```release-note
NONE
```
> 🌱 Handle when the Volume PVC ClaimName is changed

- config/local/vmoperator/local_env_var_patch.yaml
- config/wcp/vmoperator/manager_env_var_patch.yaml
- pkg/config/config.go
- pkg/config/default.go
- pkg/config/env.go
- pkg/config/env/env.go
- pkg/config/env_test.go
- webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator.go
- webhooks/virtualmachine/v1alpha2/validation/virtualmachine_validator_unit_test.go
This patch removes the sysprep FSS.
Fixes `NA`
```release-note
Remove the FSS_WCP_WINDOWS_SYSPREP feature state.
```
> ✨ Remove sysprep FSS

- api/v1alpha1/virtualmachineimage_types.go
- api/v1alpha2/virtualmachineimage_types.go
- config/crd/bases/vmoperator.vmware.com_virtualmachineimages.yaml
- config/local/vmoperator/local_env_var_patch.yaml
- config/wcp/vmoperator/manager_env_var_patch.yaml
- controllers/contentlibrary/v1alpha2/contentlibraryitem/contentlibraryitem_controller_suite_test.go
- controllers/controllers.go
- controllers/virtualmachinepublishrequest/v1alpha2/virtualmachinepublishrequest_controller.go
- controllers/virtualmachinepublishrequest/v1alpha2/virtualmachinepublishrequest_controller_suite_test.go
- pkg/config/config.go
- pkg/config/default.go
- pkg/config/env.go
- pkg/config/env/env.go
- pkg/config/env_test.go
- pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
- test/builder/test_suite.go
- test/builder/util.go
- webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator.go
- webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_intg_test.go
- webhooks/virtualmachine/v1alpha2/mutation/virtualmachine_mutator_unit_test.go
- webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator.go
- webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator_intg_test.go
- webhooks/virtualmachinepublishrequest/v1alpha2/validation/virtualmachinepublishrequest_validator_unit_test.go
This patch removes the image registry FSS.
Fixes `NA`
```release-note
Remove the FSS_WCP_VM_IMAGE_REGISTRY feature state.
```
> ✨ Remove image registry FSS

- config/local/vmoperator/local_env_var_patch.yaml
- config/wcp/vmoperator/manager_env_var_patch.yaml
- pkg/config/config.go
- pkg/config/default.go
- pkg/config/env.go
- pkg/config/env/env.go
- pkg/config/env_test.go
This patch removes the unified TKG FSS.
Fixes `NA`
```release-note
Remove the FSS_WCP_Unified_TKG feature state.
```
> ✨ Remove unified TKG FSS

- api/v1alpha1/virtualmachineclass_types.go
- api/v1alpha2/virtualmachineclass_types.go
- config/crd/bases/vmoperator.vmware.com_virtualmachineclasses.yaml
- pkg/config/config.go
- pkg/config/default.go
- pkg/config/env.go
- pkg/config/env/env.go
- pkg/config/env_test.go
- pkg/vmprovider/providers/vsphere2/vmprovider_vm_utils_test.go
- test/builder/test_suite.go
- webhooks/virtualmachineclass/v1alpha2/mutation/virtualmachineclass_mutator_intg_test.go
- webhooks/virtualmachineclass/v1alpha2/validation/virtualmachineclass_validator_intg_test.go
This patch removes the namespaced VM Class FSS.
Fixes `NA`
```release-note
Remove the FSS_WCP_NAMESPACED_VM_CLASS feature state.
```
> ✨ Remove namespaced VM Class FSS

- config/local/vmoperator/local_env_var_patch.yaml
- config/wcp/vmoperator/manager_env_var_patch.yaml
Feature state switch flags are used by internal testing to determine the state of the feature. Since this is used by older branches as well, the flags must remain, otherwise the absence of the flag indicates a feature is not present or is disabled.
Fixes #
Related to #448, #450, #451, #452, #453, and #454.
```release-note
NONE
```
> 🌱 Reintroduce FSS flags for internal testing

- config/local/vmoperator/local_env_var_patch.yaml
- config/wcp/vmoperator/manager_env_var_patch.yaml
- pkg/builder/auth.go
- pkg/config/config.go
- pkg/config/default.go
- pkg/config/env.go
- pkg/config/env/env.go
- pkg/config/env_test.go
- pkg/providers/vsphere/vmprovider_vm.go
- pkg/providers/vsphere/vmprovider_vm_test.go
- test/builder/vcsim_test_context.go
- webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
This PR adds a new FSS for ISO support and removes the unnecessary FSS check code for the existing B/R FSS as it's already enabled on main.
```release-note
Add feature state switch for the VM deployment ISO support.
```
> 🌱 Introduce FSS for ISO support

- Makefile
- docs/concepts/services-networking/vm-service.md
- docs/concepts/workloads/guest.md
- docs/concepts/workloads/vm-class.md
- docs/concepts/workloads/vm-example.yaml
- docs/concepts/workloads/vm.md
- docs/ref/api/v1alpha1.md
- docs/ref/api/v1alpha3.md
- docs/tutorials/deploy-apps/nfs-server-and-client.md
- docs/tutorials/deploy-vm/README.md
- docs/tutorials/deploy-vm/cloudinit.md
- docs/tutorials/deploy-vm/vappconfig.md
- mkdocs.yml
This patch updates the content under the docs directory to reference v1alpha3 for all examples.
Fixes `NA`
```release-note
Update ./docs content to reference v1alpha3.
```
----
📚 Documentation preview 📚: https://vm-operator--488.org.readthedocs.build/en/488/
> 📖 Update docs to reference v1alpha3

- hack/verify-codegen.sh
This patch updates the GitHub action that verifies codegen so that the generate-go-conversions target is checked as well.
Fixes `NA`
Related to #490 
```release-note
Add GitHub action for verifying generate-go-conversions has been executed
```
> 🌱 GitHub action verify-codegen checks conversions

- config/local/vmoperator/local_env_var_patch.yaml
- config/wcp/vmoperator/manager_env_var_patch.yaml
- pkg/config/config.go
- pkg/config/env.go
- pkg/config/env/env.go
- pkg/config/env_test.go
Add planned FSS for VM resize work
Fixes #
```release-note
NONE
```
> ✨ Add FSS_WCP_VMSERVICE_RESIZE

- webhooks/virtualmachine/validation/virtualmachine_validator.go
- webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Since we disallow empty class names on create don't allow updates to an empty class either.
Fixes #
#502 will fallout once that is merged
```release-note
NONE
```
> 🌱 Allow updates to ClassName when VM resize is enabled

- pkg/util/resize/configspec.go
- pkg/util/resize/configspec_test.go
- pkg/util/resize/resize_suite_test.go
Once some other surrounding support is in place, much of the remaining resize work will be in here as we compare more & more of the current and desired states to build up the full Reconfigure ConfigSpec.
Fixes #
More thought will be needed on how to best organize the tests since this will be unwieldy with all the fields
```release-note
NONE
```
> 🌱 Add very basic resize config spec function

- controllers/virtualmachine/virtualmachine_controller.go
The same finished reconciling log message is done in the defer()
Fixes #
```release-note
NONE
```
> 🌱 Remove duplicated log in VM controller

- docs/concepts/workloads/vm-controller.md
As a follow up on https://github.com/vmware-tanzu/vm-operator/pull/469, update VM Controller workflow when it comes to pause annotation and ec key.
Fixes N/A
```release-note
NONE
```
----
📚 Documentation preview 📚: https://vm-operator--489.org.readthedocs.build/en/489/
> :book: Update doc regarding pause annotation and ec key

- pkg/config/config.go
- pkg/config/env.go
- pkg/config/env/env.go
- pkg/config/env_test.go
This patch introduces the feature flag for `FSS_WCP_MOBILITY_VM_IMPORT_NEW_NET`.
Fixes `NA`
I am going to remove the addition of the FSS from #510 so I can work on yet another PR that will depend on this FSS ahead of #510 being merged.
```release-note
Introduce the feature flag FSS_WCP_MOBILITY_VM_IMPORT_NEW_NET
```
> ✨ Add FSS_WCP_MOBILITY_VM_IMPORT_NEW_NET

- webhooks/virtualmachine/mutation/virtualmachine_mutator.go
- webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
This patch protects the VirtualMachine field spec.biosUUID from being set when a new VM is created unless by a privileged user. This logic resides in the VM's mutation webhook instead of the validation webhook, since the former also defaults the value, and the latter would have no way of knowing if the default value originated from the instigating user or the mutation webhook.
Fixes  `NA`
This effectively reverts https://github.com/vmware-tanzu/vm-operator/pull/494, but in a safe manner that will not break internal, e2e …
>  🌱 Protect VirtualMachine spec.biosUUID

- docs/concepts/workloads/guest.md
- docs/concepts/workloads/vm.md
----
📚 Documentation preview 📚: https://vm-operator--492.org.readthedocs.build/en/492/
> docs: add spec.biosUUID and cloudInit.instanceID

- pkg/topology/availability_zones_test.go
This patch increases the code coverage for `pkg/topology` to above 90%.
Fixes `NA`
```release-note
NONE
```
> 🌱 Increase coverage for pkg/topology to above 90%

- pkg/patch/patch_test.go
- pkg/patch/suite_test.go
The coverage for `pkg/patch` was effectively disabled. This patch re-enables it.
Fixes `NA`
```release-note
NONE
```
> 🌱 Fix issue with pkg/patch coverage

- pkg/builder/builder_suite_test.go
- pkg/builder/mutating_webhook.go
- pkg/builder/mutating_webhook_test.go
- pkg/builder/validating_webhook_test.go
This patch increases the code coverage for pkg/builder to above 95%!
Fixes `NA`
```release-note
NONE
```
> 🌱 Increase coverage for pkg/builder >95%

- pkg/providers/vsphere/network/netplan.go
- pkg/providers/vsphere/vmlifecycle/bootstrap_cloudinit.go
This patch continues to handle fixes for the update from the old YAML package to sigs.k8s.io/yaml. Please see
https://github.com/vmware-tanzu/vm-operator/pull/542 and https://github.com/vmware-tanzu/vm-operator/pull/544 for more information.
Fixes `NA`
```release-note
NONE
```
> 🐛 Additional fixes for YAML->JSON tags

- pkg/providers/vsphere/session/session.go
- pkg/providers/vsphere/session/session_suite_test.go
- pkg/providers/vsphere/session/session_vm_update.go
- pkg/providers/vsphere/session/session_vm_update_test.go
- pkg/providers/vsphere/vmprovider_vm.go
- test/builder/vcsim_test_context.go
This patch increases the code coverage for the session package from 33% to 76%.
Fixes `NA`
```release-note
NONE
```
> 🌱 Increase coverage for session pkg from 33-->76%

- pkg/prober/prober_manager_test.go
This patch increases the code coverage for the prober package from 55 to 91%!
Fixes `NA`
```release-note
NONE
```
> 🌱 Increase coverage for prober from 55-->91%

- pkg/util/resize/configspec.go
- pkg/util/resize/configspec_test.go
The actual comparison function is cribbed from the existing session update code.
Fixes #
```release-note
NONE
```
> 🌱 Handle resize of vGPU and DDPIO devices

- controllers/virtualmachine/virtualmachine_controller.go
- controllers/virtualmachine/virtualmachine_controller_intg_test.go
An empty VMClass.Spec.ControllerName name would not cause us to reconcile the VMs when its VM Class was changed.
Fix requeueDelay() to only fall into the IP retry if the VM is expected to have networking in the first place.
Fix several integration test issues:
Use a valid UUID for dummy InstanceUUID. The prior value along with the schema upgrade would fail due to field validation. Due to how the patch helpers breaks up the patches, this was causing an error retry instead of the expected requeueDelay() usage.
Remove a bogus Creating Phase test: the controller used to set the Phase in some cases, but Phase is gone and the controller doesn't set Conditions directly. This test wasn't really testing anything.
Fix a race when testing VM deletion …
> 🐛 Fix VM controller VM Class reconcile request handler

- pkg/providers/vsphere/constants/constants.go
The usage of these went away with the image registry work.
Fixes #
```release-note
NONE
```
> 🌱 Remove unused VM Image related annotation consts

- pkg/util/resize/configspec.go
- pkg/util/resize/configspec_test.go
This change supports resizing memory allocation and memory hot add for a virtual machine
Fixes # N/A
N/A
```
Resize Memory Allocation and Memory Hot Add
```
>  ✨ Resize Memory Allocation and Memory Hot Add

- pkg/providers/vsphere/network/network.go
Some refactoring had resulted in these comments be far away from the relevant code.
Fixes #
```release-note
NONE
```
> 🌱 Move comment about default network to right spot

- pkg/util/vmopv1/resize_overwrite.go
- pkg/util/vmopv1/resize_overwrite_test.go
Another small step towards replacing the current pre-power on reconfigure with resize.
Fixes #
```release-note
NONE
```
> 🌱 Resize: VM.Spec.GuestID support

- pkg/providers/vsphere/vmlifecycle/update_status.go
- pkg/providers/vsphere/vmlifecycle/update_status_test.go
Follow on to 2b31456d3f7ea. Note that the not-classless will change again as a part of the resize work to only update it after a resize.
Fixes #
```release-note
NONE
```
> 🌱 Don't backfill VM Status.Class in classless VMs

- pkg/providers/vsphere/session/session_vm_update.go
- pkg/providers/vsphere/vmprovider_vm_resize_test.go
This uses resize to generate the ConfigSpec that is needed to reconfigure the VM prior to power on. The resize ConfigSpec does not cover everything that the existing prePowerOnVMResizeConfigSpec does - namely network devices - but that gap will be closed over time.
Fixes #
```release-note
NONE
```
> ✨ Initial resize when powering on VM support

- go.mod
- go.sum
- pkg/providers/vsphere/vmlifecycle/create.go
- pkg/providers/vsphere/vmlifecycle/create_contentlibrary.go
- pkg/providers/vsphere/vmprovider_vm.go
- pkg/providers/vsphere/vmprovider_vm_test.go
- test/builder/vcsim_test_context.go
Combine Sai's deployISO PoC and lookup Datastore from storage policy for spec.Files.VmPathName
> Support VM creation from ISO type library items

- pkg/util/resize/configspec.go
- pkg/util/resize/configspec_test.go
Change to support resize of SGX ( software guard extension ) for VMs.
Fixes # N/A
N/A
```
Resize SGX  (Software Guard Extension) for VMs
```
> ✨Resize SGX (Software Guard Extension) for VMs

- config/local/vmoperator/local_env_var_patch.yaml
- config/wcp/vmoperator/manager_env_var_patch.yaml
- pkg/config/config.go
- pkg/config/env.go
- pkg/config/env/env.go
- pkg/config/env_test.go
- pkg/providers/vsphere/vmlifecycle/update_status_test.go
- test/builder/vcsim_test_context.go
- webhooks/virtualmachine/validation/virtualmachine_validator.go
- webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
This is for limited resize that just cares about CPUs and memory.
Fixes #
```release-note
NONE
```
> 🌱 Add FSS_WCP_VMSERVICE_RESIZE_CPU_MEMORY

- pkg/util/resize/backings.go
- pkg/util/resize/backings_test.go
- pkg/util/resize/configspec_devices.go
- pkg/util/resize/configspec_devices_test.go
Start to flesh out handling resize of some of the easier device types. For these types, zip the expected and current devices of the same type together, and add, remove or edit as needed to update the VM configuration.
Fixes #
```release-note
NONE
```
> ✨ resize: Start to handle more device types

- .github/workflows/ci.yml
- Dockerfile
- api/go.mod
- go.mod
- hack/tools/go.mod
- pkg/util/image/status_to_label.go
- pkg/util/image/status_to_label_test.go
This PR has bug fixes for the patch release P04 for vCenter 8.0.3
- Update golang to v1.22.5 to fix CVEs
- Check for valid image OS image labels keys and values
Fixes # N/A
N/A
```
Bug fixes for the patch release P04 for vCenter 8.0.3
- Update golang to v1.22.5 to fix CVEs
- Check for valid image OS image labels keys and values
```
> 🐛 Bug fixes for Release 8.0.3 P04

- config/local/vmoperator/local_env_var_patch.yaml
- config/wcp/vmoperator/manager_env_var_patch.yaml
- pkg/config/config.go
- pkg/config/env.go
- pkg/config/env/env.go
- pkg/config/env_test.go
Add FSS to support incremental and partial VM restores
Fixes # N/A
N/A
```
NONE
```
>  🌱 Add FSS_WCP_VMSERVICE_INCREMENTAL_RESTORE

- docs/ref/api/v1alpha3.md
Update API docs
Fixes #
```release-note
NONE
```
----
📚 Documentation preview 📚: https://vm-operator--646.org.readthedocs.build/en/646/
> 📖 Update docs for recent VM Status storage changes

- controllers/virtualmachinewebconsolerequest/v1alpha1/webconsolerequest_intg_test.go
- controllers/virtualmachinewebconsolerequest/v1alpha2/webconsolerequest_intg_test.go
- hack/tools/Makefile
This version is closer to what is actually used
Fixes #
No minor releases avail
```release-note
NONE
```
> 🌱 Update envtest k8s version to 1.29.1

- controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
- controllers/virtualmachine/virtualmachine/virtualmachine_controller_unit_test.go
Only emit a default event if ReconcileNormal fails and it was neither a create nor update op.
While here, fix a long standing bug if that we should update the probe manager status even if CreateOrUpdate fails. If the VM Spec.ReadinessProbe has been changed we should update what's being probed even if we reconcile fails for some reason.
Fixes #
```release-note
The VM CreateOrUpdateFailure event is renamed to ReconcileNormalFailure and only emitted on neither create or update …
```
> 🌱 Avoid duplicate VM ReconcileNormal events

- config/local/vmoperator/local_env_var_patch.yaml
- config/wcp/vmoperator/manager_env_var_patch.yaml
- pkg/config/config.go
- pkg/config/env.go
- pkg/config/env/env.go
- pkg/config/env_test.go
This patch defines the FSS for Bring Your Own Encryption Key.
Fixes `NA`
```release-note
Define FSS for bring your own (encryption) key (BYOK)
```
> 🌱 Define FSS for Bring your own (encryption) key (BYOK)

- pkg/providers/vsphere/virtualmachine/backup.go
Fixes #
```release-note
NONE
```
> 🌱 Use string.Builder for backup yaml doc

- pkg/providers/vsphere/virtualmachine/backup.go
For VMs with like a bunch of volumes we don't need to decode the whole VM since we're only comparing fields in the metadata.
Use maps.Equal instead of DeepEqual to compare the label and annotation string maps.
Fixes #
```release-note
NONE
```
> 🌱 Use PartialObjectMetadata to unmarshal VM for backup needed check

- docs/concepts/workloads/vm.md
- docs/start/quick.md
Also Correct zone label docs since it cannot change after being set.
Fixes #
```release-note
Add documentation for VM Resizing.
```
----
📚 Documentation preview 📚: https://vm-operator--669.org.readthedocs.build/en/669/
> 📖 Add initial VM resize docs

- api/v1alpha3/virtualmachine_storage_types.go
- config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
The Limit field is set for both Classic and Managed (PVC) disks.
Fixes #
```release-note
NONE
```
> 📖 Remove stale VirtualMachineVolumeStatus comment

- config/local/vmoperator/local_env_var_patch.yaml
- config/wcp/vmoperator/manager_env_var_patch.yaml
- controllers/infra/capability/infra_capability_controller.go
- controllers/infra/capability/infra_capability_controller_intg_test.go
- controllers/infra/capability/infra_capability_controller_unit_test.go
- main.go
- pkg/config/capabilities/capabilities_suite_test.go
- pkg/config/capabilities/capabilities_test.go
- pkg/config/capabilities/capabilties.go
- pkg/config/config.go
- pkg/config/env.go
- pkg/config/env/env.go
- pkg/config/env/env_suite_test.go
- pkg/config/env_test.go
- pkg/manager/init/init_providers.go
Initialize our context Features with the current state of the capabilities.
Fixes #
```release-note
NONE
```
> ✨ Use capabilities at start up time

- controllers/virtualmachine/volume/volume_controller.go
- controllers/virtualmachine/volume/volume_controller_unit_test.go
The uncached Get() of every VM's PVCs on each reconcile causes an unacceptable perf regression.
The memory limit bump fallout from this change will be addressed later.
For now, keep the deferred instance-storage specific cache Watch(). It only matches IS PVCs via the label selector its cost is negligible but can be removed in a later commit.
Fixes #
```release-note
NONE
```
> 🐛 Use cached Get() of PVCs in Volume controller

- pkg/providers/vsphere/config/config.go
- pkg/providers/vsphere/config/config_test.go
For some env this will be empty. Nameservers can be set via the VM Spec.Network
Fixes #
```release-note
No nameservers in the vmoperator-network-config ConfigMap does not prevent customization
```
> 🐛 Don't fail if nameservers are empty in network CM

- api/v1alpha1/virtualmachine_conversion_test.go
- api/v1alpha2/virtualmachine_conversion_test.go
Use KeyWithValue() for conversation annotation testing and remove unnecessary line
Fixes # N/A
N/A
```
NONE
```
> 🌱  Use KeyWithValue() for conversation annotation testing

- Makefile
Fixes #
Just in case this package later gains dependencies
```release-note
NONE
```
> Include pkg/backup/api in make modules target

- controllers/infra/validatingwebhookconfiguration/validatingwebhookconfiguration_controller_intg_test.go
- webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_suite_test.go
- webhooks/unifiedstoragequota/validation/unifiedstoragequota_validator_unit_test.go
The PR refactors the unit tests in `webhooks/unifiedstoragequota/validation` to use Ginkgo in order to maintain consistency with the other tests in this project.
Fixes #
```release-note
NONE
```
> :seedling: Refactor unifiedstoragequota validating webhook unit tests to use Ginkgo

- controllers/virtualmachine/volume/volume_controller_unit_test.go
Fixes #
```release-note
NONE
```
> 🌱 Use fake client interceptor funcs for insufficient quota PVC test

- pkg/providers/vsphere/vmprovider_vm.go
This was already assigning each field so use the whole struct instead.
Fixes #
```release-note
NONE
```
> 🌱 Use struct assignment to copy bootstrap data

- docs/concepts/workloads/vm.md
This patch updates the vm documentation with information about:
* Encryption
* Storage quota
* Identifiers
The patch also rewrites a bunch of the docs to be more consistent with the overall patterns/conventions of the material.
Fixes `NA`
```release-note
Documentation on encryption, storage, identifiers
```
----
📚 Documentation preview 📚: https://vm-operator--772.org.readthedocs.build/en/772/
> 📖 Doc updates

- pkg/providers/vsphere/vcenter/cluster.go
We don't need the rest of the Summary or Hardware properties for this single field.
Fixes #
```release-note
NONE
```
> 🌱 Fetch only Host Summary.Hardware.cpuMhz for min CPU calculation

- main.go
- pkg/config/capabilities/capabilties.go
Swap old/new params to the cmp.Diff used to log feature changes so that changes shown as expected
Fixes #
```release-note
NONE
```
> 🌱 Add capabilities scheme to init features client scheme

- docs/concepts/workloads/vm.md
- docs/ref/api/v1alpha1.md
- docs/ref/api/v1alpha2.md
- docs/ref/api/v1alpha3.md
While here, regen the API docs too
Fixes #
```release-note
NONE
```
----
📚 Documentation preview 📚: https://vm-operator--798.org.readthedocs.build/en/798/
> 📖 Document ClassConfigurationSynced condition

- controllers/infra/zone/zone_controller.go
Later we may want to also put a finalizer on the Zone for the VirtualMachineSetResourcePolicy so switch to a more unique name now.
Fixes #
```release-note
NONE
```
> 🌱 Use unique finalizer name for infra Zone controller

- controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
- controllers/virtualmachine/virtualmachine/virtualmachine_controller_unit_test.go
- pkg/providers/vsphere/vmprovider_vm.go
This PR includes two patches:
1. **Refactor chanErr creation in async create**
This patch changes the way the error channel is created during the async create workflow to make this more explicit and reduces the chances someone does not close the channel.
2. **Refactor chanErr consumption in VM controller**
This patch changes the way the error channel from the async create workflow is consumed in the VirtualMachine controller.
Previously only a single error was assumed to be returned, but since this is a channel, the consumer should range over it, accounting for the possible vim and k8s error.
**Which issue(s) is/are addressed by this PR?** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) …
> 🌱 Refactor chanErr creation & consumption for async create VM workflow

- go.mod
Leftover from ac937e71bb1c472780719df0b70edbedf168f27d
Fixes #
```release-note
NONE
```
> 🌱 Remove stale envoyproxy go.mod replace entries

- controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
These logs are not worth the noise, especially for classes that aren't being used by any VMs in the namespace.
Fixes #
The performance of this mapper when there are lots of VM and/or VM Classes in a namespace is a bit of a concern. 
```release-note
NONE
```
>  🌱 Raise log level of VM Class to VM request mapper func

- .golangci.yml
- pkg/providers/vsphere/storage/provisioning.go
- pkg/providers/vsphere/vmprovider_vm.go
Fixes #
```release-note
NONE
```
>  🌱 Use consistent import alias for govmomi/pbm/types

- controllers/infra/configmap/infra_configmap_controller.go
- controllers/virtualmachine/volume/volume_controller.go
Fixes #
```release-note
NONE
```
> 🌱 Simplify with controller-runtime IgnoreNotFound() helper

- pkg/providers/vsphere/config/config.go
- pkg/providers/vsphere/config/config_test.go
These haven't been used in a long time.
Fixes #
```release-note
Remove unused Folder and ResourcePool fields from the configuration.
```
> 🌱 Remove Folder and ResourcePool from VC config

- controllers/virtualmachine/virtualmachine/virtualmachine_controller.go
- pkg/errors/errors_suite_test.go
- pkg/errors/requeue_error.go
- pkg/errors/requeue_error_test.go
- pkg/providers/vsphere/virtualmachine/delete.go
- pkg/providers/vsphere/virtualmachine/delete_test.go
- pkg/providers/vsphere/vmprovider_vm.go
- pkg/providers/vsphere/vmprovider_vm_test.go
- pkg/util/vsphere/watcher/watcher.go
This PR cross-ports #896 and #899.
Fixes `NA`
```release-note
Do not update/delete non-connected VMs.
```
> [x-port 9.0] 🌱 Do not update/delete non-connected VMs

- pkg/providers/vsphere/session/session_vm_update.go
Leftover from some early-early v1a2 work
Fixes #
```release-note
NONE
```
> 🌱 Remove old network import alias in provider

- controllers/virtualmachine/volume/volume_controller_intg_test.go
This provider better details when something fails.
Fix one place that was using an Eventually that an attachment was not created with a Consistently.
Fixes #
```release-note
NONE
```
>  🌱  Use Gomega asserts in Eventually/Consistently checks Volume integration tests

- api/v1alpha3/virtualmachine_types.go
- api/v1alpha4/virtualmachine_types.go
Fixes #
```release-note
NONE
```
> 📖 Fix var name in description of backup condition reasons

- controllers/virtualmachineimagecache/virtualmachineimagecache_controller.go
- controllers/virtualmachinepublishrequest/virtualmachinepublishrequest_controller.go
- controllers/virtualmachinereplicaset/virtualmachinereplicaset_controller.go
- controllers/virtualmachinewebconsolerequest/v1alpha1/conditions/getter.go
- controllers/virtualmachinewebconsolerequest/v1alpha1/conditions/merge.go
- hack/test.sh
- pkg/conditions/conditions.go
- pkg/conditions/getter.go
- pkg/conditions/merge.go
- pkg/conditions/setter.go
- pkg/conditions/setter_test.go
- pkg/prober/worker/readiness_worker.go
- pkg/providers/vsphere/session/session_vm_update.go
- pkg/providers/vsphere/virtualmachine/backup.go
- pkg/providers/vsphere/vmlifecycle/update_status.go
- pkg/providers/vsphere/vmlifecycle/update_status_test.go
- pkg/providers/vsphere/vmprovider_vm.go
- pkg/providers/vsphere/vmprovider_vm_utils.go
- pkg/providers/vsphere/vmprovider_vm_utils_test.go
- pkg/vmconfig/crypto/crypto_reconciler.go
- pkg/vmconfig/crypto/crypto_reconciler_pre.go
Since conditions.MarkFalse(..., err.Error()) is so common add MarkError() to simplify that pattern.
Fixes #
```release-note
NONE
```
> 🌱 Fix new go vet non const printf warnings

- test/builder/vcsim_test_context.go
Only create the old ResourceQuota when the relevant FFS is not enabled to closer match the real env in case we want to start enforcing the SC namespace association during reconcile.
Fixes #
```release-note
NONE
```
>  🌱 Create StoragePolicyQuota in vcsim test env

- webhooks/virtualmachine/validation/virtualmachine_validator.go
Make some style and variable names (vm, oldVM) consistent
Reorder a few things in validateImageOnUpdate() to reduce some unneeded checks in the common case
Always pass along the WebhookRequestContext instead of the context.Context, and use _ when the param is unused to silence some Goland linter warnings
Fixes #
```release-note
NONE
```
> 🌱  Various VM validation webhook clean up

- pkg/providers/vsphere/network/network.go
- pkg/providers/vsphere/network/network_test.go
This was an oversight from the original code. Do not attempt to use an existing network interface that is currently controller owned by another VM. For any existing situations where the interface has an controller owner that is not a VM add just an owner ref like before to keep things working.
Fixes #
```release-note
Set the VirtualMachine as the controller owner ref on the network interface custom resources.
```
>  🌱 Set VM as controller owner ref on network interfaces

- docs/concepts/workloads/guest.md
Fixes #
```release-note
NONE
```
----
📚 Documentation preview 📚: https://vm-operator--940.org.readthedocs.build/en/940/
> 📖  Fix swapped key and name field in cloud init example

- webhooks/virtualmachine/mutation/virtualmachine_mutator.go
- webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
When network interfaces are added, initialize the interface spec Network reference field based on network provider like we do on create.
Fixes #
```release-note
NONE
```
> 🌱 Initialize VM interface Network reference on update

- api/v1alpha2/virtualmachine_network_types.go
- api/v1alpha3/virtualmachine_network_types.go
- api/v1alpha4/virtualmachine_network_types.go
- config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
- config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
Fixes #955
```release-note
NONE
```
> 📖  Remove stale comment about network interface spec Addresses field

- docs/requirements.txt
This patch updates several dependencies used to build the project documentation:
- mkdocs                                    `1.5.3`  --> `1.6.1`
- mkdocs-material                           `9.5.3`  --> `9.6.14`
- pymdown-extensions                        `10.5`   --> `10.15`
- pygments                                  `2.17.2` --> `2.19.1`
- mkdocs-git-committers-plugin-2            `2.2.2`  --> `2.5.0`
- mkdocs-git-revision-date-localized-plugin `1.2.2`  --> `1.4.5`
- mkdocs-markdownextradata-plugin           `0.2.5`  --> `0.2.6`
Fixes `NA`
**Are there any special notes …
> 📖 Update mkdocs deps used to build docs

- pkg/config/capabilities/capabilities_test.go
- pkg/config/capabilities/capabilties.go
- pkg/config/config.go
Used #972 as the template for this PR, thanks @dilyar85
> Add Capability for Immutable VM Classes

- api/v1alpha2/virtualmachine_network_types.go
- api/v1alpha3/virtualmachine_network_types.go
- api/v1alpha4/virtualmachine_network_types.go
- config/crd/bases/vmoperator.vmware.com_virtualmachinereplicasets.yaml
- config/crd/bases/vmoperator.vmware.com_virtualmachines.yaml
- pkg/providers/vsphere/network/netplan_test.go
- pkg/providers/vsphere/network/network_test.go
- webhooks/virtualmachine/validation/virtualmachine_validator.go
- webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Fixes #
```release-note
VirtualMachine Spec.Network.Interfaces[].Routes[].To value to be set to "default" to specify the default route
```
> 🌱 Allow 'default' for routes To value

- pkg/providers/vsphere/session/session_vm_update.go
- pkg/providers/vsphere/vmprovider_vm_test.go
This patch fixes an issue created by #980 where an update reconfig was not occurring for VMs being powered on if the VM Resize CPU & Memory FSS was enabled.
Fixes `NA`
```release-note
Only use resize path when full VMResize FSS is enabled.
```
> 🐛 Fix issue adding cd-roms to powering on VMs

- docs/ref/api/v1alpha2.md
- docs/ref/api/v1alpha3.md
- docs/ref/api/v1alpha4.md
This patch updates the generated API markdown.
Fixes `NA`
```release-note
Update the generated API markdown files.
```
----
📚 Documentation preview 📚: https://vm-operator--1001.org.readthedocs.build/en/1001/
> 📖 Update generated API markdown

- pkg/providers/vsphere/virtualmachine/backup.go
Currently, when generating the backup manifest for a VM, or additional resources, we include the full object - which also includes the Status of the object.
The status of a resource is not useful during restore or failover anyway.  On the contrary, this increases the size of information stored in the VM's ExtraConfig, and thus, increasing the storage consumption of the VM.  Additionally, since Status is of significant size, VM operator has to spend extra CPU cycles and use memory to construct this payload.
This change drops the Status from all payloads stored as part of backup.
```release-note
Drop the Status sub-resource from payloads during backup
```
> :seedling: Drop the Status sub-resource from payloads during backup

- pkg/util/vmopv1/resize.go
- webhooks/virtualmachine/mutation/virtualmachine_mutator.go
- webhooks/virtualmachine/mutation/virtualmachine_mutator_unit_test.go
- webhooks/virtualmachine/validation/virtualmachine_validator.go
- webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
This change introduces the webhook mutations and validations for spec.className and spec.class of a VM.
The mutating webhook changes include:
- If spec.class is specified, but spec.className is omitted, the mutating webhook populates the spec.className with the class that owns the instance
- If spec.className is specified but spec.class is omitted, the mutating webhook picks the active instance and populates the spec.class with the instance.
- If both are specified, then mutating webhook is a pass-through.  The validating webhook will validate the request.
- If neither of them are specified, then mutating webhook is a pass-through.
The validating webhook changes include:
- If spec.className and spec.class both have been specified, they must …
> :seedling: Mutating and validating webhook changes for spec.class and spec.className

- hack/deploy-wcp.sh
Instead of assuming localhost/vmoperator-controller:latest use the tag from the manifests file and extract the first RepoTags value. This seems to be good enough for our images via make image-build.
Fixes #
```release-note
NONE
```
> 🌱 Grab image tag from container image for deploy-wcp

- api/v1alpha1/virtualmachine_conversion.go
Update comment to better reflect reality and just always restore the saved VM Spec.Network.Interfaces during up-convert. It is really hard to really support network mutability in v1a1, and with it being deprecated do the safer thing and just restore the save interfaces as-is.
Fixes #
```release-note
In VM v1alpha1 version up-convert, always restore the saved Spec.Network.Interfaces. In v1alpha1, uniquely identifying a network interface is difficult, and v1alpha2 or later should …
```
> 🌱 Update v1a1 network interfaces version up-convert

- config/webhook/manifests.yaml
- webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator.go
- webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator_intg_test.go
- webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator_suite_test.go
- webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator_unit_test.go
- webhooks/virtualmachinesnapshot/webhooks.go
- webhooks/webhooks.go
This is just to create the webhook folder as a placeholder for adding specific logic that validates the action on virtualmachinesnapshot
Fixes #
```release-note
Add virtualmachinesnapshot validation webhook
```
> 🌱 Add virtualmachinesnapshot validation webhook

- pkg/config/capabilities/capabilities_test.go
- pkg/config/capabilities/capabilties.go
- pkg/config/config.go
This change introduces a capability for VM AF/Anti-AF Placement Policies
Fixes # N/A
```
Introduces a capability for VM AF/Anti-AF Placement Policies
```
> 🌱 Introduce capability for VM AF/Anti-AF Placement Policies

- webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator.go
- webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator_intg_test.go
- webhooks/virtualmachinesnapshot/validation/virtualmachinesnapshot_validator_unit_test.go
Adds validation logic to webhooks for VMSnapshot resources
None
```release-note
NONE
```
> 🌱 Add VMSnapshot Validation Webhook logic

- webhooks/virtualmachine/validation/virtualmachine_validator.go
- webhooks/virtualmachine/validation/virtualmachine_validator_intg_test.go
- webhooks/virtualmachine/validation/virtualmachine_validator_unit_test.go
Adds validation for VirtualMachine currentSnapshot reference
None
```release-note
NONE
```
> vm: add snapshot validations

- pkg/providers/vsphere/vmprovider_vm.go
- pkg/providers/vsphere/vmprovider_vm_test.go
This PR updates the `vmCreateDoPlacement()` function to use VM Group placement results when `vm.spec.groupName` is specified. VMs without a group continue to use the existing placement logic. 
Fixes N/A.
Deployed this change to an internal testbed and verified the VM's placement set from its group:
- VM Group placement status (with mock data)
```
$ kubectl get vmg -n sdiliyaer-test vmg-test -o json | jq .status.members[0]
{
"conditions": [
{
"lastTransitionTime": "2025-07-22T14:32:04Z",
"message": "",
"reason": "True",
"status": "True",
"type": "GroupLinked"
},
{
"lastTransitionTime": "2025-07-22T14:32:04Z",
"message": "",
"reason": "none", …
```
> ✨ Set VM placement result from group if applicable

- pkg/providers/vsphere/virtualmachine/configspec.go
- pkg/providers/vsphere/virtualmachine/configspec_test.go
We want these considered for SRIOV 🤞 
Fixes #
```release-note
NONE
```
> 🌱 Add back Ethernet cards to placement ConfigSpec

- webhooks/common/utils.go
This PR sorts the content library names if multiple default ones are found to have a deterministic error message. 
Fixes # N/A
N/A
```release-note
```
> 🌱 sort the content library names if multiple default ones are found

- controllers/virtualmachine/storagepolicyusage/storagepolicyusage_controller.go
We don't need a map with the VirtualMachines as the value, just need a set of the VMs' names.
Make that we're sharing the VMs by using a pointer to the list items.
Fixes #
```release-note
NONE
```
> 🌱 Tweak StoragePolicyUsage controller allocs

- pkg/config/capabilities/capabilities.go
This patch adds support for the BYOK capability.
Fixes `NA`
```release-note
Respect the correct BYOK capability.
```
> 🌱 Support BYOK capability

- pkg/providers/vsphere/vmprovider_vm.go
- pkg/providers/vsphere/vmprovider_vm_test.go
Placement of a VM is driven via the VirtualMachineGroup if the VM is part of a group (specified by spec.groupName).  This means we don't send in the list of placement candidate resource pools to DRS when asking for placement recommendations.  DRS returns recommendations based on the hardware and the placement policies specified with the VM.
However, if a group member wants to explicitly be placed in a particular zone, they should be able to specify the zone label on the member.  This change adds support for that.  This will be used by VKS to support scale-outs of node pools.
```release-note
Support explicit zone specification from group members
```
> :seedling: Support explicit zone specification from group members

- pkg/config/capabilities/capabilities.go
- pkg/config/capabilities/capabilities_test.go
- pkg/config/config.go
This capability will guards the GOSC changes made for VCD parity.
Fixes #
```release-note
NONE
```
> 🌱 Add capability for VC_GuestCustomizationVCDParity

- pkg/builder/auth.go
Add a line in auth.go that will print the the
UserInfo object that is used to perform the isPrivilegedUser check. Log level 6 to keep from cluttering logs but to give the option for visibility into this.
Fixes #
```release-note
NONE
```
> Add a log statement that prints UserInfo object

- docs/concepts/workloads/vm-placement.md
- docs/concepts/workloads/vm.md
- mkdocs.yml
This patch adds a concept documentation page for how VM placement logic behaves.
Fixes `NA`
```release-note
Documents the VM placement concept.
```
----
📚 Documentation preview 📚: https://vm-operator--1184.org.readthedocs.build/en/1184/
> 📖 Add docs around VM placement
